// GENERATED by the Captain.Food codegen from specs/actors.yaml (`receives` +
// `mailbox.partitions` + `reminders`) -- do not edit by hand (PROP-20260802-130500 phase 2,
// #306). The typed mailbox client for ONE actor, in its OWN crate: depending on this crate is the
// permission to address `Restaurant`, and nothing else.
//
// The client constructs NOTHING itself. Every row is assembled behind `actor_client::ActorDoor`,
// whose delegates own the lane, partition, principal and channel derivation -- so a typed send
// here and the string-keyed reference implementation in `actor_client` cannot drift (the
// out-of-crate drift guard in `crates/actor_client/tests/drift_guard.rs` proves it field for
// field). `MailboxEntry` and `MailboxAccess` are not nameable from this crate at all.
//
// EVERY method is spec-gated (product-owner directive, 2026-08-02 -- the declaration is the
// permission): `send` + `RestaurantCommand` exist iff the actor receives >=1 COMMAND, `record` +
// `RestaurantFact` iff it receives >=1 inbound FACT, `schedule`/`cancel_scheduling` iff it declares
// `reminders:`. An unjustified surface is ABSENT -- a compile error at any call site -- never
// uncallable-but-present.

use std::sync::Arc;

use actor_client::mailbox::{Envelope, Mailbox};
use actor_client::{ActorDoor, EnqueueOutcome};
use domain::shared::errors::DomainError;

/// The privacy SEAL: `Sealed` lives in a private module, so it cannot be named -- let alone
/// implemented -- outside this GENERATED crate. Every marker trait below requires it, so the
/// receive set this actor declares in actors.yaml is the receive set, period: widening it takes a
/// spec change and a regeneration, never a stray downstream `impl`. Since phase 2 each actor owns
/// its own seal, so a sibling client crate cannot even name this actor's marker supertrait.
mod sealed {
    pub trait Sealed {}
}

impl sealed::Sealed for domain::generated::commands::ActivateRestaurant {}
impl sealed::Sealed for domain::generated::commands::ChangeOrderAcceptanceMode {}
impl sealed::Sealed for domain::generated::commands::ChangeRestaurantListingStatus {}
impl sealed::Sealed for domain::generated::commands::ClaimRestaurantListing {}
impl sealed::Sealed for domain::generated::commands::ConfigureGoogleBusinessProfileOrderLink {}
impl sealed::Sealed for domain::generated::commands::ConfigureRestaurantSlug {}
impl sealed::Sealed for domain::generated::commands::DeactivateRestaurant {}
impl sealed::Sealed for domain::generated::commands::MarkRestaurantClosed {}
impl sealed::Sealed for domain::generated::commands::OptOutRestaurantListing {}
impl sealed::Sealed for domain::generated::commands::RegisterRestaurant {}
impl sealed::Sealed for domain::generated::commands::RemoveRestaurant {}
impl sealed::Sealed for domain::generated::commands::UpdateRestaurant {}
impl sealed::Sealed for domain::generated::commands::UpdateRestaurantGoogleBusinessProfile {}
impl sealed::Sealed for domain::generated::commands::VerifyGoogleBusinessProfileOrderLink {}
impl sealed::Sealed for domain::generated::events::RestaurantRegistered {}

/// GENERATED from actors.yaml `Restaurant.receives`: marker for every COMMAND the `Restaurant` actor
/// receives. SEALED (private supertrait) so no impl can exist outside this generated crate --
/// sending a command this actor does not `receive` is a COMPILE error, not a runtime rejection.
pub trait RestaurantCommand: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the commands.yaml key).
    const MESSAGE_TYPE: &'static str;
}

impl RestaurantCommand for domain::generated::commands::ActivateRestaurant {
    const MESSAGE_TYPE: &'static str = "ActivateRestaurant";
}

impl RestaurantCommand for domain::generated::commands::ChangeOrderAcceptanceMode {
    const MESSAGE_TYPE: &'static str = "ChangeOrderAcceptanceMode";
}

impl RestaurantCommand for domain::generated::commands::ChangeRestaurantListingStatus {
    const MESSAGE_TYPE: &'static str = "ChangeRestaurantListingStatus";
}

impl RestaurantCommand for domain::generated::commands::ClaimRestaurantListing {
    const MESSAGE_TYPE: &'static str = "ClaimRestaurantListing";
}

impl RestaurantCommand for domain::generated::commands::ConfigureGoogleBusinessProfileOrderLink {
    const MESSAGE_TYPE: &'static str = "ConfigureGoogleBusinessProfileOrderLink";
}

impl RestaurantCommand for domain::generated::commands::ConfigureRestaurantSlug {
    const MESSAGE_TYPE: &'static str = "ConfigureRestaurantSlug";
}

impl RestaurantCommand for domain::generated::commands::DeactivateRestaurant {
    const MESSAGE_TYPE: &'static str = "DeactivateRestaurant";
}

impl RestaurantCommand for domain::generated::commands::MarkRestaurantClosed {
    const MESSAGE_TYPE: &'static str = "MarkRestaurantClosed";
}

impl RestaurantCommand for domain::generated::commands::OptOutRestaurantListing {
    const MESSAGE_TYPE: &'static str = "OptOutRestaurantListing";
}

impl RestaurantCommand for domain::generated::commands::RegisterRestaurant {
    const MESSAGE_TYPE: &'static str = "RegisterRestaurant";
}

impl RestaurantCommand for domain::generated::commands::RemoveRestaurant {
    const MESSAGE_TYPE: &'static str = "RemoveRestaurant";
}

impl RestaurantCommand for domain::generated::commands::UpdateRestaurant {
    const MESSAGE_TYPE: &'static str = "UpdateRestaurant";
}

impl RestaurantCommand for domain::generated::commands::UpdateRestaurantGoogleBusinessProfile {
    const MESSAGE_TYPE: &'static str = "UpdateRestaurantGoogleBusinessProfile";
}

impl RestaurantCommand for domain::generated::commands::VerifyGoogleBusinessProfileOrderLink {
    const MESSAGE_TYPE: &'static str = "VerifyGoogleBusinessProfileOrderLink";
}

/// GENERATED from actors.yaml `Restaurant.receives`: marker for every inbound FACT (an
/// `events.yaml#/...` ref -- an external fact that already happened) the `Restaurant` actor records.
/// SEALED for the same reason as [`RestaurantCommand`].
pub trait RestaurantFact: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the events.yaml key) -- also the `DomainEvent` adjacent tag.
    const EVENT_TYPE: &'static str;
    /// The fact wrapped in ITS `DomainEvent` variant -- so the adjacently-tagged wire form comes
    /// from the domain enum's own serde representation, never from a hand-built literal that
    /// could drift from it.
    fn into_domain_event(self) -> domain::generated::events::DomainEvent;
}

impl RestaurantFact for domain::generated::events::RestaurantRegistered {
    const EVENT_TYPE: &'static str = "RestaurantRegistered";
    fn into_domain_event(self) -> domain::generated::events::DomainEvent {
        domain::generated::events::DomainEvent::RestaurantRegistered(self)
    }
}

/// GENERATED from actors.yaml: the strongly-typed client for ONE `Restaurant` mailbox lane --
/// `actor_id` is the addressed instance and the partition is derived by `declared_lane` from the
/// DECLARED `mailbox.partitions` width. The only door to this actor.
///
/// This client does NOT carry the width (#596). It used to be emitted as a literal into every
/// send/schedule call, which made each generated client an independent copy of a routing constant
/// that only ever has one correct value -- and disagreeing copies of that constant are how one
/// aggregate ends up in two lanes, each with a live lease.
pub struct RestaurantClient {
    door: ActorDoor,
    actor_id: uuid::Uuid,
}

impl RestaurantClient {
    /// A client addressing the `Restaurant` instance `actor_id`.
    pub fn new(mailbox: Arc<dyn Mailbox>, actor_id: uuid::Uuid) -> Self {
        Self { door: ActorDoor::new(mailbox), actor_id }
    }

    /// Enqueue one typed COMMAND on this lane (kind COMMAND). Delegates to the door's
    /// `send_command`, which builds the row with the shared `command_entry` constructor -- the
    /// very row `enqueue_worker_command` builds for the same inputs, field for field.
    pub async fn send<M: RestaurantCommand>(
        &self,
        msg: M,
        env: Envelope,
    ) -> Result<EnqueueOutcome, DomainError> {
        let payload = serde_json::to_value(&msg)
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", M::MESSAGE_TYPE)))?;
        self.door.assert_addressed("RestaurantClient", self.actor_id, M::MESSAGE_TYPE, &payload)?;
        self.door
            .send_command("Restaurant", self.actor_id, M::MESSAGE_TYPE, payload, env)
            .await
    }

    /// Record one inbound FACT (kind EVENT, channel EXTERNAL, adjacently-tagged `DomainEvent`
    /// payload). `message_id` is ALWAYS the deterministic `inbound_message_id(source,
    /// external_id)` -- never caller-supplied -- and provenance is a REQUIRED parameter, because
    /// the `(source, external_id)` dedupe key is what makes redelivery safe. The acting principal
    /// is the per-source system user, stamped by the shared `inbound_entry` constructor.
    pub async fn record<F: RestaurantFact>(
        &self,
        fact: F,
        source: &str,
        external_id: &str,
        correlation_id: uuid::Uuid,
    ) -> Result<EnqueueOutcome, DomainError> {
        let tagged = serde_json::to_value(fact.into_domain_event())
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", F::EVENT_TYPE)))?;
        self.door
            .record_fact(
                "Restaurant",
                self.actor_id,
                F::EVENT_TYPE,
                tagged,
                source,
                external_id,
                correlation_id,
            )
            .await
    }
}
