// GENERATED by the Captain.Food codegen from specs/common/ — do not edit by hand
// (#373, ADR-20260807-183024 step 2).

//! Captain.Food `domain-common`: the `common` scope's generated domain types — the KERNEL: cross-scope contracts every scope may build on (and nothing else may leak into).
//! Types only — aggregates/handlers/folds stay in their layer crates; the `domain` facade
//! re-exports these modules so existing `domain::generated::*` paths keep the same type identity.

pub mod scalars;
pub mod entities;
pub mod events;
pub mod commands;
pub mod errors;
