#!/usr/bin/env python3
"""Table-driven battery for assert_review_marker.

Every case below is a REGRESSION: each was found by an independent review round
of PR #680 (issue #677), and several were live false reds or false greens on a
check that is required on `main`. The rounds each had to re-discover these by
hand because the matcher lived inside a YAML block scalar and could not be run;
that is why this file exists.

Run: python3 .github/scripts/assert_review_marker_test.py
"""
import os, sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from assert_review_marker import comment_names_commit, count_matches  # noqa: E402

# REAL shas, not repdigits. With H = "1"*40 the "uppercase hex" case was a literal no-op
# (("1"*12).upper() == "1"*12) and two mutants survived the whole battery: startswith -> endswith,
# and dropping .lower(). Measured by the seventh review; one line to fix, so it is fixed.
H = "3f9a2c7e1b8d40526af1c93e07b45d8e2a6f1c04"
M = "b71e4d9c02a83f5617ce4b90d283a1f6e5c70b94"
SHAS = [H, M]
BT = "`" * 3
TL = "~" * 3

# (name, body, expected, why-it-is-here)
CASES = [
    # --- live renderings a reviewer actually writes: must COUNT -------------
    # NO CORPUS COUNTS IN THESE LABELS. Six of them carried figures ("13 of 14 sha lines are code
    # spans", "11 of 14 are bold", ...) that review #10 measured against the corpus this PR sources
    # and could not reproduce -- prose-in-code doing exactly what the docstring twenty lines up
    # forbids in comments. The shapes are real and observed; the arithmetic was not checkable, so
    # it is gone rather than re-guessed.
    ("plain",                 f"reviewed\n\nReviewed-Commit: {H}", True, "baseline"),
    ("merge sha",             f"reviewed\n\nReviewed-Commit: {M}", True, "checkout takes the merge ref (round 1)"),
    ("abbreviated 7-hex",     f"reviewed\n\nReviewed-Commit: {H[:7]}", True, "round 1: real reviewers abbreviate; an exact-40 rule would have redded every review"),
    ("backticked",            f"reviewed\n\nReviewed-Commit: `{H}`", True, "a backticked sha is the commonest real shape"),
    ("uppercase hex",         f"reviewed\n\nReviewed-Commit: {H[:12].upper()}", True, "fail-closed would be a false red"),
    ("bold, colon inside",    f"reviewed\n\n**Reviewed-Commit:** {H}", True, "a real shape"),
    ("bold, colon OUTSIDE",   f"reviewed\n\n**Reviewed-Commit**: {H}", True, "round 6: this shape was a live FALSE RED"),
    ("italic",                f"reviewed\n\n_Reviewed-Commit:_ {H}", True, "seen in the corpus"),
    ("list item",             f"reviewed\n\n- Reviewed-Commit: {H}", True, "a real shape"),
    ("task list item",        f"reviewed\n\n- [x] Reviewed-Commit: {H}", False, "round 6 named it; task syntax is not stripped"),
    ("ordered list",          f"reviewed\n\n1. Reviewed-Commit: {H}", True, "natural shape"),
    ("heading",               f"reviewed\n\n## Reviewed-Commit: {H}", True, "natural shape"),
    ("blockquote",            f"reviewed\n\n> Reviewed-Commit: {H}", True, "renders live"),
    ("blockquote, no space",  f"reviewed\n\n>Reviewed-Commit: {H}", True, "round 6: legal CommonMark, was a false red"),
    ("nested blockquote",     f"reviewed\n\n>> Reviewed-Commit: {H}", True, "round 6: was a false red"),
    ("trailing text",         f"reviewed\n\nReviewed-Commit: {H} (head)", True, "round 5: end-anchor removed"),
    ("trailing period",       f"reviewed\n\nReviewed-Commit: {H}.", True, "a real shape; the end-anchor rule redded it"),
    ("trailing tab",          f"reviewed\n\nReviewed-Commit: {H}\t", True, "accepted; whitespace after the sha is not trailing text"),
    ("marker + footer after", f"reviewed\n\nReviewed-Commit: {H}\n\n---\n_Generated by Claude Code_", True,
                              "round 3: a 'must be LAST line' rule would red every footered review"),
    ("2-space indent",        f"reviewed\n\n  Reviewed-Commit: {H}", True, "under 4 spaces is not code"),

    # --- renders as CODE, or is not a marker: must NOT count ----------------
    ("fenced backtick",       f"q:\n{BT}\nReviewed-Commit: {H}\n{BT}\nno", False, "round 3: the anti-quoting property"),
    ("fenced tilde",          f"q:\n{TL}\nReviewed-Commit: {H}\n{TL}\nno", False, "round 3"),
    ("fence with info string",f"q:\n{BT}yaml\nReviewed-Commit: {H}\n{BT}\nno", False, "round 4"),
    ("nested 4-backtick",     f"q:\n{BT}`\n{BT}\nReviewed-Commit: {H}\n{BT}\n{BT}`\nno", False,
                              "round 4: the idiomatic way to quote a fenced block"),
    ("backtick closer + text",f"q:\n{BT}\nReviewed-Commit: {H}\n{BT} x\nstill code\n{BT}\nno", False,
                              "round 5: a closer may carry only whitespace"),
    ("TILDE closer + text",   f"q:\n{TL}\n{TL} x\nReviewed-Commit: {H}\n{TL}\nno", False,
                              "round 6: the rule was applied to backticks only"),
    ("unclosed fence",        f"q:\n{BT}\nstuff\n\nReviewed-Commit: {H}", False, "everything after an opener is code"),
    ("stale sha",             f"reviewed\n\nReviewed-Commit: 9999999999999999999999999999999999999999", False,
                              "round 1: comments survive pushes"),
    ("6-hex too short",       f"reviewed\n\nReviewed-Commit: {H[:6]}", False, "not specific enough"),
    ("sha prefix inside a longer token", f"reviewed\n\nReviewed-Commit: {H}beef", False,
                              "round 5: \\b must not match mid-token"),
    ("text before marker",    f"Review done. Reviewed-Commit: {H}", False, "round 6: named boundary"),
    ("no marker",             "reviewed, no findings", False, "baseline"),

    # --- eighth review: the FALSE REDS the old block parser produced ---------
    # Each is a complete, correct review that the round-7 parser rejected -- i.e. the gate calling
    # a real review "no review". That is why the design now fails open; see live_lines and
    # docs/decisions/REVIEW-MARKER-BIAS.yaml for the direction and its open row.
    ("fence in a list item that ENDS, marker after",
     f"Findings:\n\n- Log:\n\n  {BT}\n  boom\n\nReviewed-Commit: {H}", True,
     "round 8 FALSE RED: the old parser held the fence open to end of comment"),
    ("fence in a blockquote that ENDS, marker after",
     f"q:\n> {BT}\n> panic\n\nReviewed-Commit: {H}", True, "round 8 FALSE RED: container lifetime"),
    ("blockquote closer without a space",
     f"q:\n> {BT}\n> code\n>{BT}\n\nReviewed-Commit: {H}", True,
     "round 8 FALSE RED: prefix EQUALITY, but `>` and `> ` are the same block structure"),
    ("blockquote + tab before the marker",
     f"reviewed\n\n> \tReviewed-Commit: {H}", True,
     "round 8 FALSE RED: tab columns counted after the container prefix was discarded"),

    # --- seventh review: properties the battery could not see red ------------
    ("fence QUOTING a fence, inner blockquoted",
     f"prev reviewer wrote:\n{BT}\n> {BT}\nReviewed-Commit: {H}\n> {BT}\n{BT}\nno", False,
     "round 7 FALSE GREEN: a container prefix inside an open fence closed it, so quoted code escaped"),
    ("fence quoting a fence, inner list-marked",
     f"q:\n{BT}\n- {BT}\nReviewed-Commit: {H}\n- {BT}\n{BT}\nno", False, "round 7, same mechanism"),
    ("tilde fence quoting a fence",
     f"q:\n{TL}\n> {TL}\nReviewed-Commit: {H}\n> {TL}\n{TL}\nno", False, "round 7, tilde variant"),
    ("tab-indented code",     f"q:\n\n\tReviewed-Commit: {H}\nno", True,
                              "round 8: ACCEPTED false green -- indentation is not a code signal any more"),
    ("space+tab indented code", f"q:\n\n \tReviewed-Commit: {H}\nno", True, "round 8: ACCEPTED false green, same reason"),
    ("fence opener indented 4+ is not a fence",
     f"q:\n\n    {BT}\n\nReviewed-Commit: {H}", True,
     "round 8: only a COLUMN-0 delimiter is a fence, so this is live for a simpler reason"),
    ("closer of a DIFFERENT char does not close",
     f"q:\n{BT}\n{TL}\nReviewed-Commit: {H}\n{BT}\nno", False,
     "round 7: dropping char == open_char survived the battery"),
    ("longer closer still closes",
     f"q:\n{BT}\nx\n{BT}`\n\nReviewed-Commit: {H}", True,
     "round 7: run >= open_run, not ==; the == mutant survived"),
    ("CRLF body",             f"reviewed\r\n\r\nReviewed-Commit: {H}\r", True,
     "round 7. HONEST LABEL (review #9): this does NOT kill the `rstrip(chr(13))` mutant, and no "
     "case can -- CR safety actually comes from `\\b` after the hex in MARKER and from `.strip()` "
     "on a closer's rest, both of which absorb it. The strip is belt-and-braces. The earlier label "
     "claimed coverage this case does not provide, which is the round-7 repdigit defect one field over."),
    ("col-0 backtick line with a code span is NOT a fence",
     f"{BT}make validate{BT} is green.\n\nReviewed-Commit: {H}", True,
     "review #10 LIVE FALSE RED: a backtick fence's info string may not contain a backtick "
     "(CommonMark 4.5), so this is a paragraph -- but the matcher opened a phantom fence that ran "
     "to end of comment and swallowed the marker. Reviewers start lines this way constantly."),
    ("col-0 backtick opener with a stray backtick in the info string",
     f"{BT}a`b\n\nReviewed-Commit: {H}", True, "review #10: same rule, unbalanced form"),
    ("TILDE info string may contain a tilde, so this DOES open a fence",
     f"~~~x~~~\nReviewed-Commit: {H}\n~~~\nno", False,
     "review #10: the info-string restriction is backtick-only; do not over-apply the fix"),
    ("one-backtick line is NOT a fence",
     f"`live_lines` is wrong.\n\nReviewed-Commit: {H}", True,
     "review #9: relaxing the delimiter to `{1,}` made every comment opening with an inline code "
     "span at column 0 start a phantom fence and swallow the marker. HONEST LABEL (review #11): "
     "this case no longer kills that mutant -- round 11's backtick-info-string guard rescues it, "
     "because the tail carries a backtick. The case still documents a real live shape; the KILL "
     "moved to the two cases below, which carry no backtick in the tail."),
    ("col-0 opener, closer indented 1-3 spaces",
     f"q:\n{BT}\nquoted\n   {BT}\nReviewed-Commit: {H}", False,
     "ACCEPTED FALSE RED, direction 1: CommonMark closes this fence, the matcher does not see the "
     "indented closer, so the fence runs to end of comment. Pinned as a FIXTURE so the residual is "
     "not just a sentence -- review #11. Remedy for an operator: close fences at column 0."),
    ("opener indented 1-3 spaces, closer at col 0",
     f"q:\n  {BT}\nquoted\n{BT}\nReviewed-Commit: {H}", False,
     "ACCEPTED FALSE RED, direction 2 -- the MIRROR, and the one actually sitting in the committed "
     "differential baseline (seed 2) while the docstring documented only direction 1 and claimed the "
     "baseline tracked it. An indented opener is legal CommonMark; the matcher reads its column-0 "
     "closer as a fresh OPENER. Review #11."),
    ("unbalanced col-0 backtick, no backtick in the tail",
     f"`unclosed span at column zero\n\nReviewed-Commit: {H}", True,
     "review #11 RESTORED KILL: with `{1,}` this opens a phantom fence the info-string guard does "
     "NOT rescue (no backtick in the rest), so the marker is swallowed -- a live false red. This is "
     "the case that actually pins the `{3,}` delimiter length."),
    ("two-backtick line, no backtick in the tail",
     f"``almost a span\n\nReviewed-Commit: {H}", True,
     "review #11: same kill at run length 2, so `{2,}` is pinned too."),
    ("two-tilde line is NOT a fence",
     f"~~struck~~ text\n\nReviewed-Commit: {H}", True,
     "review #9: same mutant, tilde side. GFM strikethrough at column 0 is not a fence opener."),
    ("CRLF inside a fence",   f"q:\r\n{BT}\r\nReviewed-Commit: {H}\r\n{BT}\r\nno", False, "round 7"),
    ("uppercase hex, real sha", f"reviewed\n\nReviewed-Commit: {H[:12].upper()}", True,
                              "round 7: a no-op under repdigit fixtures"),
    ("sha SUFFIX must not match", f"reviewed\n\nReviewed-Commit: {H[-12:]}", False,
                              "round 7: the startswith -> endswith mutant survived"),
    ("UPPERCASE sha ARGUMENT still matches a lowercase marker",
     f"reviewed\n\nReviewed-Commit: {H[:12]}", True,
     "review #10 SURVIVING MUTANT: `s.lower().startswith(h)` -> `s.startswith(h)` passed the whole "
     "battery. The comment side was covered, the ARGUMENT side was not. Driven through "
     "`comment_names_commit(body, [H.upper()])` in main(), below.",
     "upper-arg"),

    # --- renders as CODE and COUNTS ANYWAY: the ACCEPTED false greens -------
    # These seven assert True while rendering as code. They are NOT mislabelled: round 8 chose the
    # fail-open direction deliberately (see live_lines), and each was verified against markdown-it
    # to genuinely render as code. They sat under the "must NOT count" header until review #9 --
    # a section header that lies about its rows is how round 6 happened.
    ("4-space indented",      f"q:\n\n    Reviewed-Commit: {H}\nno", True,
     "round 8: ACCEPTED false green. The indent rule was the LAST false-red source; restoring it "
     "costs dozens of false reds (lazy paragraph continuation), measured by the differential harness."),
    ("blockquoted fence",     f"q:\n> {BT}\n> Reviewed-Commit: {H}\n> {BT}\nno", True,
     "round 8: ACCEPTED false green -- a fence or indent inside a CONTAINER is not tracked. Chasing this cost rounds 6-8 and produced live FALSE REDS; the gate cannot prove which bot posted anyway."),
    ("blockquoted tilde fence",f"q:\n> {TL}\n> Reviewed-Commit: {H}\n> {TL}\nno", True, "round 8: ACCEPTED, same"),
    ("blockquote + indented", f"q:\n\n>     Reviewed-Commit: {H}\nno", True,
     "round 8: ACCEPTED, same"),
    ("list item + indented",  f"q:\n\n-     Reviewed-Commit: {H}\nno", True, "round 8: ACCEPTED, same"),
]


def main() -> int:
    failed = 0
    for case in CASES:
        name, body, want, why = case[0], case[1], case[2], case[3]
        # A 5th element names a non-default sha ARGUMENT to drive the case with. Without it the
        # argument side of every comparison is fixed at the canonical lowercase sha.
        shas = [H.upper()] if len(case) > 4 and case[4] == "upper-arg" else SHAS
        got = comment_names_commit(body, shas)
        if got != want:
            print(f"FAIL  {name}: expected {want}, got {got}   [{why}]")
            failed += 1
    # ARGUMENT ARITY, driven through the real entry point. Review #11 ran four mutants against
    # round 10's argv fix -- `> 2` -> `> 3`, `> 2` -> `if False`, dropping "extra" from the zip,
    # and `shas = args[:2]` -- and ALL FOUR survived the battery. The fix shipped with no coverage
    # at all, in the file the workflow calls "the exact contract". These cases are why it now has
    # some: a third sha must be refused outright, and the third zip slot must be live.
    import subprocess
    here = os.path.dirname(os.path.abspath(__file__))
    def run_argv(args):
        return subprocess.run(
            [sys.executable, os.path.join(here, "assert_review_marker.py"), *args],
            input="[]", capture_output=True, text=True,
        )
    third = "c" * 40
    for label, args, want_rc in [
        ("three shas are refused outright", [H, M, third], 2),
        ("a malformed THIRD sha is caught by the validation loop", [H, M, "nothex"], 2),
        ("two good shas still validate", [H, M], 0),  # rc 0 + a printed count; the workflow asserts on it
    ]:
        got = run_argv(args)
        if got.returncode != want_rc:
            print(f"FAIL  argv: {label}: expected rc {want_rc}, got {got.returncode}   "
                  f"[stderr: {got.stderr.strip()[:120]}]")
            failed += 1

    # Author filtering and counting, end to end.
    human = [{"user": {"type": "User"}, "body": f"Reviewed-Commit: {H}"}]
    if count_matches(human, SHAS) != 0:
        print("FAIL  a human comment must not satisfy the gate"); failed += 1
    bots = [{"user": {"type": "Bot"}, "body": f"Reviewed-Commit: {H}"},
            {"user": {"type": "Bot"}, "body": "no marker"}]
    if count_matches(bots, SHAS) != 1:
        print("FAIL  bot counting"); failed += 1
    if count_matches([], SHAS) != 0:
        print("FAIL  empty comment list"); failed += 1

    # Argument validation is part of the contract: an empty or malformed sha must RED, never
    # silently narrow what the gate matches against. An earlier version of main() filtered empties
    # out of argv, so an empty head sha degraded to merge-only matching and returned 0.
    import subprocess, pathlib
    script = str(pathlib.Path(__file__).parent / "assert_review_marker.py")
    for label, argv in [("empty head sha", ["", H]),
                        ("short head sha", [H[:7], H]),
                        ("non-hex head sha", ["z" * 40, H]),
                        ("empty merge sha", [H, ""])]:
        r = subprocess.run([sys.executable, script] + argv, input="[]",
                           capture_output=True, text=True)
        if r.returncode == 0:
            print(f"FAIL  {label} must be rejected, got rc=0 stdout={r.stdout!r}")
            failed += 1
    # `gh api --paginate` may merge pages into one array or emit one array per page. Both must
    # parse; the second shape raises "Extra data" under a plain json.load, which would be a false
    # red on every PR with more than 30 comments.
    from assert_review_marker import parse_comment_stream
    one = f'[{{"user":{{"type":"Bot"}},"body":"Reviewed-Commit: {H}"}}]'
    two = f'[{{"user":{{"type":"Bot"}},"body":"a"}}]'
    for label, raw, n in [("single array", one, 1),
                          ("two arrays back to back", one + "\n" + two, 2),
                          ("three arrays", one + two + one, 3),
                          ("empty stream", "", 0),
                          ("whitespace only", "   \n ", 0)]:
        try:
            got = len(parse_comment_stream(raw))
        except Exception as exc:
            print(f"FAIL  pagination shape {label!r} raised {exc}"); failed += 1; continue
        if got != n:
            print(f"FAIL  pagination shape {label!r}: expected {n} comments, got {got}"); failed += 1
    for label, raw in [("a JSON object", '{"a":1}'), ("truncated", '[{"user":')]:
        try:
            parse_comment_stream(raw)
            print(f"FAIL  {label} must raise, not parse"); failed += 1
        except Exception:
            pass
    total = len(CASES) + 3 + 4 + 7
    print(f"RESULT: {total - failed} passed, {failed} failed  ({len(CASES)} body + 3 counting + 7 argument + 7 pagination cases)")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
