// GENERATED by the Captain.Food codegen from specs/actors.yaml (`receives` +
// `mailbox.partitions` + `reminders`) -- do not edit by hand (PROP-20260802-130500 phase 2,
// #306). The typed mailbox client for ONE actor, in its OWN crate: depending on this crate is the
// permission to address `Rider`, and nothing else.
//
// The client constructs NOTHING itself. Every row is assembled behind `actor_client::ActorDoor`,
// whose delegates own the lane, partition, principal and channel derivation -- so a typed send
// here and the string-keyed reference implementation in `actor_client` cannot drift (the
// out-of-crate drift guard in `crates/actor_client/tests/drift_guard.rs` proves it field for
// field). `MailboxEntry` and `MailboxAccess` are not nameable from this crate at all.
//
// EVERY method is spec-gated (product-owner directive, 2026-08-02 -- the declaration is the
// permission): `send` + `RiderCommand` exist iff the actor receives >=1 COMMAND, `record` +
// `RiderFact` iff it receives >=1 inbound FACT, `schedule`/`cancel_scheduling` iff it declares
// `reminders:`. An unjustified surface is ABSENT -- a compile error at any call site -- never
// uncallable-but-present.

use std::sync::Arc;

use actor_client::mailbox::{Envelope, Mailbox};
use actor_client::{ActorDoor, EnqueueOutcome};
use domain::shared::errors::DomainError;

/// The privacy SEAL: `Sealed` lives in a private module, so it cannot be named -- let alone
/// implemented -- outside this GENERATED crate. Every marker trait below requires it, so the
/// receive set this actor declares in actors.yaml is the receive set, period: widening it takes a
/// spec change and a regeneration, never a stray downstream `impl`. Since phase 2 each actor owns
/// its own seal, so a sibling client crate cannot even name this actor's marker supertrait.
mod sealed {
    pub trait Sealed {}
}

impl sealed::Sealed for domain::generated::commands::ChangeRiderStatus {}
impl sealed::Sealed for domain::generated::commands::RegisterRider {}
impl sealed::Sealed for domain::generated::commands::UpdateRiderInfo {}

/// GENERATED from actors.yaml `Rider.receives`: marker for every COMMAND the `Rider` actor
/// receives. SEALED (private supertrait) so no impl can exist outside this generated crate --
/// sending a command this actor does not `receive` is a COMPILE error, not a runtime rejection.
pub trait RiderCommand: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the commands.yaml key).
    const MESSAGE_TYPE: &'static str;
}

impl RiderCommand for domain::generated::commands::ChangeRiderStatus {
    const MESSAGE_TYPE: &'static str = "ChangeRiderStatus";
}

impl RiderCommand for domain::generated::commands::RegisterRider {
    const MESSAGE_TYPE: &'static str = "RegisterRider";
}

impl RiderCommand for domain::generated::commands::UpdateRiderInfo {
    const MESSAGE_TYPE: &'static str = "UpdateRiderInfo";
}

/// GENERATED from actors.yaml: the strongly-typed client for ONE `Rider` mailbox lane --
/// `actor_id` is the addressed instance and the partition is derived by `declared_lane` from the
/// DECLARED `mailbox.partitions` width. The only door to this actor.
///
/// This client does NOT carry the width (#596). It used to be emitted as a literal into every
/// send/schedule call, which made each generated client an independent copy of a routing constant
/// that only ever has one correct value -- and disagreeing copies of that constant are how one
/// aggregate ends up in two lanes, each with a live lease.
pub struct RiderClient {
    door: ActorDoor,
    actor_id: uuid::Uuid,
}

impl RiderClient {
    /// A client addressing the `Rider` instance `actor_id`.
    pub fn new(mailbox: Arc<dyn Mailbox>, actor_id: uuid::Uuid) -> Self {
        Self { door: ActorDoor::new(mailbox), actor_id }
    }

    /// Enqueue one typed COMMAND on this lane (kind COMMAND). Delegates to the door's
    /// `send_command`, which builds the row with the shared `command_entry` constructor -- the
    /// very row `enqueue_worker_command` builds for the same inputs, field for field.
    pub async fn send<M: RiderCommand>(
        &self,
        msg: M,
        env: Envelope,
    ) -> Result<EnqueueOutcome, DomainError> {
        let payload = serde_json::to_value(&msg)
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", M::MESSAGE_TYPE)))?;
        self.door.assert_addressed("RiderClient", self.actor_id, M::MESSAGE_TYPE, &payload)?;
        self.door
            .send_command("Rider", self.actor_id, M::MESSAGE_TYPE, payload, env)
            .await
    }
}
