// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260808-062933 one bin per worker, #393).

//! `worker-journal-sweep` — scheduled command_journal stale-RECEIVED sweep -- flips dead spawned runs to FAILED so operationStatus never lies (one bin per worker, ADR-20260808-062933).
//!
//! CRON WORKER: a RUN-TO-COMPLETION pass over the existing implementation crates. The generated
//! CronJob (deploy/generated/manifests/bins/worker-journal-sweep.yaml, declared cadence `*/5 * * * *` UTC from
//! c4-l2) is the scheduler — the platform's scheduler is the scheduler, so this main runs ONE
//! pass and exits: 0 on a clean pass, 1 on a failed pass (the Job goes red), 78 on broken
//! configuration (EX_CONFIG).
//!
//! GATE-THEN-STABILIZE: nothing applies the manifests yet; the monolith's in-process loops
//! remain the running instance of this pass until the #358 cutover points the schedule here.

/// The bin's scope-filtered typed configuration (#374 Q4): the declared keys of its linked
/// scopes + `common` (+ its hosted consumers' keys, #393), read once at startup.
mod config;

/// The c4-l2 container this binary realizes.
const BIN: &str = "worker-journal-sweep";
/// The bin's family in the deploy topology.
const FAMILY: &str = "worker";

#[tokio::main]
async fn main() {
    // Identity FIRST, before any fallible startup (ADR-20260721-175411): a boot that never runs
    // its pass still names its version in the logs.
    println!("{BIN} ({FAMILY}) starting -- version {}, cron worker pass (#393)", bin_runtime::build_version());

    // Configuration gate (PROP-20260729-004500): every problem reported at once; production and
    // staging refuse to start on a broken configuration, development reports and continues.
    let (config, problems) = config::Config::resolve();

    // Telemetry SECOND -- after config (it needs LOG_LEVEL and the ingest key), before the pass,
    // so its lines are structured and correlated (issue #191).
    let mut telemetry_guard = bin_runtime::init_telemetry(bin_runtime::TelemetrySettings {
        api_key: config.honeycomb_api_key.clone(),
        endpoint: config.honeycomb_api_endpoint.clone(),
        dataset: config.honeycomb_dataset.clone(),
        sample_ratio: config.otel_traces_sample_ratio.clone(),
        log_level: config.log_level.clone(),
        profile: config.profile.to_string(),
    });
    if !problems.is_empty() {
        let report = config::MissingConfig { profile: config.profile, problems };
        tracing::error!(profile = %config.profile, "{report}");
        if config.must_stop_on_problems() {
            // Flush before exiting, or the error explaining the failed Job never leaves the pod.
            telemetry_guard.shutdown();
            // 78 = EX_CONFIG (sysexits.h): a configuration error, not a crash.
            std::process::exit(78);
        }
        tracing::warn!(profile = %config.profile, "starting anyway -- production and staging STOP here");
    }
    tracing::info!("{}", config.boot_report());

    let ok = run_pass(&config).await;
    // Flush BEFORE the exit code: a failed pass whose telemetry never left the pod is invisible.
    telemetry_guard.shutdown();
    if !ok {
        std::process::exit(1);
    }
}

/// One pass. `false` = the Job fails visibly (the next scheduled run is the retry — every pass
/// here is idempotent/checkpointed by its implementation crate).
async fn run_pass(config: &config::Config) -> bool {
    if config.database_url.is_empty() {
        // Only reachable in development (the config gate stops prod/staging): nothing to run.
        tracing::error!(bin = BIN, "DATABASE_URL unset -- the pass has nothing to run against");
        return false;
    }
    let pool = match bin_runtime::pg_pool(&config.database_url, config.database_pool_max_connections) {
        Ok(pool) => pool,
        Err(e) => {
            tracing::error!(bin = BIN, error = %e, "pg pool init failed");
            return false;
        }
    };
    // ONE shared pass (infrastructure::integrations::journal_sweep) -- the monolith loops the
    // SAME function; the stale window and the cadence live there, never here.
    match infrastructure::integrations::journal_sweep::sweep_stale_received_once(&pool).await {
        Ok(0) => {
            tracing::info!(worker = "journal_sweep", swept = 0u64, "no stale RECEIVED commands");
            true
        }
        Ok(n) => {
            tracing::warn!(worker = "journal_sweep", swept = n, "stale RECEIVED commands flipped to FAILED");
            true
        }
        Err(e) => {
            tracing::error!(worker = "journal_sweep", error = %e, "stale-command sweep failed");
            false
        }
    }
}
