// GENERATED by the Captain.Food codegen from specs/delivery/commands.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use domain_common::scalars::*;

/// An independent Captain rider accepts a pending delivery job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AcceptDelivery {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: RiderId,
}

/// The assigned rider confirms they collected the order from the restaurant.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmPickup {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: RiderId,
}

/// Restaurant/admin cancels a delivery job before it completes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelDelivery {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// Restaurant/admin asks to skip the delivery channel currently offered and advance the ranked walk now (#60). The DeliveryJob emits DeliveryEscalationRequested; DeliveryDispatchProcess offers the next ranked channel, or fails the dispatch closed when the walk is exhausted. Self-dispatch and exhaustion are handled by the saga (a benign skip / a terminal fact), not rejected as command errors.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EscalateDelivery {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// The assigned rider marks the delivery complete (handed to the customer).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CompleteDelivery {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: RiderId,
}

/// An independent rider declines a pending delivery job (it stays PENDING, re-offerable).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeclineDelivery {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: RiderId,
    pub reason: Option<String>,
}

/// Report an issue on a delivery job (rider/partner/support).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReportDeliveryIssue {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: Option<RiderId>,
    pub issue: String,
}

/// Resolve a previously reported delivery issue.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResolveDeliveryIssue {
    pub delivery_job_id: DeliveryJobId,
    pub resolution: String,
}

/// Drive a delivery job's status (independent-rider path / admin correction).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateDeliveryStatus {
    pub delivery_job_id: DeliveryJobId,
    pub status: DeliveryStatus,
}

/// Unassign a delivery job from its partner (to re-offer it).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnassignDeliveryFromPartner {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// A delivery partner self-registers its availability to serve a city on a catalog channel (#61). Birth of a DeliveryPartnerRegistration; lands PENDING until an admin approves. registrationId is client-generated (idempotent).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterDeliveryPartnerAvailability {
    pub registration_id: DeliveryPartnerRegistrationId,
    pub channel: DeliveryChannelKey,
    pub city_id: CityId,
    pub partner_name: DeliveryPartnerName,
    pub contact_email: EmailAddress,
}

/// An admin approves a PENDING delivery-partner availability registration (#61); it becomes eligible for the city's dispatch ranking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApproveDeliveryPartnerAvailability {
    pub registration_id: DeliveryPartnerRegistrationId,
}

/// Revoke a delivery-partner availability registration (#61) — the partner withdraws or an admin disables it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RevokeDeliveryPartnerAvailability {
    pub registration_id: DeliveryPartnerRegistrationId,
    pub reason: Option<String>,
}

/// Register as an independent Captain rider (linked to the auth provider user).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterRider {
    pub rider_id: RiderId,
    pub auth_ref: AuthSubject,
    pub display_name: String,
    pub phone: PhoneNumber,
}

/// Update editable rider profile fields.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateRiderInfo {
    pub rider_id: RiderId,
    pub display_name: Option<String>,
    pub phone: Option<PhoneNumber>,
}

/// Change a rider's availability/lifecycle status.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChangeRiderStatus {
    pub rider_id: RiderId,
    pub status: RiderStatus,
}
