// GENERATED by the Captain.Food codegen from specs/delivery/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// No delivery job with this id.
/// Context: `deliveryJobId`.
pub const DELIVERY_JOB_NOT_FOUND: ErrorDef = ErrorDef {
    code: "DeliveryJobNotFound",
    message_en: "Delivery job not found.",
    message_fr: "Livraison introuvable.",
};

/// The delivery job is not in a status that allows this transition.
/// Context: `deliveryJobId`, `currentStatus`, `expectedStatus`.
pub const INVALID_DELIVERY_STATUS: ErrorDef = ErrorDef {
    code: "InvalidDeliveryStatus",
    message_en: "This action is not allowed while the delivery is '{currentStatus}'.",
    message_fr: "Cette action n'est pas autorisée tant que la livraison est '{currentStatus}'.",
};

/// The delivery job has already been accepted by a courier/rider.
/// Context: `deliveryJobId`.
pub const DELIVERY_ALREADY_ASSIGNED: ErrorDef = ErrorDef {
    code: "DeliveryAlreadyAssigned",
    message_en: "This delivery has already been taken.",
    message_fr: "Cette livraison a déjà été prise en charge.",
};

/// A registration with this id already exists (idempotent self-registration guard).
/// Context: `registrationId`.
pub const DELIVERY_PARTNER_AVAILABILITY_ALREADY_REQUESTED: ErrorDef = ErrorDef {
    code: "DeliveryPartnerAvailabilityAlreadyRequested",
    message_en: "This availability registration already exists.",
    message_fr: "Cette demande de disponibilité existe déjà.",
};

/// No delivery-partner availability registration with this id.
/// Context: `registrationId`.
pub const DELIVERY_PARTNER_AVAILABILITY_NOT_FOUND: ErrorDef = ErrorDef {
    code: "DeliveryPartnerAvailabilityNotFound",
    message_en: "Availability registration not found.",
    message_fr: "Demande de disponibilité introuvable.",
};

/// The availability registration is not PENDING, so it cannot be approved.
/// Context: `registrationId`, `currentStatus`.
pub const DELIVERY_PARTNER_AVAILABILITY_NOT_PENDING: ErrorDef = ErrorDef {
    code: "DeliveryPartnerAvailabilityNotPending",
    message_en: "This availability registration is not awaiting review.",
    message_fr: "Cette demande de disponibilité n'est pas en attente de validation.",
};

/// A rider is already registered for this identity (authRef/id).
/// Context: `riderId`.
pub const RIDER_ALREADY_REGISTERED: ErrorDef = ErrorDef {
    code: "RiderAlreadyRegistered",
    message_en: "You are already registered as a rider.",
    message_fr: "Vous êtes déjà inscrit en tant que livreur.",
};

/// The login credential (`authRef`) is already bound to ANOTHER rider id: the write-side reservation `(RIDER, authRef)` in `database/tables/reservations.yaml#/auth_subject_reservations` lost its insert to a row held by a different principal (#639 part C, #794). Named for THIS population and distinct from `RiderAlreadyRegistered` (same rider id twice) and from `RefAlreadyUsed` (a HubRise import key): the human already has a rider account, and the remedy is to sign in to it, never to register a second one -- the binding is never released.
/// Context: `authRef`.
pub const RIDER_AUTH_SUBJECT_ALREADY_BOUND: ErrorDef = ErrorDef {
    code: "RiderAuthSubjectAlreadyBound",
    message_en: "This login is already linked to a rider account. Sign in to that account instead.",
    message_fr: "Cette identité de connexion est déjà liée à un compte livreur. Connectez-vous à ce compte.",
};

/// No rider with this id.
/// Context: `riderId`.
pub const RIDER_NOT_FOUND: ErrorDef = ErrorDef {
    code: "RiderNotFound",
    message_en: "Rider not found.",
    message_fr: "Livreur introuvable.",
};

/// The rider is not in a status that allows this transition.
/// Context: `riderId`, `currentStatus`, `targetStatus`.
pub const INVALID_RIDER_STATUS_TRANSITION: ErrorDef = ErrorDef {
    code: "InvalidRiderStatusTransition",
    message_en: "A rider cannot move from '{currentStatus}' to '{targetStatus}'.",
    message_fr: "Un livreur ne peut pas passer de '{currentStatus}' à '{targetStatus}'.",
};

/// A phone was verified but no rider account is bound to the login it proves (#639 part C step 2c-i): rider sign-in is IDENTIFY-ONLY and registers nobody, so the sign-in is refused and nothing is created. Named for the RIDER population; the remedy is the support route (`SUPPORT_CONTACT`, ADR-20260830-213135 -- a required key with no default), never self-registration. Only the phone's owner can see it (the OTP was verified first), so it is not an enumeration oracle.
/// Context: `supportContact`.
pub const RIDER_NOT_REGISTERED: ErrorDef = ErrorDef {
    code: "RiderNotRegistered",
    message_en: "This phone number is not linked to a rider account. Contact {supportContact} to get set up.",
    message_fr: "Ce numéro de téléphone n'est lié à aucun compte livreur. Contactez {supportContact} pour être enregistré.",
};

/// The verified login already carries a claim for ANOTHER role (a customer's `customer_id`, a restaurant's `restaurant_id`, ...), and the provider replaces the `captain_food` claim object wholesale -- stamping RIDER would erase it. Until the `one-subject-one-role` Concern of PROP-20260831-180622 is decided, the sign-in is REFUSED rather than overwriting (fail closed).
/// Context: `authRef`.
pub const AUTH_SUBJECT_HOLDS_ANOTHER_ROLE: ErrorDef = ErrorDef {
    code: "AuthSubjectHoldsAnotherRole",
    message_en: "This login is already used for another kind of Captain.Food account and cannot sign in as a rider yet.",
    message_fr: "Cette identité de connexion est déjà utilisée pour un autre type de compte Captain.Food et ne peut pas encore se connecter comme livreur.",
};
