// GENERATED by the Captain.Food codegen from specs/delivery/events.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use domain_common::entities::*;
use domain_common::scalars::*;

/// A delivery job has been created for a ready DELIVERY order and offered for fulfilment (dispatched to a partner and/or made available to independent riders). Emitted by DeliveryDispatchProcess.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryRequested {
    pub mode: Option<Mode>,
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub pickup: Address,
    pub dropoff: Address,
    pub provider: Option<DeliveryProvider>,
}

/// An independent Captain rider accepted the delivery job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryAcceptedByRider {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub rider_id: RiderId,
}

/// The rider collected the order from the restaurant.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryPickedUp {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub rider_id: RiderId,
    pub at: Option<String>,
}

/// The rider handed the order over to the customer (independent-rider delivery success).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryCompleted {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub at: Option<String>,
}

/// A delivery job was cancelled before delivery (e.g. by the restaurant or admin).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryCancelled {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// Dispatch failed terminally: the delivery partner declined the job at every offer attempt (cap of 3 total offers, ADR-20260720-004556). Emitted by DeliveryDispatchProcess (like DeliveryRequested) so read models surface the failed job to the restaurant for manual handling; no automatic retry follows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryDispatchFailed {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub attempts: i64,
    pub last_reason: Option<String>,
}

/// An operator (restaurant/admin) asked to skip the delivery channel currently offered and advance the ranked walk now (#60). Emitted by the DeliveryJob aggregate handling the EscalateDelivery command; consumed by DeliveryDispatchProcess, which offers the next ranked channel (or fails closed when the walk is exhausted). Internal dispatch mechanics — feeds no View_*.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryEscalationRequested {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// An outstanding delivery offer expired before the channel answered (#60): the DeliveryOfferTimeoutWorker found an OFFERED run older than the resolved TTL and records this fact (authored like DeliveryDispatchFailed). Recorded by the DeliveryJob aggregate and consumed by DeliveryDispatchProcess, which advances the ranked walk to the next channel (or fails closed when exhausted). Internal dispatch mechanics — feeds no View_*.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryOfferTimedOut {
    pub delivery_job_id: DeliveryJobId,
    pub channel: DeliveryChannelKey,
    pub rank: i64,
    pub reason: Option<String>,
}

/// The delivery partner (e.g. Avelo37) accepted the job and assigned one of its couriers (inbound).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryAcceptedByPartner {
    pub delivery_job_id: DeliveryJobId,
    pub partner_ref: ExternalReference,
    pub courier: Courier,
    pub estimated_pickup_at: Option<String>,
    pub estimated_dropoff_at: Option<String>,
}

/// The delivery partner declined the job (inbound); the dispatcher must re-offer or fall back to manual.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryRejectedByPartner {
    pub delivery_job_id: DeliveryJobId,
    pub partner_ref: Option<ExternalReference>,
    pub reason: Option<String>,
}

/// The delivery partner reported a status change for the job (inbound): PICKED_UP, OUT_FOR_DELIVERY, DELIVERED, FAILED…
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryStatusUpdated {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: Option<OrderId>,
    pub partner_ref: Option<ExternalReference>,
    pub status: DeliveryStatus,
    pub occurred_at: Option<String>,
    pub note: Option<String>,
}

/// A delivery job was unassigned from its partner (e.g. to re-offer it elsewhere).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryUnassignedFromPartner {
    pub delivery_job_id: DeliveryJobId,
    pub reason: Option<String>,
}

/// An independent rider declined a pending delivery job (stays PENDING, re-offerable).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryDeclinedByRider {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: RiderId,
    pub reason: Option<String>,
}

/// A rider holding a delivery job handed it back, stating where the food physically is (#639 part C step 3-ii, ADR-20260904-015903 §1-2). Business payload only — the actor is envelope metadata (`domain_events.user_id`). From ASSIGNED the job returns to PENDING (foodLocation NOT_COLLECTED, derived — the rider never picked up); from PICKED_UP/OUT_FOR_DELIVERY, RETURNED_TO_RESTAURANT re-offers the job (PENDING) and WITH_RIDER fails it closed (FAILED — a PENDING job whose food is in a restricted rider's bag would be re-offered, which is an oversell). `orderId` rides the fact (D-QW1 option b, ADR-20260808-234907, folded from the aggregate's own state — the command does not carry it): the OrderTracking projector keys every DeliveryJob-stream fact by payload `orderId`, so an event without one is invisible to the customer's mirror (found live: the `delivery_status`/`courier` reset never reached `ordertracking` — every other rider-authored fact on this stream, DeliveryAcceptedByRider/DeliveryPickedUp/DeliveryCompleted, already carries it).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryHandedBackByRider {
    pub delivery_job_id: DeliveryJobId,
    pub order_id: OrderId,
    pub rider_id: RiderId,
    pub food_location: FoodCustody,
}

/// An issue was reported on a delivery job (by the rider, partner, or support). #639 part C step 3-i (ADR-20260904-015903 §4) added the closed `kind` — NULLABLE because the shape is stored and rows appended before it carry none (additive, readers first); `issue` keeps its 1000 bound so every stored row parses, and is nullable because the command's note is optional now. No field renamed or removed. The report never moves the job's status.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryIssueReported {
    pub delivery_job_id: DeliveryJobId,
    pub rider_id: Option<RiderId>,
    pub kind: Option<DeliveryIssueKind>,
    pub issue: Option<String>,
    pub reported_at: Option<String>,
}

/// A previously reported delivery issue was acknowledged and closed. #639 part C step 3-i (ADR-20260904-015903 §4): `resolution` is the closed `DeliveryIssueResolution` kind (nullable — readers first) and the free text moves to the nullable `note`. No field renamed or removed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryIssueResolved {
    pub delivery_job_id: DeliveryJobId,
    pub resolution: Option<DeliveryIssueResolution>,
    pub note: Option<String>,
    pub resolved_at: Option<String>,
}

/// A delivery partner self-registered its availability to serve a city on a catalog channel (#61). The registration's birth fact; lands PENDING until an admin approves it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryPartnerAvailabilityRequested {
    pub registration_id: DeliveryPartnerRegistrationId,
    pub channel: DeliveryChannelKey,
    pub city_id: CityId,
    pub partner_name: DeliveryPartnerName,
    pub contact_email: EmailAddress,
}

/// An admin approved a delivery partner's city availability (#61); it becomes eligible for the city's dispatch ranking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryPartnerAvailabilityApproved {
    pub registration_id: DeliveryPartnerRegistrationId,
}

/// A delivery partner's city availability was revoked — withdrawn by the partner or disabled by an admin (#61); no longer eligible.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliveryPartnerAvailabilityRevoked {
    pub registration_id: DeliveryPartnerRegistrationId,
    pub reason: Option<String>,
}

/// An independent Captain rider registered (linked to the auth provider user).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RiderRegistered {
    pub rider_id: RiderId,
    pub auth_ref: AuthSubject,
    pub display_name: String,
    pub phone: PhoneNumber,
    pub status: RiderStatus,
}

/// One or more editable rider profile fields changed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RiderInfoUpdated {
    pub rider_id: RiderId,
    pub display_name: Option<String>,
    pub phone: Option<PhoneNumber>,
}

/// A rider's availability/lifecycle status changed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RiderStatusChanged {
    pub rider_id: RiderId,
    pub status: RiderStatus,
}

/// An admin restricted a rider's access, citing one of the closed grounds (ADR-20260904-014136, ADR-20260904-081527 §1-3, §5). Business payload only — the deciding admin is envelope metadata (`domain_events.user_id`). `decidedAt` and `effectiveAt` are both server-set and equal in V0 (the future-effectiveAt form is designed, not shipped, §5); both are kept on the payload as the legal shape either way. The read-side fold keys on THIS FACT, never on `ground`'s value or on RiderStatus — a legacy `RiderStatusChanged { SUSPENDED }` alone never restricts.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RiderRestricted {
    pub rider_id: RiderId,
    pub ground: RiderRestrictionGround,
    pub decided_at: String,
    pub effective_at: String,
}

/// A previously restricted rider was reinstated by an admin (#639 part C step 4-i, ADR-20260904-081527 §1/§6) — a new fact, never a row edit. Business payload only; the deciding admin is envelope metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RiderReinstated {
    pub rider_id: RiderId,
}
