// GENERATED by the Captain.Food codegen from specs/configuration.yaml — do not edit by hand.
//
// The typed runtime configuration (PROP-20260729-004500, issue #246). Every setting the app
// needs is DECLARED in the spec and read here, once, at startup — never through a scattered
// `env::var` call. A missing REQUIRED key (per the resolved `APP_PROFILE`) is collected with
// every other missing key and reported together; the composition root then stops the app.
//
// Secrets are never rendered: the boot report shows `set` / `unset`, and for a key declaring
// `mode_of: stripe` the derived test/live mode — never the value.

// Scope-filtered BIN reader (#374 Q4): which helpers a bin's key subset exercises varies
// per bin, so the shared reader shape carries a module-level allow instead of per-bin
// cfg surgery. The reader's behaviour is covered by the server-side config tests.
#![allow(dead_code)]

use std::fmt;

/// Which keys are required. Declared via `APP_PROFILE`, never inferred from the host or from
/// a key's prefix — an inferred profile is wrong exactly when it matters most (a mode switch).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Profile {
    Development,
    Staging,
    Production,
}

impl Profile {
    pub fn as_str(self) -> &'static str {
        match self {
            Profile::Development => "development",
            Profile::Staging => "staging",
            Profile::Production => "production",
        }
    }
}

impl fmt::Display for Profile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Lenient boolean parsing (ADR-20260728-224500): `true/1/yes/on` and `false/0/no/off`,
/// case-insensitive, trimmed, wrapping quotes stripped. An unrecognised value falls back to the
/// declared default AND says so — a typo must never be silently interpreted as either state.
fn parse_bool(name: &str, raw: &str, default: bool) -> bool {
    match raw.trim().trim_matches(['"', '\'']).trim().to_ascii_lowercase().as_str() {
        "true" | "1" | "yes" | "on" => true,
        "false" | "0" | "no" | "off" => false,
        "" => default,
        other => {
            println!(
                "{name}: unrecognised value {other:?} -- using the default ({default}). \
Accepted: true/1/yes/on, false/0/no/off."
            );
            default
        }
    }
}

/// Read a key, treating an empty/whitespace-only value as ABSENT — a dashboard field someone
/// cleared must count as missing, not as an empty string that satisfies a requirement.
fn raw(name: &str) -> Option<String> {
    std::env::var(name).ok().map(|v| v.trim().to_string()).filter(|v| !v.is_empty())
}

/// Validate a value against its scalar's regex. Compiled once per pattern and cached: startup
/// cost is a handful of small regexes, paid to make "present but unusable" impossible to miss.
fn matches_pattern(pattern: &str, value: &str) -> bool {
    use std::collections::HashMap;
    use std::sync::{Mutex, OnceLock};
    static CACHE: OnceLock<Mutex<HashMap<String, regex::Regex>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut guard = cache.lock().unwrap_or_else(|p| p.into_inner());
    let re = guard.entry(pattern.to_string()).or_insert_with(|| {
        regex::Regex::new(pattern).expect("configuration pattern compiles (checked by codegen)")
    });
    re.is_match(value)
}

/// The non-secret values DECLARED per profile (`deploy:` in configuration.yaml), baked into the
/// binary (PROP-20260729-014500 D5). Render has no per-deploy env override, so this is the only
/// way to make configuration part of the ARTIFACT: the digest then determines behaviour, and a
/// rollback restores the configuration that shipped with that build. Secrets are never here —
/// the GHCR package is public, so a baked value is world-readable.
fn baked(name: &str, profile: Profile) -> Option<&'static str> {
    BAKED
        .iter()
        .find(|(k, p, _)| *k == name && *p == profile.as_str())
        .map(|(_, _, v)| *v)
}

/// Stripe mode from the key prefix — reportable where the key itself never is.
fn stripe_mode(value: &str) -> &'static str {
    if value.starts_with("sk_live_") {
        "live"
    } else if value.starts_with("sk_test_") {
        "test"
    } else {
        "unknown"
    }
}

/// A required key that was not supplied, with the `gates` text from the spec.
#[derive(Debug, Clone)]
pub struct MissingKey {
    pub name: &'static str,
    pub gates: &'static str,
}

/// A key that WAS supplied but does not satisfy its scalar. Carries the expected shape, never
/// the offending value: a malformed secret is still a secret.
#[derive(Debug, Clone)]
pub struct InvalidKey {
    pub name: &'static str,
    pub scalar: &'static str,
    pub pattern: &'static str,
    pub gates: &'static str,
}

/// Everything wrong with the configuration, in one report — never just the first problem. An
/// operator who learns of one bad key per deploy cycle fixes a three-key outage in three deploys.
#[derive(Debug, Clone, Default)]
pub struct ConfigProblems {
    pub missing: Vec<MissingKey>,
    pub invalid: Vec<InvalidKey>,
}

impl ConfigProblems {
    pub fn is_empty(&self) -> bool {
        self.missing.is_empty() && self.invalid.is_empty()
    }

    pub fn len(&self) -> usize {
        self.missing.len() + self.invalid.len()
    }
}

/// The report the app prints before it stops (production/staging) or continues (development).
#[derive(Debug, Clone)]
pub struct MissingConfig {
    pub profile: Profile,
    pub problems: ConfigProblems,
}

impl fmt::Display for MissingConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "FATAL: {} configuration problem(s) (profile: {})\n",
            self.problems.len(),
            self.profile
        )?;
        let width = self
            .problems
            .missing
            .iter()
            .map(|m| m.name.len())
            .chain(self.problems.invalid.iter().map(|i| i.name.len()))
            .max()
            .unwrap_or(0);
        if !self.problems.missing.is_empty() {
            writeln!(f, "MISSING — required in this profile:")?;
            for m in &self.problems.missing {
                writeln!(f, "  {:width$}  {}", m.name, m.gates, width = width)?;
            }
            writeln!(f)?;
        }
        if !self.problems.invalid.is_empty() {
            writeln!(f, "INVALID — supplied but malformed (the value is never printed):")?;
            for i in &self.problems.invalid {
                writeln!(f, "  {:width$}  expected {} matching {}", i.name, i.scalar, i.pattern, width = width)?;
                writeln!(f, "  {:width$}  {}", "", i.gates, width = width)?;
            }
            writeln!(f)?;
        }
        write!(f, "Fix them in the service environment and redeploy. Nothing was started.")
    }
}

/// The resolved configuration. Built once, injected — never re-read from env.
#[derive(Debug, Clone)]
pub struct Config {
    pub profile: Profile,
    /// Postgres pool: the event store, every read model and every background worker. Unset, /health reports `not_configured` (503) and no worker is constructed at all.
    pub database_url: String,
    /// DEFAULT `5`. sqlx pool ceiling per PROCESS (ADR-20260807-183024 realization, issue #385): the monolith and every wired bin size their PgPool from this DECLARED value instead of a per-main constant. Matters at bin granularity: 49 pods x this ceiling is the CNPG cluster's connection budget, so the number must be reviewable in one place. Per-bin tuning is an env override on the pod (env > baked > default), not a code change.
    pub database_pool_max_connections: i64,
    /// Supabase Auth base URL: the passwordless OTP/magic-link flows, AND (#519) half the token verification contract -- the expected `iss` is derived from it as `{SUPABASE_URL}/auth/v1`. Unset, the identity service is the fail-closed stand-in and every login is refused, AND there is no verifier at all: `/public` degrades to anonymous and every ROLE path answers 503. An unset issuer never means "skip the issuer check".
    pub supabase_url: String,
    /// Supabase anon key sent as the `apikey` header on OTP flows. Unset, identity is fail-closed (auth stays anonymous-only).
    pub supabase_publishable_key: String,
    /// JWKS endpoint used to verify Supabase-issued JWTs -- the other half of the #519 verification contract, useless without SUPABASE_URL and vice-versa. Unset, tokens cannot be verified: the open path `/public` falls back to anonymous, and every ROLE path fails closed with 503.
    pub supabase_jwks_url: String,
    /// Honeycomb INGEST key for the OTLP trace/metric exporter (`x-honeycomb-team`). Unset, the exporter is not constructed at all and the app runs with local structured logs only — every span is built and dropped, so a production incident is diagnosed by reading stdout, which is the pre-#191 situation. This must be an INGEST key: a management key (`<id>:<secret>`, what the Honeycomb MCP server and Query API use) has a different shape and is rejected at startup rather than failing as an opaque 401 on the first export.
    pub honeycomb_api_key: Option<String>,
    /// DEFAULT `https://api.eu1.honeycomb.io`. OTLP/HTTP base endpoint. Defaults to and is baked as the **EU** host (`api.eu1.honeycomb.io`) — the US host `api.honeycomb.io` is a GDPR decision, not a preference, because spans carry customer and order ids (ADR-0042 pinned data to Frankfurt). Pointed at the wrong region, exports 401 against an account that does not hold the key and telemetry is silently absent.
    pub honeycomb_api_endpoint: String,
    /// DEFAULT `captain-food-dev`. The Honeycomb service/dataset traces land in, also reported as the OTel `service.name` resource attribute. Baked per profile so staging traffic can never be read as production: sharing one dataset makes a staging load test look like a Friday-night peak and corrupts every SLO computed from it.
    pub honeycomb_dataset: String,
    /// DEFAULT `1.0`. Head-sampling probability, parent-respecting. Baked at `1.0` (keep everything) because PROP-170500 D2's reasoning holds at V0 volume: "head-sampling would mostly discard the interesting traces". This is the dial to turn DOWN if ingest cost becomes real — turning it down before there is volume buys nothing and loses the traces that explain the incidents. Set to 0 and traces stop; the metrics and logs continue, so the app looks healthy while being undiagnosable.
    pub otel_traces_sample_ratio: String,
    /// DEFAULT `info`. Minimum severity for the structured JSON log layer. At `error` the boot report and every worker lifecycle line disappear, which is how a paused pipeline becomes invisible (issue #220) — so the baked value stays `info` and `debug` is an incident tool, not a default.
    pub log_level: String,
    /// DEFAULT `30`. How long a mailbox partition lease lives without renewal (PROP-20260728-152752 §3.1). Too short and healthy workers flap ownership; too long and a crashed worker's partitions sit unserved for that many seconds before takeover — at peak that is paid-order latency. Reader lands with the #242 slice-3 worker.
    pub mailbox_lease_seconds: i64,
    /// DEFAULT `10`. Lease renewal cadence — also the balancing-loop tick (claim free, steal ONE) and the upper bound on the dual-belief window during a steal (§3.1: belief may lag one heartbeat, authority never — the ownership_version fence is commit-time). Keep at roughly a third of MAILBOX_LEASE_SECONDS. Reader lands with the #242 slice-3 worker.
    pub mailbox_heartbeat_seconds: i64,
    /// DEFAULT `false`. ACTIVATIONS (#272 D3, PROP-20260728-152752 §3.5): ON, each mailbox delivery folds the delivered actor's own stream through a shared held-state cache — filled on first load, extended with the committed appends strictly AFTER the fenced transaction commits (apply-after-commit), dropped on a lost version race, on lane loss, on idle expiry and under the memory bound. OFF (gate-then-stabilize; the flip is its own one-line ADR after staging smoke), every delivery folds from the log, byte-identically to the pre-D3 runtime. Correctness never depends on the cache, on BOTH verdict shapes: an APPEND from a stale hold loses the UNIQUE(stream_name, version) race, and a NON-APPEND terminal verdict (a deterministic rejection, an Ignored/Duplicate record) from a cache-served fold re-asserts the stream version inside the fenced transaction — either way the delivery aborts, invalidates and refolds, out-of-band writers (saga-runner legs, peer-process fleets, the deletion engine) included.
    pub actor_activations: bool,
    /// DEFAULT `300`. Global default for activation passivation (PROP-20260728-152752 §3.5): an in-memory actor unsolicited for this long is dropped, its next message paying one rehydration fold. Per-actor overrides live in actors.yaml (mailbox.activations.idle_seconds). Zero would disable the cache; too high and idle aggregates hold memory the LRU bound must then evict. Read by the ACTOR_ACTIVATIONS-gated cache (#272 D3).
    pub actor_activation_idle_seconds: i64,
    /// DEFAULT `64`. The activation cache's byte bound (PROP-20260728-152752 §3.5 "hot cache pressure evicts by size"): crossing it evicts least-recently-used held states, sized by their serialized event payloads. Idle actors expire by the clock (ACTOR_ACTIVATION_IDLE_SECONDS); this bound is the backstop for a hot Friday-peak set larger than memory should carry.
    pub actor_activation_max_memory_mb: i64,
    /// DEFAULT `500`. Events per projection unit-of-work flush (PROP-20260730-230803 §2, 100–1000): one transaction per THIS MANY events instead of one per event. Higher = fewer fsyncs but a larger replay window after a crash and a bigger in-memory identity map. Reader lands with the #267 batched projector.
    pub projection_batch_size: i64,
    /// DEFAULT `64`. Early-flush bound on the projection identity map (PROP-20260730-230803 §4): a batch whose loaded row states outgrow this flushes before reaching PROJECTION_BATCH_SIZE, keeping wide rows (catalog imports) from ballooning the projector. Reader lands with the #267 batched projector.
    pub projection_batch_memory_mb: i64,
    /// DEFAULT `16`. Projection lane keyspace width — hash(business_key) mod THIS routes events to lanes with per-key order preserved (PROP-20260730-230803 §3). Fixed-wide like the mailbox width: changing it re-maps lanes (a drain-then-resize operation), while worker scaling only re-divides lane ownership. Reader lands with the #267 batched projector.
    pub projection_partitions: i64,
    /// DEFAULT `true`. In-process projection worker (ADR-0040). OFF, no read model advances — queries serve stale data indefinitely. Readiness at GET /projector.
    pub run_projector: bool,
    /// DEFAULT `true`. In-process saga runner (actors.yaml process managers). OFF, no cross-aggregate reaction fires. Readiness at GET /saga.
    pub run_process_managers: bool,
    /// DEFAULT `true`. Push wake for the drain loops (ADR-20260802-200416): one dedicated LISTEN connection turns each committed append's pg_notify into an immediate drain of the projector AND the saga runner, replacing the 1.5 s poll as the primary signal (~70,900 idle queries/hour -> ~120). OFF, both loops fall back to unassisted 1.5 s polling — correct but bandwidth-expensive; the escape hatch for a deployment behind a TRANSACTION-mode pooler, which silently cannot carry LISTEN (session pooler required, e.g. Supabase port 5432).
    pub run_event_push: bool,
    /// DEFAULT `true`. Push wake for the actor mailbox (PROP-20260802-223522 D1/D2, ADR-20260802-224532): the PgMailbox door raises pg_notify('inbound_messages', actor_type) inside every enqueue transaction, and one dedicated LISTEN connection per consuming process turns it into an immediate nudge of that actor type's worker — including ACROSS processes, so a standalone adapter's recorded fact wakes the monolith's worker on commit instead of waiting out the heartbeat (up to 10 s on the payment path). While push is confirmed live the full drain pass stretches to the 60 s safety net; lease renewal (beat) stays on MAILBOX_HEARTBEAT_SECONDS unconditionally. OFF — or whenever the listener is down — workers fall back to full passes at the heartbeat cadence: exactly the pre-push behaviour, never worse. Liveness is CANARY-VERIFIED, not assumed: the listener notifies itself on the same channel every canary interval and drops to down (mailbox_push_down_total{reason}) when the echo does not come back within the next interval — this catches the transaction-mode pooler's failure mode, where LISTEN registers but silently delivers nothing (session pooler required, e.g. Supabase port 5432 — same constraint as RUN_EVENT_PUSH).
    pub run_mailbox_push: bool,
    /// DEFAULT `5`. Poison bound (PROP-20260802-223522 D4): a delivery whose completion transaction fails with an infrastructure error (the status flip aborts with it, so nothing is recorded on the row) increments inbound_messages.attempts OUTSIDE the failed transaction; at this cap the row flips to terminal FAILED with the error recorded and the lane's head-of-line unblocks. Counts only actual delivery attempts — a lane that cannot be claimed consumes none, and re-attempts back off EXPONENTIALLY (ADR-20260803-002712 Q2): attempt N schedules the next try base * 2^(N-1) seconds out, base = the heartbeat (10s -> 20s -> 40s -> 80s -> 160s, ~5 min to terminal at cap 5), because push-driven retries have no natural cadence: without pacing, a nudge storm at Friday peak could burn the whole cap on a seconds-long transient blip (review #314 MAJOR-3). 0 = no cap: the pre-#313 infinite-retry behaviour, kept as the rollback lever. Handler REJECTED/FAILED verdicts are terminal on the first attempt and never involve this cap. A poison flip is an OPERATOR EVENT: counted (mailbox_poison_failed_total{actor_type}) and surfaced per lane on the ADMIN mailboxLanes supervision query (retryingAttempts/poisoned).
    pub mailbox_max_delivery_attempts: i64,
    /// DEFAULT `false`. The generic deletion engine (ADR-20260731-214500 §4): runs the declared deletion journeys (tombstone -> stream deletion -> ledger receipt) for every actors.yaml `deletion:` block. OFF, recorded expiry facts accumulate and no stream is ever erased — GDPR deletion pauses, data is never lost. Gate-then-stabilize: this worker DELETES event streams; the default flips by its own one-line ADR after the gated form is smoked in staging. Readiness at GET /deletion.
    pub run_deletion_engine: bool,
    /// DEFAULT `true`. Retention sweep over terminal journal/mirror rows. OFF, nothing expires and storage grows without bound.
    pub run_retention_sweep: bool,
    /// The sender name shown on the SMS. Unset, the client substitutes `CaptainFood`. Declares NO `default` deliberately: the fallback lives in `OvhSmsClient::from_env`, and a second copy here would be two sources of truth for one value. OVH requires a sender to be REGISTERED and approved before it can be used, so an unapproved name fails at send time, not at startup.
    pub ovh_sms_sender: Option<String>,
    /// OVH API base URL. Unset, the client substitutes `https://eu.api.ovh.com/1.0` — the EU region, which is the deliberate choice for data residency (ADR-20260722-174500) and must match the region the API credentials were created in. Declares NO `default` for the same reason as OVH_SMS_SENDER: the fallback is the client's.
    pub ovh_endpoint: Option<String>,
    /// The deployed server's drain endpoint, pinged at the end of a sweep so the worker starts in seconds instead of waiting for its hourly poll. Unset, the sweep logs that it skipped the ping — which is how department 37's 6,649 rows stayed PENDING after a successful ingestion.
    pub internal_trigger_url: Option<String>,
    /// DEFAULT `8080`. TCP port the HTTP server binds. Render injects this; a mismatch means the platform health check never reaches the app and the deploy fails.
    pub port: i64,
    /// DEFAULT `/app/web-assets`. Directory served for the Leptos/WASM bundle. Wrong path, the storefront loads no assets.
    pub web_assets_dir: String,
    /// DEFAULT ``. Subgraph address overrides for the gateway-{role} bins (#385, D8): comma-separated `scope=url` pairs. Empty (the default), a gateway resolves each scope to its in-cluster Service DNS (`http://graphql-{scope}`) — so in Kubernetes nothing sets this; a local or off-cluster gateway that cannot resolve Service names routes nowhere without it.
    pub gateway_subgraph_urls: String,
    /// DEFAULT ``. The role-gateway origin the fo-*/bo-* surface bins resolve SSR reads through (#385, D8 — a surface holds no database credential; it reads only over GraphQL, always as the anonymous PUBLIC role). Empty (the default) resolves the in-cluster `http://gateway-public` Service; a local or off-cluster surface renders data-less shells without it.
    pub surface_gateway_url: String,
    /// Short git SHA baked into the image at build time (ADR-20260721-175411) and reported by /health and the X-VERSION header. Unset, `build_version()` substitutes `dev-<crate version>` for local and uncontainerized runs, so a build that forgot it is identifiable AS unidentified. Deliberately declares NO `default`: the fallback is COMPUTED (it interpolates the crate version), and a spec default of plain `dev` would state a value the runtime never produces — a false declaration is worse than an absent one.
    pub captain_build_version: Option<String>,
    /// DEFAULT `900`. The Restaurant.serviceWindow.validUntil horizon (RSO-1, DECISIONS §43 sub-question iii): validUntil = min(next window transition, evaluatedAt + this horizon), and under HOURS_UNDECLARED — where no transition exists to wait for — it is evaluatedAt + horizon alone. Exists so no cache can treat a verdict as immortal: without it a restaurant declaring its hours at 18:50 on a Friday would keep rendering a blank badge in every warm cache at the hour it matters. Seconds; the 900 default trades staleness against re-evaluation load at Friday-peak list fan-out.
    pub service_window_validity_horizon_seconds: i64,
    /// DEFAULT `false`. SIRENE staging drain (ADR-0045): translates `external_sirene_restaurants` rows through the ACL and releases their payloads. PAUSED since 2026-07-28 with the CI sweep (issue #220). OFF, staged rows stay PENDING indefinitely and registry-driven prospect creation does not happen. Readiness at GET /sirene.
    pub run_sirene_worker: bool,
    /// INSEE portal API key, sent as `X-INSEE-Api-Key-Integration` (no OAuth2 on the 2024+ portal). `SireneClient::from_env` FAILS when it is unset, so a sweep with no token does not silently ingest zero établissements — it refuses. No `deploy` block: this consumer runs in GitHub Actions, which injects the repo secret of the same name directly; the Render sync (which only carries the server service) has nothing to do with it.
    pub insee_api_token: Option<String>,
    /// Override of the version-pinned Sirene base URL. Exists because the version is IN the path (`/api-sirene/3.11`): when INSEE bumps it, a sweep can be redirected without a release. Unset, the client uses its own pinned constant -- so no `default` here, which would be a second copy of it.
    pub insee_api_base_url: Option<String>,
    /// Comma-separated departments to sweep, honoured VERBATIM and in order (e.g. `37` for Tours only). Blank = stalest-first across all of France (#218). Set per workflow_dispatch run, not persisted.
    pub sirene_departments: Option<String>,
    /// Wall-clock a sweep may spend before stopping cleanly at a department boundary. Blank = the binary default (75 sweep / 60 compact); the run resumes where it stopped on the next invocation.
    pub sirene_budget_minutes: Option<String>,
}

impl Config {
    /// Resolve from the process environment, returning the config AND every missing required
    /// key. Both, always: the warn-only rollout phase (`CONFIG_ENFORCE=false`, D5) has to boot
    /// with the config it managed to build while still reporting what was absent. A missing
    /// required string resolves to empty — the caller decides whether that is fatal.
    pub fn resolve() -> (Self, ConfigProblems) {
        Self::resolve_inner()
    }

    /// Strict form: `Err` when anything required is missing. Used by tests and any caller that
    /// wants no warn-only escape hatch.
    pub fn from_env() -> Result<Self, MissingConfig> {
        let (cfg, problems) = Self::resolve_inner();
        if problems.is_empty() {
            Ok(cfg)
        } else {
            Err(MissingConfig { profile: cfg.profile, problems })
        }
    }

    /// Whether a configuration problem must STOP the app. Decided by the PROFILE, not by a
    /// separate toggle (product-owner directive 2026-07-29): production and staging stop,
    /// development reports and continues. Stopping is safe on Render — an exiting container
    /// fails the deploy and the PREVIOUS version keeps serving, so a misconfigured build can
    /// never replace a working one.
    pub fn must_stop_on_problems(&self) -> bool {
        !matches!(self.profile, Profile::Development)
    }

    fn resolve_inner() -> (Self, ConfigProblems) {
        let profile = match raw("APP_PROFILE").as_deref() {
            Some("production") => Profile::Production,
            Some("staging") => Profile::Staging,
            Some("development") | None => Profile::Development,
            Some(other) => {
                println!("APP_PROFILE: unrecognised value {other:?} -- using development.");
                Profile::Development
            }
        };
        let mut problems = ConfigProblems::default();
        let database_url = raw("DATABASE_URL");
        if database_url.is_none() && matches!(profile, Profile::Staging | Profile::Production) {
            problems.missing.push(MissingKey { name: "DATABASE_URL", gates: "Postgres pool: the event store, every read model and every background worker. Unset, /health reports `not_configured` (503) and no worker is constructed at all." });
        }
        let database_url = database_url.unwrap_or_default();
        let database_pool_max_connections = raw("DATABASE_POOL_MAX_CONNECTIONS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(5);
        let supabase_url = raw("SUPABASE_URL").or_else(|| baked("SUPABASE_URL", profile).map(str::to_string));
        if supabase_url.is_none() && matches!(profile, Profile::Staging | Profile::Production) {
            problems.missing.push(MissingKey { name: "SUPABASE_URL", gates: "Supabase Auth base URL: the passwordless OTP/magic-link flows, AND (#519) half the token verification contract -- the expected `iss` is derived from it as `{SUPABASE_URL}/auth/v1`. Unset, the identity service is the fail-closed stand-in and every login is refused, AND there is no verifier at all: `/public` degrades to anonymous and every ROLE path answers 503. An unset issuer never means \"skip the issuer check\"." });
        }
        let supabase_url = supabase_url.unwrap_or_default();
        let supabase_publishable_key = raw("SUPABASE_PUBLISHABLE_KEY").or_else(|| baked("SUPABASE_PUBLISHABLE_KEY", profile).map(str::to_string));
        if supabase_publishable_key.is_none() && matches!(profile, Profile::Staging | Profile::Production) {
            problems.missing.push(MissingKey { name: "SUPABASE_PUBLISHABLE_KEY", gates: "Supabase anon key sent as the `apikey` header on OTP flows. Unset, identity is fail-closed (auth stays anonymous-only)." });
        }
        let supabase_publishable_key = supabase_publishable_key.unwrap_or_default();
        let supabase_jwks_url = raw("SUPABASE_JWKS_URL").or_else(|| baked("SUPABASE_JWKS_URL", profile).map(str::to_string));
        if supabase_jwks_url.is_none() && matches!(profile, Profile::Staging | Profile::Production) {
            problems.missing.push(MissingKey { name: "SUPABASE_JWKS_URL", gates: "JWKS endpoint used to verify Supabase-issued JWTs -- the other half of the #519 verification contract, useless without SUPABASE_URL and vice-versa. Unset, tokens cannot be verified: the open path `/public` falls back to anonymous, and every ROLE path fails closed with 503." });
        }
        let supabase_jwks_url = supabase_jwks_url.unwrap_or_default();
        let honeycomb_api_key = raw("HONEYCOMB_API_KEY");
        let honeycomb_api_endpoint = raw("HONEYCOMB_API_ENDPOINT").or_else(|| baked("HONEYCOMB_API_ENDPOINT", profile).map(str::to_string));
        let honeycomb_api_endpoint = honeycomb_api_endpoint.unwrap_or_else(|| "https://api.eu1.honeycomb.io".to_string());
        let honeycomb_dataset = raw("HONEYCOMB_DATASET").or_else(|| baked("HONEYCOMB_DATASET", profile).map(str::to_string));
        let honeycomb_dataset = honeycomb_dataset.unwrap_or_else(|| "captain-food-dev".to_string());
        let otel_traces_sample_ratio = raw("OTEL_TRACES_SAMPLE_RATIO").or_else(|| baked("OTEL_TRACES_SAMPLE_RATIO", profile).map(str::to_string));
        let otel_traces_sample_ratio = otel_traces_sample_ratio.unwrap_or_else(|| "1.0".to_string());
        let log_level = raw("LOG_LEVEL").or_else(|| baked("LOG_LEVEL", profile).map(str::to_string));
        let log_level = log_level.unwrap_or_else(|| "info".to_string());
        let mailbox_lease_seconds = raw("MAILBOX_LEASE_SECONDS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(30);
        let mailbox_heartbeat_seconds = raw("MAILBOX_HEARTBEAT_SECONDS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(10);
        let actor_activations = raw("ACTOR_ACTIVATIONS")
            .or_else(|| baked("ACTOR_ACTIVATIONS", profile).map(str::to_string))
            .map(|v| parse_bool("ACTOR_ACTIVATIONS", &v, false))
            .unwrap_or(false);
        let actor_activation_idle_seconds = raw("ACTOR_ACTIVATION_IDLE_SECONDS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(300);
        let actor_activation_max_memory_mb = raw("ACTOR_ACTIVATION_MAX_MEMORY_MB").and_then(|v| v.parse::<i64>().ok()).unwrap_or(64);
        let projection_batch_size = raw("PROJECTION_BATCH_SIZE").and_then(|v| v.parse::<i64>().ok()).unwrap_or(500);
        let projection_batch_memory_mb = raw("PROJECTION_BATCH_MEMORY_MB").and_then(|v| v.parse::<i64>().ok()).unwrap_or(64);
        let projection_partitions = raw("PROJECTION_PARTITIONS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(16);
        let run_projector = raw("RUN_PROJECTOR")
            .or_else(|| baked("RUN_PROJECTOR", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_PROJECTOR", &v, true))
            .unwrap_or(true);
        let run_process_managers = raw("RUN_PROCESS_MANAGERS")
            .or_else(|| baked("RUN_PROCESS_MANAGERS", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_PROCESS_MANAGERS", &v, true))
            .unwrap_or(true);
        let run_event_push = raw("RUN_EVENT_PUSH")
            .or_else(|| baked("RUN_EVENT_PUSH", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_EVENT_PUSH", &v, true))
            .unwrap_or(true);
        let run_mailbox_push = raw("RUN_MAILBOX_PUSH")
            .or_else(|| baked("RUN_MAILBOX_PUSH", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_MAILBOX_PUSH", &v, true))
            .unwrap_or(true);
        let mailbox_max_delivery_attempts = raw("MAILBOX_MAX_DELIVERY_ATTEMPTS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(5);
        let run_deletion_engine = raw("RUN_DELETION_ENGINE")
            .or_else(|| baked("RUN_DELETION_ENGINE", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_DELETION_ENGINE", &v, false))
            .unwrap_or(false);
        let run_retention_sweep = raw("RUN_RETENTION_SWEEP")
            .or_else(|| baked("RUN_RETENTION_SWEEP", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_RETENTION_SWEEP", &v, true))
            .unwrap_or(true);
        let ovh_sms_sender = raw("OVH_SMS_SENDER");
        let ovh_endpoint = raw("OVH_ENDPOINT");
        let internal_trigger_url = raw("INTERNAL_TRIGGER_URL");
        let port = raw("PORT").and_then(|v| v.parse::<i64>().ok()).unwrap_or(8080);
        let web_assets_dir = raw("WEB_ASSETS_DIR");
        let web_assets_dir = web_assets_dir.unwrap_or_else(|| "/app/web-assets".to_string());
        let gateway_subgraph_urls = raw("GATEWAY_SUBGRAPH_URLS");
        let gateway_subgraph_urls = gateway_subgraph_urls.unwrap_or_else(|| "".to_string());
        let surface_gateway_url = raw("SURFACE_GATEWAY_URL");
        let surface_gateway_url = surface_gateway_url.unwrap_or_else(|| "".to_string());
        let captain_build_version = raw("CAPTAIN_BUILD_VERSION");
        let service_window_validity_horizon_seconds = raw("SERVICE_WINDOW_VALIDITY_HORIZON_SECONDS").and_then(|v| v.parse::<i64>().ok()).unwrap_or(900);
        let run_sirene_worker = raw("RUN_SIRENE_WORKER")
            .or_else(|| baked("RUN_SIRENE_WORKER", profile).map(str::to_string))
            .map(|v| parse_bool("RUN_SIRENE_WORKER", &v, false))
            .unwrap_or(false);
        let insee_api_token = raw("INSEE_API_TOKEN");
        let insee_api_base_url = raw("INSEE_API_BASE_URL");
        let sirene_departments = raw("SIRENE_DEPARTMENTS");
        let sirene_budget_minutes = raw("SIRENE_BUDGET_MINUTES");
        if let Some(v) = Some(database_url.as_str()) {
            if !v.is_empty() && !matches_pattern("^postgres(ql)?://", v) {
                problems.invalid.push(InvalidKey { name: "DATABASE_URL", scalar: "PostgresUrl", pattern: "^postgres(ql)?://", gates: "Postgres pool: the event store, every read model and every background worker. Unset, /health reports `not_configured` (503) and no worker is constructed at all." });
            }
        }
        if let Some(v) = Some(supabase_url.as_str()) {
            if !v.is_empty() && !matches_pattern("^https?://", v) {
                problems.invalid.push(InvalidKey { name: "SUPABASE_URL", scalar: "HttpsUrl", pattern: "^https?://", gates: "Supabase Auth base URL: the passwordless OTP/magic-link flows, AND (#519) half the token verification contract -- the expected `iss` is derived from it as `{SUPABASE_URL}/auth/v1`. Unset, the identity service is the fail-closed stand-in and every login is refused, AND there is no verifier at all: `/public` degrades to anonymous and every ROLE path answers 503. An unset issuer never means \"skip the issuer check\"." });
            }
        }
        if let Some(v) = Some(supabase_jwks_url.as_str()) {
            if !v.is_empty() && !matches_pattern("^https?://", v) {
                problems.invalid.push(InvalidKey { name: "SUPABASE_JWKS_URL", scalar: "HttpsUrl", pattern: "^https?://", gates: "JWKS endpoint used to verify Supabase-issued JWTs -- the other half of the #519 verification contract, useless without SUPABASE_URL and vice-versa. Unset, tokens cannot be verified: the open path `/public` falls back to anonymous, and every ROLE path fails closed with 503." });
            }
        }
        if let Some(v) = honeycomb_api_key.as_deref() {
            if !v.is_empty() && !matches_pattern("^[A-Za-z0-9_]{20,120}$", v) {
                problems.invalid.push(InvalidKey { name: "HONEYCOMB_API_KEY", scalar: "HoneycombIngestKey", pattern: "^[A-Za-z0-9_]{20,120}$", gates: "Honeycomb INGEST key for the OTLP trace/metric exporter (`x-honeycomb-team`). Unset, the exporter is not constructed at all and the app runs with local structured logs only — every span is built and dropped, so a production incident is diagnosed by reading stdout, which is the pre-#191 situation. This must be an INGEST key: a management key (`<id>:<secret>`, what the Honeycomb MCP server and Query API use) has a different shape and is rejected at startup rather than failing as an opaque 401 on the first export." });
            }
        }
        if let Some(v) = Some(honeycomb_api_endpoint.as_str()) {
            if !v.is_empty() && !matches_pattern("^https?://", v) {
                problems.invalid.push(InvalidKey { name: "HONEYCOMB_API_ENDPOINT", scalar: "HttpsUrl", pattern: "^https?://", gates: "OTLP/HTTP base endpoint. Defaults to and is baked as the **EU** host (`api.eu1.honeycomb.io`) — the US host `api.honeycomb.io` is a GDPR decision, not a preference, because spans carry customer and order ids (ADR-0042 pinned data to Frankfurt). Pointed at the wrong region, exports 401 against an account that does not hold the key and telemetry is silently absent." });
            }
        }
        if let Some(v) = Some(otel_traces_sample_ratio.as_str()) {
            if !v.is_empty() && !matches_pattern("^(0(\\.[0-9]+)?|1(\\.0+)?)$", v) {
                problems.invalid.push(InvalidKey { name: "OTEL_TRACES_SAMPLE_RATIO", scalar: "TraceSampleRatio", pattern: "^(0(\\.[0-9]+)?|1(\\.0+)?)$", gates: "Head-sampling probability, parent-respecting. Baked at `1.0` (keep everything) because PROP-170500 D2's reasoning holds at V0 volume: \"head-sampling would mostly discard the interesting traces\". This is the dial to turn DOWN if ingest cost becomes real — turning it down before there is volume buys nothing and loses the traces that explain the incidents. Set to 0 and traces stop; the metrics and logs continue, so the app looks healthy while being undiagnosable." });
            }
        }
        if let Some(v) = Some(log_level.as_str()) {
            if !v.is_empty() && !matches_pattern("^(?i)(trace|debug|info|warn|error)$", v) {
                problems.invalid.push(InvalidKey { name: "LOG_LEVEL", scalar: "LogLevel", pattern: "^(?i)(trace|debug|info|warn|error)$", gates: "Minimum severity for the structured JSON log layer. At `error` the boot report and every worker lifecycle line disappear, which is how a paused pipeline becomes invisible (issue #220) — so the baked value stays `info` and `debug` is an incident tool, not a default." });
            }
        }
        if let Some(v) = internal_trigger_url.as_deref() {
            if !v.is_empty() && !matches_pattern("^https?://", v) {
                problems.invalid.push(InvalidKey { name: "INTERNAL_TRIGGER_URL", scalar: "HttpsUrl", pattern: "^https?://", gates: "The deployed server's drain endpoint, pinged at the end of a sweep so the worker starts in seconds instead of waiting for its hourly poll. Unset, the sweep logs that it skipped the ping — which is how department 37's 6,649 rows stayed PENDING after a successful ingestion." });
            }
        }
        if let Some(v) = insee_api_base_url.as_deref() {
            if !v.is_empty() && !matches_pattern("^https?://", v) {
                problems.invalid.push(InvalidKey { name: "INSEE_API_BASE_URL", scalar: "HttpsUrl", pattern: "^https?://", gates: "Override of the version-pinned Sirene base URL. Exists because the version is IN the path (`/api-sirene/3.11`): when INSEE bumps it, a sweep can be redirected without a release. Unset, the client uses its own pinned constant -- so no `default` here, which would be a second copy of it." });
            }
        }
        if let Some(v) = sirene_departments.as_deref() {
            if !v.is_empty() && !matches_pattern("^([0-9]{2,3}|2[AB])(,([0-9]{2,3}|2[AB]))*$", v) {
                problems.invalid.push(InvalidKey { name: "SIRENE_DEPARTMENTS", scalar: "DepartmentList", pattern: "^([0-9]{2,3}|2[AB])(,([0-9]{2,3}|2[AB]))*$", gates: "Comma-separated departments to sweep, honoured VERBATIM and in order (e.g. `37` for Tours only). Blank = stalest-first across all of France (#218). Set per workflow_dispatch run, not persisted." });
            }
        }
        (
            Self {
                profile,
                database_url,
                database_pool_max_connections,
                supabase_url,
                supabase_publishable_key,
                supabase_jwks_url,
                honeycomb_api_key,
                honeycomb_api_endpoint,
                honeycomb_dataset,
                otel_traces_sample_ratio,
                log_level,
                mailbox_lease_seconds,
                mailbox_heartbeat_seconds,
                actor_activations,
                actor_activation_idle_seconds,
                actor_activation_max_memory_mb,
                projection_batch_size,
                projection_batch_memory_mb,
                projection_partitions,
                run_projector,
                run_process_managers,
                run_event_push,
                run_mailbox_push,
                mailbox_max_delivery_attempts,
                run_deletion_engine,
                run_retention_sweep,
                ovh_sms_sender,
                ovh_endpoint,
                internal_trigger_url,
                port,
                web_assets_dir,
                gateway_subgraph_urls,
                surface_gateway_url,
                captain_build_version,
                service_window_validity_horizon_seconds,
                run_sirene_worker,
                insee_api_token,
                insee_api_base_url,
                sirene_departments,
                sirene_budget_minutes,
            },
            problems,
        )
    }

    /// The declared reminder/deletion window keys (actors.yaml `after:` refs), each with its
    /// resolved runtime value as a TYPED Duration (the key's declared `unit:` is applied HERE,
    /// #167) — handed to the mailbox delivery glue so scheduling reads configuration, never a
    /// constant (ADR-20260731-214500).
    pub fn reminder_windows(&self) -> std::collections::HashMap<&'static str, std::time::Duration> {
        [
        ]
        .into_iter()
        .collect()
    }

    /// What actually resolved, for the boot log. Secrets render as `set` / `unset`, never as a
    /// value; a key declaring `mode_of: stripe` additionally reports its derived mode, so
    /// "is production actually live?" is answerable without reading a secret.
    pub fn boot_report(&self) -> String {
        let mut out = format!("config: profile={}, {} keys resolved\n", self.profile, KEY_COUNT);
        out.push_str(&format!("  DATABASE_URL               = {}\n", if self.database_url.is_empty() { "unset" } else { "set" }));
        out.push_str(&format!("  DATABASE_POOL_MAX_CONNECTIONS = {}\n", self.database_pool_max_connections));
        out.push_str(&format!("  SUPABASE_URL               = {}\n", self.supabase_url));
        out.push_str(&format!("  SUPABASE_PUBLISHABLE_KEY   = {}\n", self.supabase_publishable_key));
        out.push_str(&format!("  SUPABASE_JWKS_URL          = {}\n", self.supabase_jwks_url));
        out.push_str(&format!("  HONEYCOMB_API_KEY          = {}\n", if self.honeycomb_api_key.is_some() { "set" } else { "unset" }));
        out.push_str(&format!("  HONEYCOMB_API_ENDPOINT     = {}\n", self.honeycomb_api_endpoint));
        out.push_str(&format!("  HONEYCOMB_DATASET          = {}\n", self.honeycomb_dataset));
        out.push_str(&format!("  OTEL_TRACES_SAMPLE_RATIO   = {}\n", self.otel_traces_sample_ratio));
        out.push_str(&format!("  LOG_LEVEL                  = {}\n", self.log_level));
        out.push_str(&format!("  MAILBOX_LEASE_SECONDS      = {}\n", self.mailbox_lease_seconds));
        out.push_str(&format!("  MAILBOX_HEARTBEAT_SECONDS  = {}\n", self.mailbox_heartbeat_seconds));
        out.push_str(&format!("  ACTOR_ACTIVATIONS          = {}\n", self.actor_activations));
        out.push_str(&format!("  ACTOR_ACTIVATION_IDLE_SECONDS = {}\n", self.actor_activation_idle_seconds));
        out.push_str(&format!("  ACTOR_ACTIVATION_MAX_MEMORY_MB = {}\n", self.actor_activation_max_memory_mb));
        out.push_str(&format!("  PROJECTION_BATCH_SIZE      = {}\n", self.projection_batch_size));
        out.push_str(&format!("  PROJECTION_BATCH_MEMORY_MB = {}\n", self.projection_batch_memory_mb));
        out.push_str(&format!("  PROJECTION_PARTITIONS      = {}\n", self.projection_partitions));
        out.push_str(&format!("  RUN_PROJECTOR              = {}\n", self.run_projector));
        out.push_str(&format!("  RUN_PROCESS_MANAGERS       = {}\n", self.run_process_managers));
        out.push_str(&format!("  RUN_EVENT_PUSH             = {}\n", self.run_event_push));
        out.push_str(&format!("  RUN_MAILBOX_PUSH           = {}\n", self.run_mailbox_push));
        out.push_str(&format!("  MAILBOX_MAX_DELIVERY_ATTEMPTS = {}\n", self.mailbox_max_delivery_attempts));
        out.push_str(&format!("  RUN_DELETION_ENGINE        = {}\n", self.run_deletion_engine));
        out.push_str(&format!("  RUN_RETENTION_SWEEP        = {}\n", self.run_retention_sweep));
        out.push_str(&format!("  OVH_SMS_SENDER             = {}\n", self.ovh_sms_sender.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  OVH_ENDPOINT               = {}\n", self.ovh_endpoint.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  INTERNAL_TRIGGER_URL       = {}\n", self.internal_trigger_url.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  PORT                       = {}\n", self.port));
        out.push_str(&format!("  WEB_ASSETS_DIR             = {}\n", self.web_assets_dir));
        out.push_str(&format!("  GATEWAY_SUBGRAPH_URLS      = {}\n", self.gateway_subgraph_urls));
        out.push_str(&format!("  SURFACE_GATEWAY_URL        = {}\n", self.surface_gateway_url));
        out.push_str(&format!("  CAPTAIN_BUILD_VERSION      = {}\n", self.captain_build_version.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  SERVICE_WINDOW_VALIDITY_HORIZON_SECONDS = {}\n", self.service_window_validity_horizon_seconds));
        out.push_str(&format!("  RUN_SIRENE_WORKER          = {}\n", self.run_sirene_worker));
        out.push_str(&format!("  INSEE_API_TOKEN            = {}\n", if self.insee_api_token.is_some() { "set" } else { "unset" }));
        out.push_str(&format!("  INSEE_API_BASE_URL         = {}\n", self.insee_api_base_url.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  SIRENE_DEPARTMENTS         = {}\n", self.sirene_departments.as_deref().unwrap_or("unset")));
        out.push_str(&format!("  SIRENE_BUDGET_MINUTES      = {}\n", self.sirene_budget_minutes.as_deref().unwrap_or("unset")));
        out
    }
}

/// How many keys the spec declares (excluding the profile selector).
pub const KEY_COUNT: usize = 39;

/// Every declared key name — the drift test asserts each `env::var` call site is one of these.
pub const DECLARED_KEYS: &[&str] = &[
    "APP_PROFILE",
    "DATABASE_URL",
    "DATABASE_POOL_MAX_CONNECTIONS",
    "SUPABASE_URL",
    "SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_JWKS_URL",
    "HONEYCOMB_API_KEY",
    "HONEYCOMB_API_ENDPOINT",
    "HONEYCOMB_DATASET",
    "OTEL_TRACES_SAMPLE_RATIO",
    "LOG_LEVEL",
    "MAILBOX_LEASE_SECONDS",
    "MAILBOX_HEARTBEAT_SECONDS",
    "ACTOR_ACTIVATIONS",
    "ACTOR_ACTIVATION_IDLE_SECONDS",
    "ACTOR_ACTIVATION_MAX_MEMORY_MB",
    "PROJECTION_BATCH_SIZE",
    "PROJECTION_BATCH_MEMORY_MB",
    "PROJECTION_PARTITIONS",
    "RUN_PROJECTOR",
    "RUN_PROCESS_MANAGERS",
    "RUN_EVENT_PUSH",
    "RUN_MAILBOX_PUSH",
    "MAILBOX_MAX_DELIVERY_ATTEMPTS",
    "RUN_DELETION_ENGINE",
    "RUN_RETENTION_SWEEP",
    "OVH_SMS_SENDER",
    "OVH_ENDPOINT",
    "INTERNAL_TRIGGER_URL",
    "PORT",
    "WEB_ASSETS_DIR",
    "GATEWAY_SUBGRAPH_URLS",
    "SURFACE_GATEWAY_URL",
    "CAPTAIN_BUILD_VERSION",
    "SERVICE_WINDOW_VALIDITY_HORIZON_SECONDS",
    "RUN_SIRENE_WORKER",
    "INSEE_API_TOKEN",
    "INSEE_API_BASE_URL",
    "SIRENE_DEPARTMENTS",
    "SIRENE_BUDGET_MINUTES",
];

/// `(key, profile, value)` — the declared non-secret configuration, baked in. Reviewed in a PR
/// and carried by the image digest, so redeploying a digest reproduces its behaviour exactly.
const BAKED: &[(&str, &str, &str)] = &[
    ("SUPABASE_URL", "production", "https://zcshlzhiinwmpzujuiep.supabase.co"),
    ("SUPABASE_URL", "staging", "https://zcshlzhiinwmpzujuiep.supabase.co"),
    ("SUPABASE_PUBLISHABLE_KEY", "production", "sb_publishable_iJnNRwbG123-7bNcFEtz7Q_IvhhfwBE"),
    ("SUPABASE_PUBLISHABLE_KEY", "staging", "sb_publishable_iJnNRwbG123-7bNcFEtz7Q_IvhhfwBE"),
    ("SUPABASE_JWKS_URL", "production", "https://zcshlzhiinwmpzujuiep.supabase.co/auth/v1/.well-known/jwks.json"),
    ("SUPABASE_JWKS_URL", "staging", "https://zcshlzhiinwmpzujuiep.supabase.co/auth/v1/.well-known/jwks.json"),
    ("HONEYCOMB_API_ENDPOINT", "production", "https://api.eu1.honeycomb.io"),
    ("HONEYCOMB_API_ENDPOINT", "staging", "https://api.eu1.honeycomb.io"),
    ("HONEYCOMB_DATASET", "production", "captain-food"),
    ("HONEYCOMB_DATASET", "staging", "captain-food-staging"),
    ("OTEL_TRACES_SAMPLE_RATIO", "production", "1.0"),
    ("OTEL_TRACES_SAMPLE_RATIO", "staging", "1.0"),
    ("LOG_LEVEL", "production", "info"),
    ("LOG_LEVEL", "staging", "info"),
    ("RUN_PROJECTOR", "production", "true"),
    ("RUN_PROJECTOR", "staging", "true"),
    ("RUN_PROCESS_MANAGERS", "production", "true"),
    ("RUN_PROCESS_MANAGERS", "staging", "true"),
    ("RUN_EVENT_PUSH", "production", "true"),
    ("RUN_EVENT_PUSH", "staging", "true"),
    ("RUN_MAILBOX_PUSH", "production", "true"),
    ("RUN_MAILBOX_PUSH", "staging", "true"),
    ("RUN_RETENTION_SWEEP", "production", "true"),
    ("RUN_RETENTION_SWEEP", "staging", "true"),
    ("RUN_SIRENE_WORKER", "production", "true"),
    ("RUN_SIRENE_WORKER", "staging", "true"),
];
