// GENERATED by the Captain.Food codegen from specs/customer/commands.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use domain_common::entities::*;
use domain_common::scalars::*;

/// Ask Supabase Auth to send an SMS OTP to a phone (OVHcloud SMS via the Supabase send-SMS hook; a mock provider in dev). Emits no event. `locale` localizes the message; when absent it defaults from the dialing code (e.g. '+33' → fr-FR).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestPhoneVerification {
    pub dialing_code: DialingCode,
    pub national_number: NationalPhoneNumber,
    pub locale: Option<Locale>,
}

/// Verify the SMS OTP with Supabase Auth, then register-or-identify: a first verified phone CREATES the Customer (CustomerRegistered), a returning phone RESOLVES + signs in (CustomerIdentified). The backend decides new-vs-returning; the client never calls register/identify directly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerifyPhone {
    pub customer_id: CustomerId,
    pub dialing_code: DialingCode,
    pub national_number: NationalPhoneNumber,
    pub code: OtpCode,
    pub session_id: SessionId,
    pub display_name: Option<CustomerDisplayName>,
    pub locale: Option<Locale>,
    pub timezone: Option<TimeZone>,
}

/// Ask Supabase Auth to email a magic link to verify/link an email for the signed-in customer. Emits no event; the message is localized via the customer's STORED locale (no per-call language param).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestEmailVerification {
    pub customer_id: CustomerId,
    pub email: EmailAddress,
}

/// Confirm an email magic link: the client returns the Supabase token, we VERIFY it server-side and link the now-verified email to the Customer. Used for both the initial email and later changes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmEmailVerification {
    pub customer_id: CustomerId,
    pub token: EmailVerificationToken,
}

/// Ask Supabase to send an SMS OTP to a NEW phone for a signed-in customer (stored locale). Emits no event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestPhoneChange {
    pub customer_id: CustomerId,
    pub new_dialing_code: DialingCode,
    pub new_national_number: NationalPhoneNumber,
}

/// Verify the OTP on the new phone and change the customer's phone (→ canonical E.164 PhoneNumber).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmPhoneChange {
    pub customer_id: CustomerId,
    pub new_dialing_code: DialingCode,
    pub new_national_number: NationalPhoneNumber,
    pub code: OtpCode,
}

/// Persist the customer's preferred language (the single locale setter). The stored locale then localizes subsequent authenticated SMS/email sends — so they need no per-call language param.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChangeLanguage {
    pub customer_id: CustomerId,
    pub locale: Locale,
}

/// Customer marks a restaurant as a favorite for quick access.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarkRestaurantAsFavorite {
    pub customer_id: CustomerId,
    pub restaurant_id: RestaurantId,
}

/// Customer removes a restaurant from their favorites.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmarkRestaurantAsFavorite {
    pub customer_id: CustomerId,
    pub restaurant_id: RestaurantId,
}

/// Customer updates their display name. (Email is verified-only — set via ConfirmEmailVerification.)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateCustomerInfo {
    pub customer_id: CustomerId,
    pub display_name: Option<CustomerDisplayName>,
}

/// Customer sets discovery + i18n preferences (timezone, dietary restrictions, favorite cuisines). Language is set via ChangeLanguage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetCustomerPreferences {
    pub customer_id: CustomerId,
    pub timezone: Option<TimeZone>,
    #[serde(default)]
    pub dietary_tags: Vec<Tag>,
    #[serde(default)]
    pub favorite_cuisines: Vec<Tag>,
}

/// Customer adds or updates a saved delivery address in their address book.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetCustomerAddress {
    pub customer_id: CustomerId,
    pub address_id: AddressId,
    pub label: Option<String>,
    pub address: Address,
}

/// Customer removes a saved address from their address book.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RemoveCustomerAddress {
    pub customer_id: CustomerId,
    pub address_id: AddressId,
}

/// Customer sets or updates their preferred Stripe payment method.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetCustomerPaymentMethod {
    pub customer_id: CustomerId,
    pub payment_method_id: PaymentMethodId,
}

/// Ask for this account and its personal data to be erased (GDPR Art. 17). Acceptance-first: the mutation returns the `erasureRequestId` and the fact is recorded by the aggregate, which is what lets the status surface answer immediately. IDEMPOTENT while one request is pending — a second ask returns the SAME id and records nothing new, because a double-tap on a delete button is a nervous customer, not a second intention. Rejected with `ErasureBlockedByOpenOrder` when an order is in flight, and with `ErasureEngineUnavailable` when the deletion engine is gated OFF in this deployment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestCustomerErasure {
    pub customer_id: CustomerId,
    pub erasure_request_id: ErasureRequestId,
}

/// Confirm the erasure with the token sent to the subject's verified channel — the SECOND round-trip that turns a request into a scheduled destruction. On acceptance the grace window starts and the `deletion:` trigger arms. The token is verified server-side and is the ONLY thing that authorizes the confirm; it is deliberately not "being logged in", because the whole point of the second step is to prove the person holding the session is the person who owns the channel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmCustomerErasure {
    pub customer_id: CustomerId,
    pub erasure_request_id: ErasureRequestId,
    pub token: ErasureConfirmationToken,
}

/// The subject changed their mind inside the grace window and keeps their account. RE-LOGIN-CANCELS is the recorded posture: cancelling is the USER's act — there is no admin resurrection, because an erasure an operator can undo is not an erasure. A returning customer placing an order is the strongest cancel-intent signal there is, but it does NOT auto-cancel: the recorded intent stands until the subject withdraws it; an in-flight order only defers EXECUTION (the PARKED arm).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CancelCustomerErasure {
    pub customer_id: CustomerId,
    pub erasure_request_id: ErasureRequestId,
}
