// GENERATED by the Captain.Food codegen from specs/customer/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// The SMS OTP code does not match (rejected by Supabase Auth).
/// Context: `phone`.
pub const INVALID_VERIFICATION_CODE: ErrorDef = ErrorDef {
    code: "InvalidVerificationCode",
    message_en: "The verification code is incorrect. Please try again.",
    message_fr: "Le code de vérification est incorrect. Veuillez réessayer.",
};

/// The SMS OTP (or email link) has expired; request a new one.
pub const VERIFICATION_CODE_EXPIRED: ErrorDef = ErrorDef {
    code: "VerificationCodeExpired",
    message_en: "The verification code has expired. Please request a new one.",
    message_fr: "Le code de vérification a expiré. Veuillez en demander un nouveau.",
};

/// The email magic-link token failed server-side verification with Supabase Auth.
pub const INVALID_VERIFICATION_TOKEN: ErrorDef = ErrorDef {
    code: "InvalidVerificationToken",
    message_en: "This email verification link is invalid or has already been used.",
    message_fr: "Ce lien de vérification d'e-mail est invalide ou a déjà été utilisé.",
};

/// The email is already linked to another customer.
/// Context: `email`.
pub const EMAIL_ALREADY_IN_USE: ErrorDef = ErrorDef {
    code: "EmailAlreadyInUse",
    message_en: "The email '{email}' is already in use by another account.",
    message_fr: "L'e-mail '{email}' est déjà utilisé par un autre compte.",
};

/// The phone number is already linked to another customer (on change).
/// Context: `phone`.
pub const PHONE_ALREADY_IN_USE: ErrorDef = ErrorDef {
    code: "PhoneAlreadyInUse",
    message_en: "The phone number '{phone}' is already in use by another account.",
    message_fr: "Le numéro '{phone}' est déjà utilisé par un autre compte.",
};
