// GENERATED by the Captain.Food codegen from specs/customer/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// The phone's dialing code is outside the served set (`SMS_ALLOWED_DIALING_CODES`). NOT a validation error and NOT an accusation: it lands on a real person whose number is simply somewhere we do not deliver yet, so the message NAMES the country code and points at an exit. The allowlist is the served-country decision plus cost containment — a calling code is not a destination, and a code we do not serve can reach territories rated far above what we budgeted (the global ceiling, not this list, is the economic control against pumping) — which is why the refusal is fail-closed: an unparseable number lands here too, never on a send.
/// Context: `dialingCode`.
pub const PHONE_COUNTRY_NOT_SERVED: ErrorDef = ErrorDef {
    code: "PhoneCountryNotServed",
    message_en: "We can't send a code to {dialingCode} numbers yet — we deliver in Tours. Please use a French mobile number, or contact us.",
    message_fr: "Nous ne pouvons pas encore envoyer de code vers les numéros {dialingCode} — nous livrons à Tours. Utilisez un numéro de mobile français ou contactez-nous.",
};

/// This phone number has used up its allowance of OTP sends for the day. Deliberately NOT a `RateLimited`: there is no countdown worth rendering (tomorrow is not a countdown), so the screen must offer help instead of a timer. A customer who genuinely burned five sends has a delivery problem no sixth SMS will fix.
pub const VERIFICATION_SEND_LIMIT_REACHED: ErrorDef = ErrorDef {
    code: "VerificationSendLimitReached",
    message_en: "You've requested too many codes today. Please try again tomorrow, or contact us and we'll help you sign in.",
    message_fr: "Vous avez demandé trop de codes aujourd'hui. Réessayez demain ou contactez-nous, nous vous aiderons à vous connecter.",
};

/// The GLOBAL daily SMS ceiling is spent, so NO further OTP is sent to anyone until it is raised (#516). This is the one refusal that turns legitimate sign-ups away ON PURPOSE: per-number caps limit an individual, and an attacker rotates numbers, so only a total ceiling bounds the bill. It must be LOUD — if this fires, either the ceiling is too low for real traffic or an attack is under way, and both need a human tonight.
pub const VERIFICATION_SEND_CAPACITY_EXHAUSTED: ErrorDef = ErrorDef {
    code: "VerificationSendCapacityExhausted",
    message_en: "We can't send verification codes right now. Please contact us — we'll get you signed in.",
    message_fr: "Nous ne pouvons pas envoyer de code de vérification pour le moment. Contactez-nous, nous vous connecterons.",
};

/// The SMS OTP code does not match (rejected by Supabase Auth).
/// Context: `phone`.
pub const INVALID_VERIFICATION_CODE: ErrorDef = ErrorDef {
    code: "InvalidVerificationCode",
    message_en: "The verification code is incorrect. Please try again.",
    message_fr: "Le code de vérification est incorrect. Veuillez réessayer.",
};

/// The SMS OTP (or email link) has expired; request a new one.
pub const VERIFICATION_CODE_EXPIRED: ErrorDef = ErrorDef {
    code: "VerificationCodeExpired",
    message_en: "The verification code has expired. Please request a new one.",
    message_fr: "Le code de vérification a expiré. Veuillez en demander un nouveau.",
};

/// The email magic-link token failed server-side verification with Supabase Auth.
pub const INVALID_VERIFICATION_TOKEN: ErrorDef = ErrorDef {
    code: "InvalidVerificationToken",
    message_en: "This email verification link is invalid or has already been used.",
    message_fr: "Ce lien de vérification d'e-mail est invalide ou a déjà été utilisé.",
};

/// The email is already linked to another customer.
/// Context: `email`.
pub const EMAIL_ALREADY_IN_USE: ErrorDef = ErrorDef {
    code: "EmailAlreadyInUse",
    message_en: "The email '{email}' is already in use by another account.",
    message_fr: "L'e-mail '{email}' est déjà utilisé par un autre compte.",
};

/// The phone number is already linked to another customer (on change).
/// Context: `phone`.
pub const PHONE_ALREADY_IN_USE: ErrorDef = ErrorDef {
    code: "PhoneAlreadyInUse",
    message_en: "The phone number '{phone}' is already in use by another account.",
    message_fr: "Le numéro '{phone}' est déjà utilisé par un autre compte.",
};

/// The customer asked to be erased while an order of theirs is still in flight (or money is still settling). A set-based precondition the write side checks, which is exactly why erasure begins as a rejectable COMMAND and not an event: an event cannot be refused, a command can. NOT a refusal of the right — a refusal of the TIMING, and the message must say so, because a person exercising Art. 17 who reads "no" will not ask twice. The same precondition re-runs at promotion, where failing it PARKS the journey rather than rejecting it (the request already stands by then; only execution waits).
/// Context: `openOrders`.
pub const ERASURE_BLOCKED_BY_OPEN_ORDER: ErrorDef = ErrorDef {
    code: "ErasureBlockedByOpenOrder",
    message_en: "You have an order in progress. You can request deletion once it is complete — your request has not been recorded.",
    message_fr: "Vous avez une commande en cours. Vous pourrez demander la suppression une fois celle-ci terminée — votre demande n'a pas été enregistrée.",
};

/// The erasure confirmation token does not verify, or its window has expired. DELIBERATELY NOT `InvalidVerificationToken`, which already means the email magic link: one name, one meaning. Overloading it would render "this email verification link is invalid" to a customer who is trying to delete their account — a lie at the highest-stakes tap in the product, and one that would send them to the wrong recovery path.
pub const INVALID_ERASURE_CONFIRMATION_TOKEN: ErrorDef = ErrorDef {
    code: "InvalidErasureConfirmationToken",
    message_en: "This deletion confirmation link is invalid or has expired. Please request deletion again.",
    message_fr: "Ce lien de confirmation de suppression est invalide ou a expiré. Veuillez redemander la suppression.",
};

/// A confirm or cancel arrived with no erasure request outstanding for this customer — the request was already confirmed, already cancelled, or never made. Typed rather than silent because both commands are irreversible-adjacent: a cancel that quietly does nothing would let a customer believe they had kept an account that is still scheduled for deletion.
pub const ERASURE_NOT_REQUESTED: ErrorDef = ErrorDef {
    code: "ErasureNotRequested",
    message_en: "There is no deletion request to act on for this account.",
    message_fr: "Aucune demande de suppression n'est en cours pour ce compte.",
};

/// Erasure is declared but its engine is not running in this deployment (`configuration.yaml#/RUN_DELETION_ENGINE` is OFF — the single gate, gate-then-stabilize). THE MUTATIONS SHIP DARK BEHIND THAT SAME FLAG, AND DARK MEANS A TYPED REFUSAL, NEVER A SILENT ACCEPT (farley). Accepting a request the engine cannot execute would start the Art. 12(3) thirty-day clock on a journey nothing will ever run, and produce a status screen that says "scheduled" forever: the erasure analogue of a paid order nobody is told about — and worse here, because the subject stops chasing a right they believe is being honoured. Refusing loudly keeps the failure OURS instead of moving it onto the customer. A second flag was rejected on purpose: one blast radius, one decision surface.
pub const ERASURE_ENGINE_UNAVAILABLE: ErrorDef = ErrorDef {
    code: "ErasureEngineUnavailable",
    message_en: "Account deletion is temporarily unavailable. Please contact us and we will handle your request.",
    message_fr: "La suppression de compte est temporairement indisponible. Contactez-nous et nous traiterons votre demande.",
};
