// GENERATED by the Captain.Food codegen from specs/customer/events.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use domain_common::entities::*;
use domain_common::scalars::*;

/// A customer account was created on first phone verification (passwordless OTP, identity managed by the auth provider). Phone number is the primary identifier.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerRegistered {
    pub mode: Option<Mode>,
    pub customer_id: CustomerId,
    pub auth_ref: Option<ExternalReference>,
    pub phone: PhoneNumber,
    pub display_name: Option<CustomerDisplayName>,
    pub email: Option<EmailAddress>,
    pub locale: Option<Locale>,
    pub timezone: Option<TimeZone>,
}

/// A returning visitor signed in and was resolved to an existing Customer (authRef → customerId). NOT an auth event (OTP/session live in the auth provider): this records the DOMAIN fact so the visitor's OPEN guest carts can be bound to the customerId — letting carts started on different devices converge under one customer and be merged at checkout. Thanks to the sessionId, the existing open cart(s) can be bound to the customerId and merged at checkout. This is a domain event, not an auth event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerIdentified {
    pub customer_id: CustomerId,
    pub auth_ref: ExternalReference,
    pub session_id: SessionId,
}

/// Customer marked a restaurant as a favorite.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RestaurantFavorited {
    pub customer_id: CustomerId,
    pub restaurant_id: RestaurantId,
}

/// Customer removed a restaurant from their favorites.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RestaurantUnfavorited {
    pub customer_id: CustomerId,
    pub restaurant_id: RestaurantId,
}

/// Customer updated their display name. (Email is verified-only — see CustomerEmailVerified.)
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerInfoUpdated {
    pub customer_id: CustomerId,
    pub display_name: Option<CustomerDisplayName>,
}

/// An email was verified (Supabase magic link) and linked to the Customer — initial set OR a later change.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerEmailVerified {
    pub customer_id: CustomerId,
    pub email: EmailAddress,
}

/// The Customer's phone was changed after re-verification (canonical E.164).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerPhoneChanged {
    pub customer_id: CustomerId,
    pub phone: PhoneNumber,
}

/// The Customer's preferred language (locale) was set/changed; localizes later SMS/email sends.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerLanguageChanged {
    pub customer_id: CustomerId,
    pub locale: Locale,
}

/// Customer set their discovery + i18n preferences (timezone, dietary restrictions, favorite cuisines). Language is CustomerLanguageChanged.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerPreferencesSet {
    pub customer_id: CustomerId,
    pub timezone: Option<TimeZone>,
    #[serde(default)]
    pub dietary_tags: Vec<Tag>,
    #[serde(default)]
    pub favorite_cuisines: Vec<Tag>,
}

/// Customer added or updated a saved delivery address.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerAddressSet {
    pub customer_id: CustomerId,
    pub address_id: AddressId,
    pub label: Option<String>,
    pub address: Address,
}

/// Customer removed a saved address.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerAddressRemoved {
    pub customer_id: CustomerId,
    pub address_id: AddressId,
}

/// Customer set or updated their preferred Stripe payment method.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomerPaymentMethodSet {
    pub customer_id: CustomerId,
    pub payment_method_id: PaymentMethodId,
}
