// GENERATED by the Captain.Food codegen from specs/customer/ — do not edit by hand
// (#373, ADR-20260807-183024 step 2).

//! Captain.Food `domain-customer`: the `customer` scope's generated domain types.
//! Types only — aggregates/handlers/folds stay in their layer crates; the `domain` facade
//! re-exports these modules so existing `domain::generated::*` paths keep the same type identity.

pub mod scalars;
pub mod events;
pub mod commands;
pub mod errors;
