// GENERATED by the Captain.Food codegen from specs/ordering/events.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use crate::entities::*;
use domain_common::entities::*;
use domain_common::scalars::*;

/// A cart that was started by a guest visitor (no customerId) was bound to a Customer after sign-in. This is a domain event, not an auth event. The cartId is the same as the original guest cart; the cart's customerId is now set to the signed-in customer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartBoundToCustomer {
    pub cart_id: CartId,
    pub customer_id: CustomerId,
}

/// A new cart was created for a restaurant (emitted with the first line added).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartStarted {
    pub cart_id: CartId,
    pub restaurant_id: RestaurantId,
    pub session_id: SessionId,
    pub customer_id: Option<CustomerId>,
}

/// A line was added to a cart.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartLineAdded {
    pub cart_id: CartId,
    pub line: CartLineItem,
}

/// The quantity of an existing cart line changed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartLineQuantityChanged {
    pub cart_id: CartId,
    pub cart_line_id: CartLineId,
    pub quantity: i64,
}

/// A line was removed from a cart.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartLineRemoved {
    pub cart_id: CartId,
    pub cart_line_id: CartLineId,
}

/// The cart was converted to an order at checkout and is now closed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CartCheckedOut {
    pub cart_id: CartId,
    pub order_id: OrderId,
}

/// A customer has placed an order and payment was successfully authorized/captured.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderPlaced {
    pub mode: Option<Mode>,
    pub order_id: OrderId,
    pub r#ref: Option<ExternalReference>,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub customer_contact: CustomerContact,
    pub service_type: ServiceType,
    pub delivery_address: Option<Address>,
    pub items: Vec<OrderLineItem>,
    pub total_amount: Money,
    pub breakdown: PaymentBreakdown,
    pub note: Option<OrderNote>,
    pub replacement_of: Option<OrderId>,
    pub payment_intent_id: Option<PaymentIntentId>,
}

/// Restaurant has accepted to prepare the order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderAcceptedByRestaurant {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub estimated_ready_at: Option<String>,
}

/// Restaurant has started preparing an accepted order (status PREPARING).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderPreparationStarted {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
}

/// Restaurant has rejected the order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderRejectedByRestaurant {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub reason: String,
}

/// Restaurant has marked the order as ready for pickup/delivery.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderMarkedReady {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
}

/// The order has been delivered to the customer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderDelivered {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
}

/// The customer cancelled the order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderCancelledByCustomer {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub reason: Option<String>,
}

/// The restaurant cancelled the order after initial acceptance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderCancelledByRestaurant {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub reason: String,
}

/// The customer rated the delivery of a completed order (rider thumbs up/down).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderRated {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub rider_thumb: ThumbRating,
}

/// The customer rated the restaurant of a completed order (0–5 stars + optional comment).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RestaurantRated {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub stars: StarRating,
    pub comment: Option<RatingComment>,
}

/// The customer answered the delivery-delay satisfaction survey for a delivered order (#62): the timeliness verdict (+ an optional reason when TOO_LATE). Recorded once per order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeliverySatisfactionRecorded {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub timeliness: DeliveryTimeliness,
    pub reason: Option<DeliveryDissatisfactionReason>,
}

/// A tipper (customer or restaurant) added one or more tips (rider / restaurant / Captain) on an order (ADR-012). Separate from the price; Captain keeps 0%. Additive — multiple OrderTipped accumulate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderTipped {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub tipped_by: Tipper,
    pub customer_id: Option<CustomerId>,
    pub tips: Vec<Tip>,
}

/// The customer requested a refund for an order; the RefundProcess will drive Stripe.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefundRequested {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub reason: Option<String>,
}

/// A refundable fact on a paid order (rejection, cancellation, customer request) opened a refund for a restaurant/admin decision. Delivered by RefundProcess to the Payment aggregate ONLY when the payment is CAPTURED, so the refund queue (View_PendingRefunds) folds from the log, not from PM state. `amount` is the captured order total eligible for refund (an approval may still be partial).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefundOpened {
    pub payment_intent_id: PaymentIntentId,
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub amount: Money,
    pub reason: Option<String>,
}

/// Birth of a customer reclamation over a delivered order (id = reclamationId; #153). Records the category, the customer's description and — optionally — the resolution the customer requested. Carries `customerId` (whose claim) and `restaurantId` (on whose restaurant's order) — business data the client supplies, mirroring how OrderPlaced carries them — so the read model can scope "my claims" and the restaurant's claims queue (#154). The 14-day window and order-eligibility (order exists/delivered) are enforced in the application layer when opening, not by the aggregate (#151).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReclamationOpened {
    pub reclamation_id: ReclamationId,
    pub order_id: OrderId,
    pub customer_id: CustomerId,
    pub restaurant_id: RestaurantId,
    pub category: ReclamationCategory,
    pub description: ReclamationDescription,
    pub requested_resolution: Option<ReclamationResolution>,
}

/// A reclamation was decided (resolved). Carries the chosen `resolution` and, for a PARTIAL_REFUND or a GOODWILL_CREDIT, the `refundAmount` — so the downstream refund/credit/replacement slices can react to the recorded decision. The aggregate records the DECISION only; it performs no money-move (#151). `orderId` AND `customerId` ride along (sourced from the aggregate's own fold state, established at ReclamationOpened) so the claim lifecycle can be woven into the per-order conversation thread, keyed by order (§2.5, #155), and so the ReclamationProcess saga can grant goodwill credit to the claimant without a read step (ADR-20260726-163737, #158).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReclamationResolved {
    pub reclamation_id: ReclamationId,
    pub order_id: OrderId,
    pub customer_id: CustomerId,
    pub resolution: ReclamationResolution,
    pub note: Option<ReclamationReason>,
    pub refund_amount: Option<Money>,
}

/// A reclamation was rejected (the claim was declined) with a recorded reason (rules.yaml#/ReclamationRejectionCarriesAReason) (#151). `orderId` rides along (from the aggregate's fold state) so the claim lifecycle weaves into the per-order conversation thread, keyed by order (#155).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReclamationRejected {
    pub reclamation_id: ReclamationId,
    pub order_id: OrderId,
    pub reason: ReclamationReason,
}

/// A previously decided (resolved or rejected) reclamation was reopened for another look (rules.yaml#/OnlyDecidedReclamationsCanBeReopened). `reason` is optional — a reopen need not state why — mirroring the optional command input (there is no reason-required guard on reopen, unlike reject) (#151). `orderId` rides along (from the aggregate's fold state) so the claim lifecycle weaves into the per-order conversation thread, keyed by order (#155).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReclamationReopened {
    pub reclamation_id: ReclamationId,
    pub order_id: OrderId,
    pub reason: Option<ReclamationReason>,
}

/// The customer attached an evidence photo to their claim — an opaque, framework-managed attachment ref (storage/moderation/GDPR retention handled generically by the framework, not this aggregate; #156). Evidence may be attached in any lifecycle state — the only guard is that the claim exists. `orderId` rides along (from the aggregate's fold state, established at ReclamationOpened) so the evidence weaves into the per-order conversation thread, keyed by order (§2.5, #155).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReclamationEvidenceAttached {
    pub reclamation_id: ReclamationId,
    pub order_id: OrderId,
    pub attachment_ref: AttachmentRef,
}

/// The order's retention window elapsed — at this moment the order IS expired: no discussion, no rejection possible (ADR-20260731-153000 §1a: a FACT, never a command). Scheduled by the Order actor's OrderExpired reminder when a terminal lifecycle fact is recorded (`schedules:` on the terminal receives, ADR-20260731-214500 §2), delivered by the promotion pass when due, and recorded with record semantics (Recorded, or Ignored/Duplicate — never Rejected). Recording it starts the order's exit from the system (ADR-20260731-160000): projections fold it to tombstone their rows, and the generic deletion engine reacts to the recorded fact with the journey that ends in the OrderDeleted receipt. The erasure ACTION on this recording is a STUB until the engine's journey lands (#194 "GDPR erasure").
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderExpired {
    pub order_id: OrderId,
}

/// The deletion receipt (ADR-20260731-160000 §6): recorded on the DELETION LEDGER stream — never on the (about-to-be / already deleted) order streams — when the generic deletion engine's journey completes (projection checkpoints verified → technical tombstone appended → streams deleted from domain_events + domain_stream). Carries PSEUDONYMOUS domain references only: whose order was erased must remain answerable (GDPR accountability), but never the erased personal payloads (address, phone, conversation content — those are gone).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OrderDeleted {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub policy: String,
    pub tombstone_event_id: Option<String>,
}
