// GENERATED by the Captain.Food codegen from specs/ordering/scalars.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};

/// Identifies a line within a cart, used to edit its quantity or remove it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CartLineId(pub uuid::Uuid);

/// An OPAQUE, server-signed token binding a cart's priced read to the exact catalog coordinate that produced it (PROP-20260831-134539 slice 3b, ADR-20260906-192007 D-A/D-J) — base64url, no internal structure a client may parse or construct. Returned by `cart.current`/`cart` on the SAME read that painted the total the customer sees; `null` on that same read means one of three things, never distinguished on the wire (D-D's cause-neutral posture, restated at the read): the fold-priced read is CLOSED (`configuration.yaml#/RUN_FOLD_PRICED_CART_READ` off — no coordinate exists to sign), the fold itself failed, or this is the `carts` LIST read (D-L: the fan-out never mints, structurally). The checkout submits the quote of the read that painted `/checkout`'s own recap total, never one stashed at `/cart` (restaurant_frontoffice.yaml — the /cart→/checkout binding). DARK on the write side until a later phase of this PR lands the signer/verifier and the write door (`configuration.yaml#/RUN_QUOTE_REQUIRED_ON_PLACE_ORDER`): today the value returned here is accepted structurally on `PlaceOrder.quote` but never read by any code.
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CartQuote(pub String);

/// Restaurant rating in stars (0–5), given by the customer on a delivered order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct StarRating(pub i64);

/// Rider rating: thumbs up or down.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum ThumbRating {
    UP,
    DOWN,
}

/// Free-text comment accompanying a restaurant rating.
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RatingComment(pub String);

/// The customer's post-delivery verdict on the delivery delay (#62), asked once a DELIVERY order is delivered. The subjective counterpart of the objective delivered/late facts (ADR-0031/#60); feeds the restaurant's self-dispatch-vs-Captain decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum DeliveryTimeliness {
    ON_TIME,
    ACCEPTABLE_DELAY,
    TOO_LATE,
}

/// Optional free-text reason a customer gives for a TOO_LATE delivery-timeliness verdict (#62).
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DeliveryDissatisfactionReason(pub String);

/// Who a tip goes to (ADR-012). Tips are separate from the core 3-way split and Captain skims 0% (100% passes through); a tip to CAPTAIN is the tipper's explicit choice, not a cut of others' tips.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum TipRecipient {
    RIDER,
    RESTAURANT,
    CAPTAIN,
}

/// Who gives a tip: the CUSTOMER (may tip rider/restaurant/Captain) or the RESTAURANT (may tip rider/ Captain — e.g. thanking the courier). Derived server-side from the caller's role, not client-supplied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum Tipper {
    CUSTOMER,
    RESTAURANT,
}

/// Lifecycle of a cart. Only an OPEN cart accepts line edits or checkout. Carts are never abandoned/expired — they persist until checked out, so there is no abandonment state.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum CartStatus {
    OPEN,
    CHECKED_OUT,
}

/// Free-text description of the problem the customer is claiming about the order (#151).
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ReclamationDescription(pub String);

/// Lifecycle of a reclamation as the read model folds it from the domain facts (View_Reclamation): OPEN on ReclamationOpened (awaiting a decision), RESOLVED on ReclamationResolved, REJECTED on ReclamationRejected, and back to OPEN on ReclamationReopened. Mirrors the pure domain enum in `crates/domain/src/reclamation.rs`; this DSL scalar backs the view/api derived status (#154).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum ReclamationStatus {
    OPEN,
    RESOLVED,
    REJECTED,
}
