// GENERATED by the Captain.Food codegen from specs/payments/scalars.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};

/// Stripe Refund id (provider reference). Example: 're_3Nabc...'.
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RefundId(pub String);

/// Lifecycle of a refund request as read models fold it from the domain facts (View_PendingRefunds): REQUESTED on RefundOpened (awaiting a restaurant/admin decision), APPROVED on RefundApproved (Stripe refund requested), DENIED on RefundDenied, REFUNDED once Stripe settles (PaymentRefunded). Distinct from RefundProcessStatus, the RefundProcess state-table run status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum RefundStatus {
    REQUESTED,
    APPROVED,
    DENIED,
    REFUNDED,
}

/// Why capturing a confirmed authorization failed AFTER fulfilment (PaymentCaptureFailed — the food is cooked and the money did not move, ADR-20260808-195315 §1.2 team note): CARD_DECLINED = the issuer refused the capture; AUTHORIZATION_EXPIRED = the ~7-day hold lapsed before capture; GATEWAY_REFUSED = Stripe refused the request deterministically (already captured/canceled, keying bug); GATEWAY_UNAVAILABLE = transport/5xx — the capture MAY have succeeded provider-side (the settled PaymentCaptured webhook supersedes this fact when it did).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[allow(non_camel_case_types)]
pub enum CaptureFailureReason {
    CARD_DECLINED,
    AUTHORIZATION_EXPIRED,
    GATEWAY_REFUSED,
    GATEWAY_UNAVAILABLE,
}
