// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260807-183024 steps 3+4 and #385).

//! `adapter-uber-direct` — partner webhook ingestion bin for `uber-direct` -- verify, mirror, ACL, ENQUEUE on the shared mailbox; holds ONLY this partner's secrets (one bin per adapter, ADR-20260808-062432).
//!
//! BUSINESS RUNTIME (#385 API-tier wiring): hosts the `uber-direct` partner webhook ingestor: verify, mirror into the external_* journals, translate through the ACL, ENQUEUE on the shared mailbox — the owning actor bins deliver. This pod holds ONLY this partner's secrets (ADR-20260808-062432). Serves the `/health` + `/ping` probes its
//! generated Deployment (deploy/generated/manifests/bins/adapter-uber-direct.yaml) declares (`wired:true`),
//! draining on SIGTERM.
//!
//! GATE-THEN-STABILIZE: runnable end-to-end, but the monolith `server` bin remains the DEPLOYED
//! production runtime until ADR-20260807-183024 steps (6)–(7) (#358 cutover) point traffic and
//! the mailbox at these pods.

/// The bin's scope-filtered typed configuration (#374 Q4): the declared keys of its linked
/// scopes + `common`, read once at startup — the same generated reader the monolith uses,
/// emitted over this bin's key subset.
mod config;

/// The c4-l2 container this binary realizes.
const BIN: &str = "adapter-uber-direct";
/// The bin's family in the deploy topology.
const FAMILY: &str = "adapter";
/// The ONE partner ACL this bin hosts (one bin per adapter, ADR-20260808-062432).
const PARTNER: &str = "uber-direct";

#[tokio::main]
async fn main() {
    // Identity FIRST, before any fallible startup (ADR-20260721-175411): a boot that never binds
    // still names its version in the logs.
    println!("{BIN} ({FAMILY}) starting -- version {}, business runtime (#385)", bin_runtime::build_version());

    // Configuration gate (PROP-20260729-004500): every problem reported at once; production and
    // staging refuse to start on a broken configuration, development reports and continues.
    let (config, problems) = config::Config::resolve();

    // Telemetry SECOND -- after config (it needs LOG_LEVEL and the ingest key), before every
    // worker, so their startup lines are structured and correlated (issue #191).
    let mut telemetry_guard = bin_runtime::init_telemetry(bin_runtime::TelemetrySettings {
        api_key: config.honeycomb_api_key.clone(),
        endpoint: config.honeycomb_api_endpoint.clone(),
        dataset: config.honeycomb_dataset.clone(),
        sample_ratio: config.otel_traces_sample_ratio.clone(),
        log_level: config.log_level.clone(),
        profile: config.profile.to_string(),
    });
    if !problems.is_empty() {
        let report = config::MissingConfig { profile: config.profile, problems };
        tracing::error!(profile = %config.profile, "{report}");
        if config.must_stop_on_problems() {
            // Flush before exiting, or the error explaining the failed deploy never leaves the box.
            telemetry_guard.shutdown();
            // 78 = EX_CONFIG (sysexits.h): a configuration error, not a crash.
            std::process::exit(78);
        }
        tracing::warn!(profile = %config.profile, "starting anyway -- production and staging STOP here");
    }
    tracing::info!("{}", config.boot_report());

    // Without a database nothing can be mirrored or enqueued: stay a viable pod that says so
    // (readiness 503) -- the config gate already stopped prod/staging.
    let db_ready = !config.database_url.is_empty();
    let app = if db_ready {
        let pool = bin_runtime::pg_pool(&config.database_url, config.database_pool_max_connections)
            .unwrap_or_else(|e| panic!("{BIN}: pg pool init: {e}"));
        // Enqueue→worker nudges are in-process wakes; the owning actor bins are woken by the
        // mailbox INSERT's pg_notify (ADR-20260802-200416) — registered for monolith parity.
        let nudges = {
            let mut n = infrastructure::persistence::mailbox_store::MailboxNudges::default();
            for (actor_type, _) in infrastructure::generated::command_router::ACTOR_MAILBOXES {
                n.register(actor_type);
            }
            std::sync::Arc::new(n)
        };
        let mailbox = || {
            std::sync::Arc::new(
                infrastructure::persistence::mailbox_store::PgMailbox::new(pool.clone())
                    .with_nudges(nudges.clone()),
            )
        };
        // Uber Direct (issue #57): POST /adapters/uber-direct/webhooks (X-Uber-Signature HMAC).
        let ingestor = std::sync::Arc::new(uber_direct_adapter::UberDirectWebhookIngestor::new(
            std::sync::Arc::new(uber_direct_adapter::PgRawUberDirectEvents::new(pool.clone())),
            mailbox(),
        ));
        let uber_direct_config = uber_direct_adapter::UberDirectConfig::from_env().unwrap_or_else(|e| {
            tracing::warn!(error = %e, key = "UBER_DIRECT_*", "misconfigured, treating as unset");
            None
        });
        uber_direct_adapter::routes(uber_direct_adapter::UberDirectWebhookState {
            ingestor: Some(ingestor),
            webhook_secret: uber_direct_config.map(|c| std::sync::Arc::new(c.webhook_secret)),
        })
    } else {
        tracing::warn!(bin = BIN, "DATABASE_URL unset -- webhook ingestion not mounted, readiness stays 503");
        Default::default()
    };
    // Readiness = this partner's ingestion routes are mounted over their database.
    let health: bin_runtime::HealthFn = std::sync::Arc::new(move || {
        (
            db_ready,
            serde_json::json!({
                "adapter": PARTNER,
                "db": if db_ready { "configured" } else { "not_configured" },
            }),
        )
    });
    bin_runtime::serve_with_app(BIN, FAMILY, &config.port.to_string(), health, app).await;
    telemetry_guard.shutdown();
}
