// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260807-183024 steps 3+4, #382/#349).

//! `graphql-customer` — GraphQL subgraph for the `customer` scope -- one domain, one graph, one GRANT (D8).
//!
//! PROBE-SERVING SHELL (gate-then-stabilize): binds `$PORT` and serves the `/health` + `/ping`
//! probes its generated Deployment (deploy/generated/manifests/bins/graphql-customer.yaml) declares,
//! draining on SIGTERM — a viable pod, not yet the business runtime. The monolith `server` bin
//! remains the deployed production runtime; this bin's business wiring is tracked on #349 and
//! flips with steps (6)–(7) (#358 cutover).

// The manifest is the scope assertion; these imports make each declared domain-crate
// link a compile-checked fact (the linker cannot silently strip it).
use domain_customer as _;

/// The c4-l2 container this binary realizes.
const BIN: &str = "graphql-customer";
/// The bin's family in the deploy topology.
const FAMILY: &str = "subgraph";

#[tokio::main]
async fn main() {
    // Identity FIRST, before any fallible startup (ADR-20260721-175411): a boot that never binds
    // still names its version in the logs. `dev` outside an image; CI bakes `sha-<commit>`.
    let version = std::env::var("CAPTAIN_BUILD_VERSION").unwrap_or_else(|_| "dev".into());
    println!("{BIN} ({FAMILY}) starting -- version {version}, probe-serving shell (#349)");

    // `wired:false` is the shell telling the truth: the pod is viable (probes pass) but the
    // business runtime is not hosted here yet. Real wiring flips this with its own /health.
    let health_body = format!(
        "{{\"bin\":\"{BIN}\",\"family\":\"{FAMILY}\",\"version\":\"{}\",\"wired\":false}}",
        version.replace('"', "'")
    );
    let app = axum::Router::new()
        .route(
            "/health",
            axum::routing::get(move || {
                let body = health_body.clone();
                async move { ([(axum::http::header::CONTENT_TYPE, "application/json")], body) }
            }),
        )
        .route("/ping", axum::routing::get(|| async { "ok" }));

    let port = std::env::var("PORT").unwrap_or_else(|_| "8080".into());
    let addr = format!("0.0.0.0:{port}");
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .unwrap_or_else(|e| panic!("{BIN}: failed to bind {addr}: {e}"));
    println!("{BIN} listening on {addr}");
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await
        .expect("server error");
    println!("{BIN}: drained -- bye");
}

/// Resolve on Ctrl-C or SIGTERM (Kubernetes sends SIGTERM on every Recreate rollout) so
/// in-flight probe requests drain instead of RSTing mid-deploy.
async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c().await.expect("install Ctrl-C handler");
    };
    #[cfg(unix)]
    let terminate = async {
        use tokio::signal::unix::{signal, SignalKind};
        signal(SignalKind::terminate()).expect("install SIGTERM handler").recv().await;
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();
    tokio::select! {
        _ = ctrl_c => {},
        _ = terminate => {},
    }
    println!("{BIN}: shutdown signal received -- draining");
}
