// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260807-183024 step 3, #382).

//! `graphql-customer` — GraphQL subgraph for the `customer` scope -- one domain, one graph, one GRANT (D8).
//!
//! SKELETON (gate-then-stabilize): this bin exists so the deploy topology is buildable and its
//! scope containment is compiler-checked; the monolith `server` bin remains the deployed
//! production runtime until #349 (manifests/images emitter) and #358 (MKS cutover) flip
//! deployment as their own recorded steps.

// The manifest is the scope assertion; these imports make each declared domain-crate
// link a compile-checked fact (the linker cannot silently strip it).
use domain_customer as _;

/// The c4-l2 container this binary realizes.
const BIN: &str = "graphql-customer";
/// The bin's family in the deploy topology.
const FAMILY: &str = "subgraph";

fn main() {
    println!(
        "{BIN} ({FAMILY}): bin skeleton (ADR-20260807-183024 step 3) — runtime wiring lands \
         with #349/#358; the monolith server remains the deployed runtime."
    );
}
