// GENERATED by the Captain.Food codegen from specs/network/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// No restaurant account with this id (e.g. registering a location under a missing account).
/// Context: `restaurantAccountId`.
pub const RESTAURANT_ACCOUNT_NOT_FOUND: ErrorDef = ErrorDef {
    code: "RestaurantAccountNotFound",
    message_en: "Restaurant account not found.",
    message_fr: "Compte restaurant introuvable.",
};

/// Another restaurant already holds this slug. Includes a label a restaurant RELEASED by renaming: released labels stay reserved so their 301 redirect cannot be hijacked (ADR-20260728-011344).
/// Context: `slug`.
pub const SLUG_ALREADY_TAKEN: ErrorDef = ErrorDef {
    code: "SlugAlreadyTaken",
    message_en: "The address '{slug}' is already taken.",
    message_fr: "L'adresse '{slug}' est déjà utilisée.",
};

/// The restaurant has no storefront address yet, so it cannot be activated — customers would have no host to reach it on (ADR-20260728-011344). Aggregate-local: the fold sees whether RestaurantSlugConfigured ever landed, so no read model is consulted.
/// Context: `restaurantId`.
pub const SLUG_NOT_CONFIGURED: ErrorDef = ErrorDef {
    code: "SlugNotConfigured",
    message_en: "Choose your storefront address before going live.",
    message_fr: "Choisissez l'adresse de votre boutique avant la mise en ligne.",
};

/// The external reference (idempotent import key) is already owned by another aggregate.
/// Context: `ref`.
pub const REF_ALREADY_USED: ErrorDef = ErrorDef {
    code: "RefAlreadyUsed",
    message_en: "The reference '{ref}' is already in use.",
    message_fr: "La référence '{ref}' est déjà utilisée.",
};

/// Currency is not a valid ISO 4217 code.
/// Context: `currency`.
pub const INVALID_CURRENCY: ErrorDef = ErrorDef {
    code: "InvalidCurrency",
    message_en: "'{currency}' is not a valid currency.",
    message_fr: "'{currency}' n'est pas une devise valide.",
};

/// Operation requires an ACTIVE restaurant.
/// Context: `restaurantId`, `restaurantName`.
pub const RESTAURANT_NOT_ACTIVE: ErrorDef = ErrorDef {
    code: "RestaurantNotActive",
    message_en: "The restaurant '{restaurantName}' is not active.",
    message_fr: "Le restaurant '{restaurantName}' n'est pas actif.",
};

/// Activation requires at least one catalog with one orderable offer.
/// Context: `restaurantId`, `restaurantName`.
pub const RESTAURANT_NOT_READY_FOR_ACTIVATION: ErrorDef = ErrorDef {
    code: "RestaurantNotReadyForActivation",
    message_en: "Add at least one orderable product before activating '{restaurantName}'.",
    message_fr: "Ajoutez au moins un produit commandable avant d'activer '{restaurantName}'.",
};

/// Requested acceptance mode equals the current one.
/// Context: `restaurantId`, `restaurantName`, `mode`.
pub const ACCEPTANCE_MODE_UNCHANGED: ErrorDef = ErrorDef {
    code: "AcceptanceModeUnchanged",
    message_en: "'{restaurantName}' is already in '{mode}' mode.",
    message_fr: "'{restaurantName}' est déjà en mode '{mode}'.",
};

/// The restaurant listing has already been claimed by an owner.
/// Context: `restaurantId`.
pub const LISTING_ALREADY_CLAIMED: ErrorDef = ErrorDef {
    code: "ListingAlreadyClaimed",
    message_en: "This restaurant listing has already been claimed.",
    message_fr: "Cette fiche restaurant a déjà été revendiquée.",
};

/// Could not verify ownership of the listing (Google Business Profile proof rejected).
/// Context: `restaurantId`.
pub const LISTING_OWNERSHIP_NOT_VERIFIED: ErrorDef = ErrorDef {
    code: "ListingOwnershipNotVerified",
    message_en: "We couldn't verify that you own this restaurant. Please confirm via your Google Business Profile.",
    message_fr: "Nous n'avons pas pu vérifier que ce restaurant vous appartient. Confirmez via votre fiche Google Business Profile.",
};

/// No Google Business Profile 'Order online' link is configured to verify.
/// Context: `restaurantId`.
pub const GBP_ORDER_LINK_NOT_CONFIGURED: ErrorDef = ErrorDef {
    code: "GbpOrderLinkNotConfigured",
    message_en: "Configure the Google 'Order online' link before verifying it.",
    message_fr: "Configurez le lien Google « Commander en ligne » avant de le vérifier.",
};

/// The prospect already received the maximum number of outreach contacts (anti-spam: ≤ 3).
/// Context: `restaurantId`.
pub const PROSPECT_CONTACT_LIMIT_REACHED: ErrorDef = ErrorDef {
    code: "ProspectContactLimitReached",
    message_en: "This prospect has already been contacted the maximum number of times.",
    message_fr: "Ce prospect a déjà été contacté le nombre maximum de fois.",
};

/// A new contact is too soon after the previous one (anti-spam: ≥ 7 days apart).
/// Context: `restaurantId`.
pub const PROSPECT_CONTACTED_TOO_RECENTLY: ErrorDef = ErrorDef {
    code: "ProspectContactedTooRecently",
    message_en: "This prospect was contacted too recently; wait before contacting again.",
    message_fr: "Ce prospect a été contacté trop récemment ; patientez avant de le recontacter.",
};

/// No prospect (contact history) exists for this restaurant.
/// Context: `restaurantId`.
pub const PROSPECT_NOT_FOUND: ErrorDef = ErrorDef {
    code: "ProspectNotFound",
    message_en: "Prospect not found.",
    message_fr: "Prospect introuvable.",
};

/// The grant door is closed by `configuration.yaml#/keys/RUN_MEMBER_ACCESS_GRANT` (#639 part C step 6-i, ADR-20260905-101349 §6) -- a declared, supervisable refusal while the preconditions (`docs/decisions/MEMBER-ACCESS-GRANT-PRECONDITIONS.yaml`) are open, never a silent no-op. The first hand-provisioned grant about a real Tours human is the irreversible moment that starts every legal clock, so the store is never touched while this is off.
/// Context: `scopeId`.
pub const MEMBER_ACCESS_GRANT_DOOR_CLOSED: ErrorDef = ErrorDef {
    code: "MemberAccessGrantDoorClosed",
    message_en: "Granting restaurant access is not yet enabled in this environment.",
    message_fr: "L'octroi d'accès restaurant n'est pas encore activé dans cet environnement.",
};

/// `GrantRestaurantAccess.basis` named a declared but not-yet-implemented door (#639 part C step 6-i, ADR-20260905-101349 §3): only `CAPTAIN_ONBOARDING` is accepted today. `GOOGLE_BUSINESS_PROFILE`, `OWNER_DECLARATION` and `MEMBER_INVITATION` are named in the closed `AccessBasis` set so the vocabulary does not widen a second time when each door lands, but none of the three has a handler yet.
/// Context: `basis`.
pub const ACCESS_BASIS_NOT_YET_ACCEPTED: ErrorDef = ErrorDef {
    code: "AccessBasisNotYetAccepted",
    message_en: "This access basis is not yet supported.",
    message_fr: "Ce fondement d'accès n'est pas encore pris en charge.",
};

/// The login credential (`authSubject`) is already bound to ANOTHER member id: the write-side reservation `(MEMBER, authSubject)` in `database/tables/reservations.yaml#/ auth_subject_reservations` lost its insert to a row held by a different principal (#639 part C step 6-i, ADR-20260905-101349 §4). The binding is never released by a revoke, so the remedy is to grant the EXISTING member id, never a new one.
/// Context: `authSubject`.
pub const MEMBER_AUTH_SUBJECT_ALREADY_BOUND: ErrorDef = ErrorDef {
    code: "MemberAuthSubjectAlreadyBound",
    message_en: "This login is already linked to a restaurant member. Grant the existing member instead.",
    message_fr: "Cette identité de connexion est déjà liée à un membre. Accordez l'accès au membre existant.",
};

/// No `RestaurantMembership` exists for this `membershipId` (#639 part C step 6-i).
/// Context: `membershipId`.
pub const RESTAURANT_MEMBERSHIP_NOT_FOUND: ErrorDef = ErrorDef {
    code: "RestaurantMembershipNotFound",
    message_en: "This restaurant membership was not found.",
    message_fr: "Cette adhésion restaurant est introuvable.",
};

/// The `RestaurantMembership` was already revoked (#639 part C step 6-i) -- revocation is a fact that happens once; a second `RevokeRestaurantAccess` on the same `membershipId` is rejected rather than silently re-recorded (the Art. 11-log style: the log is never overwritten).
/// Context: `membershipId`.
pub const RESTAURANT_MEMBERSHIP_ALREADY_REVOKED: ErrorDef = ErrorDef {
    code: "RestaurantMembershipAlreadyRevoked",
    message_en: "This restaurant membership was already revoked.",
    message_fr: "Cette adhésion restaurant a déjà été révoquée.",
};

/// The magic-link token verified (the email is genuinely proven), but no `Member` row exists for this auth subject in `Member.auth_subject` (the step-6-i bridge) -- the not-yet-linked refusal (PROP-20260831-180622 §8.5, the rider door's `RiderNotRegistered` precedent). NOTHING is stamped and NOTHING is created; the session is still parked so the refusal screen can offer "Se déconnecter" against a real cookie. `email` carries the VERIFIED address (the token's output, never client input) so the refusal screen can print it.
/// Context: `email`, `supportContact`.
pub const MEMBER_NOT_LINKED: ErrorDef = ErrorDef {
    code: "MemberNotLinked",
    message_en: "Your account is not yet linked to a restaurant. Write to {supportContact}.",
    message_fr: "Votre compte n'est pas encore relié à un restaurant. Écrivez-nous à {supportContact}.",
};

/// The sign-in confirmation arrived with no `X-SESSION-ID` (the rider door's #852 B1 precedent). The credential it would mint is parked for `POST /auth/session` under the OWNING anonymous session (envelope data, ADR-0041), and a session parked with no owner could be claimed by any header-less caller holding the acceptance messageId. So the door refuses BEFORE the token is spent (the link stays usable for a correct retry) and nothing is verified, stamped or parked. Carries nothing: the remedy is the client's (the SDUI client always sends the header, so a restaurateur never sees this).
pub const MEMBER_SIGN_IN_REQUIRES_SESSION: ErrorDef = ErrorDef {
    code: "MemberSignInRequiresSession",
    message_en: "Sign-in needs a browser session. Reload the page and try again.",
    message_fr: "La connexion nécessite une session de navigation. Rechargez la page et réessayez.",
};

/// `RUN_MEMBER_SIGN_IN_DOOR` is OFF (`configuration.yaml`, default false) -- the member sign-in door refuses BEFORE touching the identity provider (ADR-20260905-101349 §6/§F): the writer key flips only after the preconditions in `decisions/MEMBER-SIGN-IN-DOOR-PRECONDITIONS.yaml` are met.
pub const MEMBER_SIGN_IN_DOOR_CLOSED: ErrorDef = ErrorDef {
    code: "MemberSignInDoorClosed",
    message_en: "Restaurant sign-in is not yet available.",
    message_fr: "La connexion restaurateur n'est pas encore disponible.",
};
