// GENERATED by the Captain.Food codegen from specs/network/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// No restaurant account with this id (e.g. registering a location under a missing account).
/// Context: `restaurantAccountId`.
pub const RESTAURANT_ACCOUNT_NOT_FOUND: ErrorDef = ErrorDef {
    code: "RestaurantAccountNotFound",
    message_en: "Restaurant account not found.",
    message_fr: "Compte restaurant introuvable.",
};

/// Another restaurant already holds this slug. Includes a label a restaurant RELEASED by renaming: released labels stay reserved so their 301 redirect cannot be hijacked (ADR-20260728-011344).
/// Context: `slug`.
pub const SLUG_ALREADY_TAKEN: ErrorDef = ErrorDef {
    code: "SlugAlreadyTaken",
    message_en: "The address '{slug}' is already taken.",
    message_fr: "L'adresse '{slug}' est déjà utilisée.",
};

/// The restaurant has no storefront address yet, so it cannot be activated — customers would have no host to reach it on (ADR-20260728-011344). Aggregate-local: the fold sees whether RestaurantSlugConfigured ever landed, so no read model is consulted.
/// Context: `restaurantId`.
pub const SLUG_NOT_CONFIGURED: ErrorDef = ErrorDef {
    code: "SlugNotConfigured",
    message_en: "Choose your storefront address before going live.",
    message_fr: "Choisissez l'adresse de votre boutique avant la mise en ligne.",
};

/// The external reference (idempotent import key) is already owned by another aggregate.
/// Context: `ref`.
pub const REF_ALREADY_USED: ErrorDef = ErrorDef {
    code: "RefAlreadyUsed",
    message_en: "The reference '{ref}' is already in use.",
    message_fr: "La référence '{ref}' est déjà utilisée.",
};

/// Currency is not a valid ISO 4217 code.
/// Context: `currency`.
pub const INVALID_CURRENCY: ErrorDef = ErrorDef {
    code: "InvalidCurrency",
    message_en: "'{currency}' is not a valid currency.",
    message_fr: "'{currency}' n'est pas une devise valide.",
};

/// Operation requires an ACTIVE restaurant.
/// Context: `restaurantId`, `restaurantName`.
pub const RESTAURANT_NOT_ACTIVE: ErrorDef = ErrorDef {
    code: "RestaurantNotActive",
    message_en: "The restaurant '{restaurantName}' is not active.",
    message_fr: "Le restaurant '{restaurantName}' n'est pas actif.",
};

/// Activation requires at least one catalog with one orderable offer.
/// Context: `restaurantId`, `restaurantName`.
pub const RESTAURANT_NOT_READY_FOR_ACTIVATION: ErrorDef = ErrorDef {
    code: "RestaurantNotReadyForActivation",
    message_en: "Add at least one orderable product before activating '{restaurantName}'.",
    message_fr: "Ajoutez au moins un produit commandable avant d'activer '{restaurantName}'.",
};

/// Requested acceptance mode equals the current one.
/// Context: `restaurantId`, `restaurantName`, `mode`.
pub const ACCEPTANCE_MODE_UNCHANGED: ErrorDef = ErrorDef {
    code: "AcceptanceModeUnchanged",
    message_en: "'{restaurantName}' is already in '{mode}' mode.",
    message_fr: "'{restaurantName}' est déjà en mode '{mode}'.",
};

/// The restaurant listing has already been claimed by an owner.
/// Context: `restaurantId`.
pub const LISTING_ALREADY_CLAIMED: ErrorDef = ErrorDef {
    code: "ListingAlreadyClaimed",
    message_en: "This restaurant listing has already been claimed.",
    message_fr: "Cette fiche restaurant a déjà été revendiquée.",
};

/// Could not verify ownership of the listing (Google Business Profile proof rejected).
/// Context: `restaurantId`.
pub const LISTING_OWNERSHIP_NOT_VERIFIED: ErrorDef = ErrorDef {
    code: "ListingOwnershipNotVerified",
    message_en: "We couldn't verify that you own this restaurant. Please confirm via your Google Business Profile.",
    message_fr: "Nous n'avons pas pu vérifier que ce restaurant vous appartient. Confirmez via votre fiche Google Business Profile.",
};

/// No Google Business Profile 'Order online' link is configured to verify.
/// Context: `restaurantId`.
pub const GBP_ORDER_LINK_NOT_CONFIGURED: ErrorDef = ErrorDef {
    code: "GbpOrderLinkNotConfigured",
    message_en: "Configure the Google 'Order online' link before verifying it.",
    message_fr: "Configurez le lien Google « Commander en ligne » avant de le vérifier.",
};

/// The prospect already received the maximum number of outreach contacts (anti-spam: ≤ 3).
/// Context: `restaurantId`.
pub const PROSPECT_CONTACT_LIMIT_REACHED: ErrorDef = ErrorDef {
    code: "ProspectContactLimitReached",
    message_en: "This prospect has already been contacted the maximum number of times.",
    message_fr: "Ce prospect a déjà été contacté le nombre maximum de fois.",
};

/// A new contact is too soon after the previous one (anti-spam: ≥ 7 days apart).
/// Context: `restaurantId`.
pub const PROSPECT_CONTACTED_TOO_RECENTLY: ErrorDef = ErrorDef {
    code: "ProspectContactedTooRecently",
    message_en: "This prospect was contacted too recently; wait before contacting again.",
    message_fr: "Ce prospect a été contacté trop récemment ; patientez avant de le recontacter.",
};

/// No prospect (contact history) exists for this restaurant.
/// Context: `restaurantId`.
pub const PROSPECT_NOT_FOUND: ErrorDef = ErrorDef {
    code: "ProspectNotFound",
    message_en: "Prospect not found.",
    message_fr: "Prospect introuvable.",
};
