// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260807-183024 step 3, #382).

//! `bo-rider` — surface bin -- assets/SSR/webhooks; speaks to its role gateway, holds no domain vocabulary and no broad views access.
//!
//! SKELETON (gate-then-stabilize): this bin exists so the deploy topology is buildable and its
//! scope containment is compiler-checked; the monolith `server` bin remains the deployed
//! production runtime until #349 (manifests/images emitter) and #358 (MKS cutover) flip
//! deployment as their own recorded steps.

/// The c4-l2 container this binary realizes.
const BIN: &str = "bo-rider";
/// The bin's family in the deploy topology.
const FAMILY: &str = "surface";

fn main() {
    println!(
        "{BIN} ({FAMILY}): bin skeleton (ADR-20260807-183024 step 3) — runtime wiring lands \
         with #349/#358; the monolith server remains the deployed runtime."
    );
}
