// GENERATED by the Captain.Food codegen from specs/comms/commands.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use serde::{Deserialize, Serialize};
use crate::scalars::*;
use domain_common::scalars::*;

/// Open the in-app conversation for an order (id = orderId; idempotent birth). Snapshots whether customer<->restaurant direct chat is enabled (default true). orderId is the client-generated, idempotent key.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenConversation {
    pub order_id: OrderId,
    pub restaurant_id: RestaurantId,
    pub customer_id: Option<CustomerId>,
    pub customer_chat_enabled: bool,
}

/// Post a message to an order's conversation — PUBLIC (customer-visible) or INTERNAL (staff-only note). The client-generated messageId is the idempotency key (a re-post with the same id is rejected).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostMessage {
    pub order_id: OrderId,
    pub message_id: ConversationMessageId,
    pub author_role: ConversationAuthorRole,
    pub visibility: MessageVisibility,
    pub body: MessageBody,
    pub original_locale: Locale,
    #[serde(default)]
    pub attachment_refs: Vec<AttachmentRef>,
}

/// Record (cache) a translation of a posted message into a target locale; idempotent per (message, locale). The conversation and the message must exist. Translate once, reuse (#129).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecordMessageTranslation {
    pub order_id: OrderId,
    pub message_id: ConversationMessageId,
    pub locale: Locale,
    pub text: TranslatedText,
}

/// Pull an admin into an order's conversation through a reasoned escalation (restaurant or rider). The conversation must exist. Emits AdminInvitedToConversation (#129).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EscalateToAdmin {
    pub order_id: OrderId,
    pub reason: EscalationReason,
}

/// Mute a participant role in an order's conversation. A justification `reason` is REQUIRED, but is left OUT of `required` on purpose: the "justified" invariant is enforced by the write model as an anticipated error (errors.yaml#/MuteReasonRequired), not by the schema. `until` bounds the mute in time; absent = indefinite. The conversation must exist (#129).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MuteParticipant {
    pub order_id: OrderId,
    pub muted_role: ConversationAuthorRole,
    pub reason: Option<MuteReason>,
    pub until: Option<String>,
}

/// Unmute a previously muted participant role in an order's conversation. The conversation must exist and the role must currently be muted (errors.yaml#/ParticipantNotMuted) (#129).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmuteParticipant {
    pub order_id: OrderId,
    pub muted_role: ConversationAuthorRole,
}
