// GENERATED by the Captain.Food codegen from specs/comms/errors.yaml — do not edit by hand
// (#373, ADR-20260807-183024 step 2). This scope's items only; the `domain` facade re-exports
// them so `domain::generated::*` paths keep resolving with the SAME type identity.

use domain_common::errors::ErrorDef;

/// OpenConversation targeted an order whose conversation already exists (id = orderId). The birth is idempotent-guarded, so a second open is rejected (#129).
/// Context: `orderId`.
pub const CONVERSATION_ALREADY_OPEN: ErrorDef = ErrorDef {
    code: "ConversationAlreadyOpen",
    message_en: "A conversation is already open for this order.",
    message_fr: "Une conversation est déjà ouverte pour cette commande.",
};

/// PostMessage targeted an order whose conversation was never opened; a message cannot be posted before the conversation exists (#129).
/// Context: `orderId`.
pub const CONVERSATION_NOT_FOUND: ErrorDef = ErrorDef {
    code: "ConversationNotFound",
    message_en: "No conversation exists for this order.",
    message_fr: "Aucune conversation n'existe pour cette commande.",
};

/// The acting principal is not a participant of the aggregate instance it tried to write to — the aggregate's own folded state names its participants and the caller is not among them (write-side per-instance authorization, #235 / PROP-20260728-135632 requires.acting). The instance's existence is NOT disclosed beyond this rejection.
/// Context: `orderId`.
pub const NOT_A_PARTICIPANT: ErrorDef = ErrorDef {
    code: "NotAParticipant",
    message_en: "You are not a participant in this conversation.",
    message_fr: "Vous ne participez pas à cette conversation.",
};

/// The role claimed in the payload does not match the verified acting principal — e.g. a CUSTOMER posting authorRole RESTAURANT to forge a staff note (write-side anti-forgery, #235 / PROP-20260728-135632 requires.claims).
/// Context: `orderId`.
pub const ROLE_MISMATCH: ErrorDef = ErrorDef {
    code: "RoleMismatch",
    message_en: "The author role does not match your account.",
    message_fr: "Le rôle d'auteur ne correspond pas à votre compte.",
};

/// A CUSTOMER-authored message was posted to an order whose restaurant disabled customer chat; only staff may post on that thread (#129).
/// Context: `orderId`.
pub const CUSTOMER_CHAT_DISABLED: ErrorDef = ErrorDef {
    code: "CustomerChatDisabled",
    message_en: "Customer messaging is disabled for this order.",
    message_fr: "La messagerie client est désactivée pour cette commande.",
};

/// A message with this client-generated messageId was already posted to the conversation; the re-post is a duplicate and is rejected (idempotency; #129).
/// Context: `messageId`.
pub const MESSAGE_ALREADY_POSTED: ErrorDef = ErrorDef {
    code: "MessageAlreadyPosted",
    message_en: "This message has already been posted.",
    message_fr: "Ce message a déjà été envoyé.",
};

/// A translation targeted a message that was never posted to the conversation; a translation can only be recorded for an actually-posted message (rules.yaml#/TranslationTargetsAPostedMessage) (#129).
/// Context: `orderId`, `messageId`.
pub const MESSAGE_NOT_FOUND_IN_CONVERSATION: ErrorDef = ErrorDef {
    code: "MessageNotFoundInConversation",
    message_en: "No such message exists in this conversation.",
    message_fr: "Ce message n'existe pas dans cette conversation.",
};

/// A translation for this message and target locale is already cached; the re-record is idempotent and rejected (translate once, reuse; rules.yaml#/TranslationsAreCachedOncePerLocale) (#129).
/// Context: `orderId`, `messageId`, `locale`.
pub const TRANSLATION_ALREADY_RECORDED: ErrorDef = ErrorDef {
    code: "TranslationAlreadyRecorded",
    message_en: "This message is already translated into this language.",
    message_fr: "Ce message est déjà traduit dans cette langue.",
};

/// A participant was muted without a justification reason; a mute must record why (rules.yaml#/MuteRequiresAReason) (#129).
/// Context: `orderId`.
pub const MUTE_REASON_REQUIRED: ErrorDef = ErrorDef {
    code: "MuteReasonRequired",
    message_en: "A reason is required to mute a participant.",
    message_fr: "Un motif est requis pour rendre un participant muet.",
};

/// An unmute targeted a role that is not currently muted in the order's conversation (rules.yaml#/OnlyMutedParticipantsCanBeUnmuted) (#129).
/// Context: `orderId`, `mutedRole`.
pub const PARTICIPANT_NOT_MUTED: ErrorDef = ErrorDef {
    code: "ParticipantNotMuted",
    message_en: "This participant is not currently muted.",
    message_fr: "Ce participant n'est pas actuellement muet.",
};
