// GENERATED by the Captain.Food codegen from specs/actors.yaml (`receives` +
// `mailbox.partitions` + `reminders`) -- do not edit by hand (PROP-20260802-130500 phase 2,
// #306). The typed mailbox client for ONE actor, in its OWN crate: depending on this crate is the
// permission to address `Order`, and nothing else.
//
// The client constructs NOTHING itself. Every row is assembled behind `actor_client::ActorDoor`,
// whose delegates own the lane, partition, principal and channel derivation -- so a typed send
// here and the string-keyed reference implementation in `actor_client` cannot drift (the
// out-of-crate drift guard in `crates/actor_client/tests/drift_guard.rs` proves it field for
// field). `MailboxEntry` and `MailboxAccess` are not nameable from this crate at all.
//
// EVERY method is spec-gated (product-owner directive, 2026-08-02 -- the declaration is the
// permission): `send` + `OrderCommand` exist iff the actor receives >=1 COMMAND, `record` +
// `OrderFact` iff it receives >=1 inbound FACT, `schedule`/`cancel_scheduling` iff it declares
// `reminders:`. An unjustified surface is ABSENT -- a compile error at any call site -- never
// uncallable-but-present.

use std::sync::Arc;

use actor_client::mailbox::{Envelope, Mailbox};
use actor_client::{ActorDoor, EnqueueOutcome, ScheduleOutcome};
use domain::shared::errors::DomainError;

/// The privacy SEAL: `Sealed` lives in a private module, so it cannot be named -- let alone
/// implemented -- outside this GENERATED crate. Every marker trait below requires it, so the
/// receive set this actor declares in actors.yaml is the receive set, period: widening it takes a
/// spec change and a regeneration, never a stray downstream `impl`. Since phase 2 each actor owns
/// its own seal, so a sibling client crate cannot even name this actor's marker supertrait.
mod sealed {
    pub trait Sealed {}
}

impl sealed::Sealed for domain::generated::commands::AcceptOrder {}
impl sealed::Sealed for domain::generated::commands::CancelOrderByCustomer {}
impl sealed::Sealed for domain::generated::commands::CancelOrderByRestaurant {}
impl sealed::Sealed for domain::generated::commands::MarkOrderDelivered {}
impl sealed::Sealed for domain::generated::commands::MarkOrderReady {}
impl sealed::Sealed for domain::generated::commands::PlaceReplacementOrder {}
impl sealed::Sealed for domain::generated::commands::RateOrder {}
impl sealed::Sealed for domain::generated::commands::RateRestaurant {}
impl sealed::Sealed for domain::generated::commands::RecordDeliverySatisfaction {}
impl sealed::Sealed for domain::generated::commands::RejectOrder {}
impl sealed::Sealed for domain::generated::commands::RequestRefund {}
impl sealed::Sealed for domain::generated::commands::StartPreparation {}
impl sealed::Sealed for domain::generated::commands::TipOrder {}
impl sealed::Sealed for domain::generated::events::OrderPlaced {}
impl sealed::Sealed for domain::generated::answers::OrderPaymentReferenceRequest {}

/// GENERATED from actors.yaml `Order.receives`: marker for every COMMAND the `Order` actor
/// receives. SEALED (private supertrait) so no impl can exist outside this generated crate --
/// sending a command this actor does not `receive` is a COMPILE error, not a runtime rejection.
pub trait OrderCommand: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the commands.yaml key).
    const MESSAGE_TYPE: &'static str;
}

impl OrderCommand for domain::generated::commands::AcceptOrder {
    const MESSAGE_TYPE: &'static str = "AcceptOrder";
}

impl OrderCommand for domain::generated::commands::CancelOrderByCustomer {
    const MESSAGE_TYPE: &'static str = "CancelOrderByCustomer";
}

impl OrderCommand for domain::generated::commands::CancelOrderByRestaurant {
    const MESSAGE_TYPE: &'static str = "CancelOrderByRestaurant";
}

impl OrderCommand for domain::generated::commands::MarkOrderDelivered {
    const MESSAGE_TYPE: &'static str = "MarkOrderDelivered";
}

impl OrderCommand for domain::generated::commands::MarkOrderReady {
    const MESSAGE_TYPE: &'static str = "MarkOrderReady";
}

impl OrderCommand for domain::generated::commands::PlaceReplacementOrder {
    const MESSAGE_TYPE: &'static str = "PlaceReplacementOrder";
}

impl OrderCommand for domain::generated::commands::RateOrder {
    const MESSAGE_TYPE: &'static str = "RateOrder";
}

impl OrderCommand for domain::generated::commands::RateRestaurant {
    const MESSAGE_TYPE: &'static str = "RateRestaurant";
}

impl OrderCommand for domain::generated::commands::RecordDeliverySatisfaction {
    const MESSAGE_TYPE: &'static str = "RecordDeliverySatisfaction";
}

impl OrderCommand for domain::generated::commands::RejectOrder {
    const MESSAGE_TYPE: &'static str = "RejectOrder";
}

impl OrderCommand for domain::generated::commands::RequestRefund {
    const MESSAGE_TYPE: &'static str = "RequestRefund";
}

impl OrderCommand for domain::generated::commands::StartPreparation {
    const MESSAGE_TYPE: &'static str = "StartPreparation";
}

impl OrderCommand for domain::generated::commands::TipOrder {
    const MESSAGE_TYPE: &'static str = "TipOrder";
}

/// GENERATED from actors.yaml `Order.receives`: marker for every inbound FACT (an
/// `events.yaml#/...` ref -- an external fact that already happened) the `Order` actor records.
/// SEALED for the same reason as [`OrderCommand`].
pub trait OrderFact: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the events.yaml key) -- also the `DomainEvent` adjacent tag.
    const EVENT_TYPE: &'static str;
    /// The fact wrapped in ITS `DomainEvent` variant -- so the adjacently-tagged wire form comes
    /// from the domain enum's own serde representation, never from a hand-built literal that
    /// could drift from it.
    fn into_domain_event(self) -> domain::generated::events::DomainEvent;
}

impl OrderFact for domain::generated::events::OrderPlaced {
    const EVENT_TYPE: &'static str = "OrderPlaced";
    fn into_domain_event(self) -> domain::generated::events::DomainEvent {
        domain::generated::events::DomainEvent::OrderPlaced(self)
    }
}

/// GENERATED from actors.yaml `Order.answers` (PROP-20260815-142349 s7, #582): marker for
/// every ask this actor ANSWERS -- the declaration is the permission, so this trait (and the
/// `ask` method) exist iff the spec declares `answers:`, and are ABSENT otherwise. SEALED like
/// the send/record traits: the answer set is the answer set, period. `Reply` carries
/// UNCONDITIONAL serde -- the wire shape may not rot while the ask is local -- and the reader
/// is TOLERANT (additive-only producer / tolerant reader; a breaking reshape takes a NEW
/// answer name).
pub trait OrderAnswer: sealed::Sealed {
    /// The declared operation address -- the ref path IS the whole address (the actor is
    /// encoded in it, never restated).
    const QUERY_TYPE: &'static str;
    type Reply: serde::Serialize + serde::de::DeserializeOwned + Send;
    /// The answering instance's stream -- the identity IS the argument (PROP s3).
    fn stream_name(&self) -> String;
    /// Project the declared reply properties off the actor's own fold state. THE compiled
    /// YAML-state <-> hand-fold parity proof: rename a fold field and this stops building.
    fn project(state: &domain::order::OrderState) -> Self::Reply;
}

impl OrderAnswer for domain::generated::answers::OrderPaymentReferenceRequest {
    const QUERY_TYPE: &'static str = "actors.yaml#/Order/answers/paymentReference";
    type Reply = domain::generated::answers::OrderPaymentReferenceReply;
    fn stream_name(&self) -> String {
        format!("Order-{}", self.order_id.0)
    }
    fn project(state: &domain::order::OrderState) -> Self::Reply {
        domain::generated::answers::OrderPaymentReferenceReply {
            payment_intent_id: state.payment_intent_id.clone(),
        }
    }
}

/// GENERATED from actors.yaml: the strongly-typed client for ONE `Order` mailbox lane --
/// `actor_id` is the addressed instance, the partition is the FROZEN `stable_partition` over
/// width 5 (`mailbox.partitions`). The only door to this actor.
pub struct OrderClient {
    door: ActorDoor,
    actor_id: uuid::Uuid,
}

impl OrderClient {
    /// A client addressing the `Order` instance `actor_id`.
    pub fn new(mailbox: Arc<dyn Mailbox>, actor_id: uuid::Uuid) -> Self {
        Self { door: ActorDoor::new(mailbox), actor_id }
    }

    /// Enqueue one typed COMMAND on this lane (kind COMMAND). Delegates to the door's
    /// `send_command`, which builds the row with the shared `command_entry` constructor -- the
    /// very row `enqueue_worker_command` builds for the same inputs, field for field.
    pub async fn send<M: OrderCommand>(
        &self,
        msg: M,
        env: Envelope,
    ) -> Result<EnqueueOutcome, DomainError> {
        let payload = serde_json::to_value(&msg)
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", M::MESSAGE_TYPE)))?;
        self.door.assert_addressed("OrderClient", self.actor_id, M::MESSAGE_TYPE, &payload)?;
        self.door
            .send_command("Order", 5, self.actor_id, M::MESSAGE_TYPE, payload, env)
            .await
    }

    /// Record one inbound FACT (kind EVENT, channel EXTERNAL, adjacently-tagged `DomainEvent`
    /// payload). `message_id` is ALWAYS the deterministic `inbound_message_id(source,
    /// external_id)` -- never caller-supplied -- and provenance is a REQUIRED parameter, because
    /// the `(source, external_id)` dedupe key is what makes redelivery safe. The acting principal
    /// is the per-source system user, stamped by the shared `inbound_entry` constructor.
    pub async fn record<F: OrderFact>(
        &self,
        fact: F,
        source: &str,
        external_id: &str,
        correlation_id: uuid::Uuid,
    ) -> Result<EnqueueOutcome, DomainError> {
        let tagged = serde_json::to_value(fact.into_domain_event())
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", F::EVENT_TYPE)))?;
        self.door
            .record_fact(
                "Order",
                self.actor_id,
                F::EVENT_TYPE,
                tagged,
                source,
                external_id,
                correlation_id,
            )
            .await
    }

    /// Schedule one typed COMMAND for LATER delivery: a SCHEDULED row (`position` NULL) the
    /// promotion pass delivers when due; a still-SCHEDULED identity reschedules IN PLACE
    /// (ADR-20260731-150500).
    pub async fn schedule<M: OrderCommand>(
        &self,
        msg: M,
        env: Envelope,
        at: chrono::DateTime<chrono::Utc>,
    ) -> Result<ScheduleOutcome, DomainError> {
        let payload = serde_json::to_value(&msg)
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", M::MESSAGE_TYPE)))?;
        self.door.assert_addressed("OrderClient", self.actor_id, M::MESSAGE_TYPE, &payload)?;
        self.door
            .schedule_command("Order", 5, self.actor_id, M::MESSAGE_TYPE, payload, env, at)
            .await
    }

    /// Withdraw a SCHEDULED reminder (`SCHEDULED -> CANCELLED`, ADR-20260731-150500 section 3).
    /// `false` = absent, delivered or already cancelled -- the caller decides whether losing that
    /// race matters. Named `cancel_scheduling` (product-owner decision 2026-08-02, #308): the name
    /// says exactly what it withdraws -- a scheduled reminder, never an in-flight command. Keyed
    /// by `message_id` like the port beneath it: the id is minted by `schedule`, so holding it IS
    /// the capability (decided over lane-scoping, #308).
    pub async fn cancel_scheduling(&self, message_id: uuid::Uuid) -> Result<bool, DomainError> {
        self.door.cancel_scheduling(message_id).await
    }

    /// Ask this actor for a DECLARED answer (PROP-20260815-142349 s7, #582) -- the LOCAL
    /// adapter: load the instance's stream through the EventStore PORT, fold with the actor's
    /// own hand fold, project the declared reply, envelope with the fold's version. `Absent`
    /// (no birth event on the stream) and `Deadline` (the CALLER's deadline elapsed -- the
    /// deadline lives on the call site, never on this actor, D5) are Ok-channel arms the
    /// caller must match exhaustively; `Err` stays reserved for infrastructure failure. The
    /// reply's authority EXPIRES AT SEND: a fold gives freshness, not atomicity (CHK-1).
    pub async fn ask<Q: OrderAnswer>(
        &self,
        q: Q,
        store: &dyn application::ports::EventStore,
        deadline: std::time::Duration,
    ) -> Result<actor_client::ask::AskOutcome<Q::Reply>, DomainError> {
        actor_client::ask::ask_local(store, &q.stream_name(), deadline, domain::order::fold, Q::project)
            .await
    }
}
