//! Emit `crates/infrastructure/src/generated/actor_clients.rs` — one strongly-typed client per
//! mailbox actor (#284 slice 1, PROP-20260728-152752 §2.1): the ONLY typed door to the
//! `inbound_messages` mailbox. Per-actor SEALED marker traits make "send a message the actor does
//! not `receive`" a COMPILE error, and every entry is assembled by the shared `pub(crate)`
//! constructors in `crate::mailbox::enqueue`, so the typed door and the free-function door can
//! never drift on lane, partition, principal or channel.

use crate::*;

/// One mailbox actor's typed surface, scanned from actors.yaml: its frozen partition width and its
/// `receives` split by ref kind — `commands.yaml#/…` → COMMAND, `events.yaml#/…` → inbound FACT
/// (the ref path encodes the kind, §1b).
struct ClientActor {
    name: String,
    width: u16,
    commands: Vec<String>,
    facts: Vec<String>,
}

/// Every actor with a declared mailbox, sorted by name (stable output), receives de-duplicated.
/// Skips the file-level `version`/`description` keys and the `principals` map like every other
/// actors.yaml consumer.
fn client_actors(model: &Model) -> Vec<ClientActor> {
    let mut out: Vec<ClientActor> = Vec::new();
    let Some(Value::Mapping(actors)) = model.defs.get("actors.yaml") else { return out };
    for (k, def) in actors {
        let Some(name) = k.as_str().filter(|s| *s != "principals") else { continue };
        if !matches!(def.get("type").and_then(|t| t.as_str()), Some("aggregate" | "process-manager"))
        {
            continue;
        }
        let Some(width) =
            def.get("mailbox").and_then(|m| m.get("partitions")).and_then(|p| p.as_u64())
        else {
            continue;
        };
        let mut commands: Vec<String> = Vec::new();
        let mut facts: Vec<String> = Vec::new();
        if let Some(receives) = def.get("receives").and_then(|r| r.as_sequence()) {
            for entry in receives {
                let Some(r) =
                    entry.get("message").and_then(|m| m.get("$ref")).and_then(|r| r.as_str())
                else {
                    continue;
                };
                if let Some(cmd) = r.strip_prefix("commands.yaml#/") {
                    if !commands.iter().any(|c| c == cmd) {
                        commands.push(cmd.to_string());
                    }
                } else if let Some(ev) = r.strip_prefix("events.yaml#/") {
                    if !facts.iter().any(|f| f == ev) {
                        facts.push(ev.to_string());
                    }
                }
            }
        }
        commands.sort();
        facts.sort();
        out.push(ClientActor { name: name.to_string(), width: width as u16, commands, facts });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

pub(crate) fn emit_infra_actor_clients(model: &Model) -> String {
    let actors = client_actors(model);
    let mut out = String::from(
        "// GENERATED by the Captain.Food codegen from specs/actors.yaml (`receives` + `mailbox.partitions`)\n// — do not edit by hand (#284 slice 1, PROP-20260728-152752 §2.1). One strongly-typed client per\n// mailbox actor: the ONLY typed door to the `inbound_messages` mailbox. The clients construct\n// NOTHING themselves — every entry is assembled by the shared pub(crate) constructors in\n// `crate::mailbox::enqueue`, so a typed send and a free-function enqueue can never drift on lane,\n// partition, principal or channel; this file only gathers typed inputs and delegates.\n\nuse std::sync::Arc;\n\nuse application::mailbox::{Envelope, Mailbox};\nuse domain::shared::errors::DomainError;\n\nuse crate::mailbox::enqueue::{command_entry, declared_identity, insert_mapped, schedule_mapped};\nuse crate::mailbox::{enqueue_inbound_fact, EnqueueOutcome, InboundFact, ScheduleOutcome};\n\n/// The privacy SEAL: `Sealed` lives in a private module, so it cannot be named — let alone\n/// implemented — outside this GENERATED file. Every `{Actor}Command`/`{Actor}Fact` marker trait\n/// requires it, so the receive set an actor declares in actors.yaml is the receive set, period:\n/// widening it takes a spec change and a regeneration, never a stray downstream `impl`.\nmod sealed {\n    pub trait Sealed {}\n}\n\n// One `Sealed` impl per DISTINCT message type (a fact received by several actors — the fan-out\n// kind — is sealed once and marked per actor below).\n",
    );
    let mut sealed: BTreeSet<String> = BTreeSet::new();
    for a in &actors {
        for c in &a.commands {
            sealed.insert(format!("domain::generated::commands::{c}"));
        }
        for f in &a.facts {
            sealed.insert(format!("domain::generated::events::{f}"));
        }
    }
    for path in &sealed {
        out.push_str(&format!("impl sealed::Sealed for {path} {{}}\n"));
    }
    for a in &actors {
        let actor = &a.name;
        let width = a.width;
        out.push_str(&format!(
            "\n// ─── {actor} ───\n\n/// GENERATED from actors.yaml `{actor}.receives`: marker for every COMMAND the `{actor}` actor\n/// receives. SEALED (private supertrait) so no impl can exist outside the generated file —\n/// sending a command this actor does not `receive` is a COMPILE error, not a runtime rejection.\npub trait {actor}Command: sealed::Sealed + serde::Serialize + Send {{\n    /// The mailbox `message_type` (the commands.yaml key).\n    const MESSAGE_TYPE: &'static str;\n}}\n"
        ));
        for c in &a.commands {
            out.push_str(&format!(
                "\nimpl {actor}Command for domain::generated::commands::{c} {{\n    const MESSAGE_TYPE: &'static str = \"{c}\";\n}}\n"
            ));
        }
        out.push_str(&format!(
            "\n/// GENERATED from actors.yaml `{actor}.receives`: marker for every inbound FACT (an\n/// `events.yaml#/…` ref — an external fact that already happened) the `{actor}` actor records.\n/// SEALED for the same reason as [`{actor}Command`].\npub trait {actor}Fact: sealed::Sealed + serde::Serialize + Send {{\n    /// The mailbox `message_type` (the events.yaml key) — also the `DomainEvent` adjacent tag.\n    const EVENT_TYPE: &'static str;\n    /// The fact wrapped in ITS `DomainEvent` variant — so the adjacently-tagged wire form comes\n    /// from the domain enum's own serde representation, never from a hand-built literal that\n    /// could drift from it.\n    fn into_domain_event(self) -> domain::generated::events::DomainEvent;\n}}\n"
        ));
        for f in &a.facts {
            out.push_str(&format!(
                "\nimpl {actor}Fact for domain::generated::events::{f} {{\n    const EVENT_TYPE: &'static str = \"{f}\";\n    fn into_domain_event(self) -> domain::generated::events::DomainEvent {{\n        domain::generated::events::DomainEvent::{f}(self)\n    }}\n}}\n"
            ));
        }
        out.push_str(&format!(
            "\n/// GENERATED from actors.yaml: the strongly-typed client for ONE `{actor}` mailbox lane —\n/// `actor_id` is the addressed instance, the partition is the FROZEN `stable_partition` over\n/// width {width} (`mailbox.partitions`). The only door non-GraphQL code should use to reach this\n/// actor (PROP-20260728-152752 §2.1).\npub struct {actor}Client {{\n    mailbox: Arc<dyn Mailbox>,\n    actor_id: uuid::Uuid,\n}}\n\nimpl {actor}Client {{\n    /// A client addressing the `{actor}` instance `actor_id`.\n    pub fn new(mailbox: Arc<dyn Mailbox>, actor_id: uuid::Uuid) -> Self {{\n        Self {{ mailbox, actor_id }}\n    }}\n\n    /// Enqueue one typed COMMAND on this lane (kind COMMAND). Delegates to the shared\n    /// `command_entry` constructor — the very row `enqueue_worker_command` builds for the same\n    /// inputs, field for field (the drift guard in `tests/actor_clients.rs` proves it).\n    pub async fn send<M: {actor}Command>(\n        &self,\n        msg: M,\n        env: Envelope,\n    ) -> Result<EnqueueOutcome, DomainError> {{\n        let payload = serde_json::to_value(&msg)\n            .map_err(|e| DomainError::Repository(format!(\"{{}} payload: {{e}}\", M::MESSAGE_TYPE)))?;\n        self.assert_addressed(M::MESSAGE_TYPE, &payload)?;\n        let entry = command_entry(\"{actor}\", {width}, self.actor_id, M::MESSAGE_TYPE, payload, env);\n        let payload_hash = entry.payload_hash.clone();\n        insert_mapped(self.mailbox.as_ref(), entry, &payload_hash).await\n    }}\n\n    /// Record one inbound FACT (kind EVENT, channel EXTERNAL, adjacently-tagged `DomainEvent`\n    /// payload). `message_id` is ALWAYS the deterministic `inbound_message_id(source,\n    /// external_id)` — never caller-supplied — and provenance is a REQUIRED parameter, because the\n    /// `(source, external_id)` dedupe key is what makes redelivery safe. The acting principal is\n    /// the per-source system user, stamped by the shared `inbound_entry` constructor.\n    pub async fn record<F: {actor}Fact>(\n        &self,\n        fact: F,\n        source: &str,\n        external_id: &str,\n        correlation_id: uuid::Uuid,\n    ) -> Result<EnqueueOutcome, DomainError> {{\n        let tagged = serde_json::to_value(fact.into_domain_event())\n            .map_err(|e| DomainError::Repository(format!(\"{{}} payload: {{e}}\", F::EVENT_TYPE)))?;\n        enqueue_inbound_fact(\n            self.mailbox.as_ref(),\n            InboundFact {{\n                source: source.to_owned(),\n                external_id: external_id.to_owned(),\n                event_type: F::EVENT_TYPE.to_owned(),\n                payload: tagged,\n                correlation_id,\n                actor_type: \"{actor}\".to_owned(),\n                actor_id: self.actor_id,\n            }},\n        )\n        .await\n    }}\n\n    /// Schedule one typed COMMAND for LATER delivery via the port's `schedule`: a SCHEDULED row\n    /// (`position` NULL) the promotion pass delivers when due; a still-SCHEDULED identity\n    /// reschedules IN PLACE (ADR-20260731-150500).\n    pub async fn schedule<M: {actor}Command>(\n        &self,\n        msg: M,\n        env: Envelope,\n        at: chrono::DateTime<chrono::Utc>,\n    ) -> Result<ScheduleOutcome, DomainError> {{\n        let payload = serde_json::to_value(&msg)\n            .map_err(|e| DomainError::Repository(format!(\"{{}} payload: {{e}}\", M::MESSAGE_TYPE)))?;\n        self.assert_addressed(M::MESSAGE_TYPE, &payload)?;\n        let entry = command_entry(\"{actor}\", {width}, self.actor_id, M::MESSAGE_TYPE, payload, env);\n        let payload_hash = entry.payload_hash.clone();\n        schedule_mapped(self.mailbox.as_ref(), entry, at, &payload_hash).await\n    }}\n\n    /// Withdraw a scheduled message (`SCHEDULED → CANCELLED`, ADR-20260731-150500 §3). `false` =\n    /// absent, delivered or already cancelled — the caller decides whether losing that race\n    /// matters. NOTE: unscoped by message_id today, like the port beneath it — lane-scoped\n    /// cancellation is a slice-2 question, recorded on #284.\n    pub async fn cancel(&self, message_id: uuid::Uuid) -> Result<bool, DomainError> {{\n        self.mailbox.cancel_scheduled(message_id).await\n    }}\n\n    /// The addressing invariant, enforced with the SAME `declared_identity` derivation the\n    /// free-function door uses: when the command declares an identity property, its value MUST\n    /// equal this client's lane — a mismatch would park the command on one lane while the handler\n    /// acts on another aggregate, silently breaking per-aggregate serialization. A command whose\n    /// actor declares no identity property is addressed by the lane the client was built with.\n    fn assert_addressed(&self, message_type: &str, payload: &serde_json::Value) -> Result<(), DomainError> {{\n        match declared_identity(message_type, payload)? {{\n            Some(id) if id != self.actor_id => Err(DomainError::Repository(format!(\n                \"{{message_type}}: payload identity {{id}} does not match this {actor}Client lane {{}} — refusing a mis-addressed send\",\n                self.actor_id\n            ))),\n            _ => Ok(()),\n        }}\n    }}\n}}\n"
        ));
    }
    out
}
