//! Emit `specs/generated/databases.generated.{md,json}` — THE DATABASE PLACEMENT INVENTORY
//! (#494 slice 1): every declared database, each table's RESOLVED database set, and the
//! recovery postures.
//!
//! THIS ARTIFACT IS THE INTERFACE THE NEXT SLICES BUILD AGAINST — read it, never the prose maps:
//!   - #509 "restore drill legs": one leg per database, shaped by `recovery` (pitr is restored,
//!     replay is replayed, refetch is re-ingested, backup-required needs its own dump story);
//!   - #513 "grant emitter + negative-path test": the per-database table sets are what a role is
//!     granted on — and what every OTHER role must be proven REFUSED;
//!   - #514 "per-database migration chains + the REQUIRED_SCHEMA_VERSION map": one chain per
//!     database in this inventory.
//! ADR-20260812-115930's membership table and PROP-20260811-093000 §11's placement map remain the
//! DECISION records; this file is the LIVE resolution of them against the spec tree.
//!
//! A table's `databases` is always a SET, even while every single-home value is a singleton — the
//! replicated class (STO-2(a)) already resolves to N, and the erasure sweep (#528) needs the full
//! set shape. Since STO-2 CLOSED (2026-08-14, DECISIONS §32 "STO-2 closure"; #562) EVERY
//! spec-declared table kind is covered, and the validator's completeness requirement consumes THIS
//! resolution (`validate::resolve_placements`), so nothing can be validator-green and
//! inventory-absent.

use crate::*;

fn placements_by_db(model: &Model) -> BTreeMap<String, Vec<String>> {
    let mut by_db: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for d in validate::parse_databases(model) {
        by_db.entry(d.name).or_default();
    }
    for p in validate::resolve_placements(model) {
        for db in &p.databases {
            by_db.entry(db.clone()).or_default().push(p.table.clone());
        }
    }
    for tables in by_db.values_mut() {
        tables.sort();
    }
    by_db
}

/// `specs/generated/databases.generated.json` — the machine face (what #509/#513/#514 consume).
pub(crate) fn emit_databases_json(model: &Model) -> String {
    use serde_json::{json, Map, Value as J};
    let by_db = placements_by_db(model);
    let mut databases = Map::new();
    for d in validate::parse_databases(model) {
        databases.insert(
            d.name.clone(),
            json!({
                "k8sName": d.k8s_name,
                "owner": d.owner,
                "recovery": d.recovery,
                "tables": by_db.get(&d.name).cloned().unwrap_or_default(),
            }),
        );
    }
    let mut tables = Map::new();
    for p in validate::resolve_placements(model) {
        tables.insert(
            p.table.clone(),
            json!({
                "kind": p.kind.name(),
                "placement": p.mode.name(),
                "databases": p.databases,
            }),
        );
    }
    let out = J::Object(Map::from_iter([
        (
            "comment".to_string(),
            J::String(
                "GENERATED by the Captain.Food codegen (tools/codegen-rs, emit/databases.rs) from \
                 specs/database/databases.yaml + the per-table placement keys -- do not edit by hand. \
                 The interface for #509 (drill legs), #513 (grant emitter), #514 (migration chains)."
                    .to_string(),
            ),
        ),
        ("databases".to_string(), J::Object(databases)),
        ("tables".to_string(), J::Object(tables)),
    ]));
    format!("{}\n", serde_json::to_string_pretty(&out).expect("databases inventory serializes"))
}

/// `specs/generated/databases.generated.md` — the human face of the same resolution.
pub(crate) fn emit_databases_md(model: &Model) -> String {
    let by_db = placements_by_db(model);
    let mut out = String::new();
    out.push_str("# Database placement inventory\n\n");
    out.push_str(
        "<!-- GENERATED by the Captain.Food codegen (tools/codegen-rs, emit/databases.rs) — do not edit by hand. -->\n\n",
    );
    out.push_str(
        "Resolved from [`specs/database/databases.yaml`](../database/databases.yaml) and the per-table \
         placement keys (#494 slice 1 — PROP-20260811-093000 STO-1(a)/STO-2(a), ADR-20260812-115930 ADP-1). \
         **This inventory is the interface the next slices build against**: \
         [#509 \"the restore drill grows a leg per database\"](https://github.com/TheCaptainCompany/captain-food/issues/509) \
         reads `recovery`, \
         [#513 \"the grant emitter and its negative-path test\"](https://github.com/TheCaptainCompany/captain-food/issues/513) \
         reads the per-database table sets, \
         [#514 \"per-database migration chains and the REQUIRED_SCHEMA_VERSION map\"](https://github.com/TheCaptainCompany/captain-food/issues/514) \
         reads the database list. The ADR's membership table and the proposal's §11 map are the decision \
         records; this file is their live resolution against the spec tree.\n\n",
    );
    out.push_str("## Databases\n\n");
    out.push_str("| Database | K8s object | Owning role | Recovery | Tables (resolved) |\n|---|---|---|---|---|\n");
    for d in validate::parse_databases(model) {
        let tables = by_db.get(&d.name).cloned().unwrap_or_default();
        let cell = if tables.is_empty() {
            "*(none yet — see the catalog's entry for what its first table owes)*".to_string()
        } else {
            tables.iter().map(|t| format!("`{}`", t)).collect::<Vec<_>>().join(" · ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} |\n",
            d.name, d.k8s_name, d.owner, d.recovery, cell
        ));
    }
    out.push_str("\n## Tables\n\n");
    out.push_str(
        "Every table of a covered kind, with its resolved database SET (a set even while single-home — \
         the replicated class resolves to N, and #528's erasure sweep needs the full set shape). \
         Since STO-2 closed (DECISIONS §32 \"STO-2 closure\", 2026-08-14) every spec-declared table \
         kind is covered: business read models and referential tables declare `database:` or \
         `replicated:` and an absent placement is a validator ERROR, never a default.\n\n",
    );
    out.push_str("| Table | Kind | Placement | Databases |\n|---|---|---|---|\n");
    for p in validate::resolve_placements(model) {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            p.table,
            p.kind.name(),
            p.mode.name(),
            p.databases.iter().map(|d| format!("`{}`", d)).collect::<Vec<_>>().join(" · ")
        ));
    }
    out
}
