use crate::*;

// ─── crates/domain/src/generated/scalars.rs (ADR-0034 #3 — Rust domain types from scalars.yaml) ──

/// A scalar's `description` as `///` doc lines (one per non-empty source line, trimmed).
pub(crate) fn scalar_doc(node: &Value) -> String {
    let mut out = String::new();
    if let Some(d) = node.get("description").and_then(|d| d.as_str()) {
        for line in d.trim().lines() {
            let line = line.trim();
            if !line.is_empty() {
                out.push_str("/// ");
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    out
}

/// Emit ONE scalar definition (enum or newtype) — the per-item body shared by the per-scope crate
/// emitter (`emit_domain_scope_crates`), which owns where each item now lives (#373).
pub(crate) fn push_scalar(out: &mut String, name: &str, node: &Value) {
    out.push('\n');
    out.push_str(&scalar_doc(node));
    if let Some(vals) = node.get("enum").and_then(|e| e.as_sequence()) {
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
        out.push_str("#[allow(non_camel_case_types)]\n");
        out.push_str(&format!("pub enum {} {{\n", name));
        for v in vals {
            if let Some(vs) = v.as_str() {
                // Verbatim: the Rust variant IS the spec value — 1:1 spec↔code↔wire, no serde
                // transform. The value must be a valid Rust identifier; a spec smell (hyphen,
                // space, leading digit) fails here so it is fixed at the root, not masked.
                assert!(
                    vs.chars().next().map_or(false, |c| c.is_ascii_alphabetic() || c == '_')
                        && vs.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                    "scalars.yaml#/{}: enum value '{}' is not a valid Rust identifier — rename it in the spec",
                    name,
                    vs
                );
                out.push_str(&format!("    {},\n", vs));
            }
        }
        out.push_str("}\n");
        return;
    }
    let ty = node.get("type").and_then(|t| t.as_str()).unwrap_or("string");
    let is_uuid = node.get("format").and_then(|f| f.as_str()) == Some("uuid");
    let (derives, inner) = if is_uuid {
        ("Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize", "uuid::Uuid")
    } else if ty == "integer" {
        ("Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize", "i64")
    } else if ty == "number" {
        ("Debug, Clone, Copy, PartialEq, PartialOrd, Serialize, Deserialize", "f64")
    } else {
        // Default: a projection folding a legacy event that predates a required property
        // falls back to the empty value instead of panicking the worker (see the
        // ScalarLatest required-on-creation arm of the projector emitter).
        ("Debug, Clone, Default, PartialEq, Eq, Hash, Serialize, Deserialize", "String")
    };
    out.push_str(&format!("#[derive({})]\n", derives));
    out.push_str(&format!("pub struct {}(pub {});\n", name, inner));
}

/// The scopes that own ≥1 emitted item of `kind`, in scope order — the facade's re-export list.
fn scopes_with(model: &Model, kind: &str) -> Vec<String> {
    model
        .scopes
        .iter()
        .filter(|s| !scope_items(model, s, kind).is_empty())
        .cloned()
        .collect()
}

/// The facade banner + one `pub use domain_{scope}::{module}::*;` line per owning scope: since
/// #373 the items live in the per-scope crates (`crates/domains/{scope}`), and `crates/domain`
/// re-exports them so every `domain::generated::*` path keeps resolving with the SAME type
/// identity (a re-export is the type, not a copy).
fn facade_reexports(model: &Model, kind: &str, module: &str, what: &str) -> String {
    let mut out = format!(
        "// GENERATED by the Captain.Food codegen — do not edit by hand (#373, ADR-20260807-183024\n// step 2). {what} now live in the per-scope domain crates (specs/{{scope}}/{kind} →\n// crates/domains/{{scope}}); this facade re-exports every scope's module so existing\n// `domain::generated::{module}::*` paths keep resolving with the SAME type identity.\n",
    );
    out.push('\n');
    for s in scopes_with(model, kind) {
        out.push_str(&format!("pub use {}::{}::*;\n", domain_crate_ident(&s), module));
    }
    out
}

/// Emit `crates/domain/src/generated/scalars.rs` — since #373 a RE-EXPORT facade over the
/// per-scope crates' `scalars` modules (the definitions live in `crates/domains/{scope}`).
pub(crate) fn emit_domain_scalars(model: &Model) -> String {
    facade_reexports(model, "scalars.yaml", "scalars", "Scalar types")
}

// ─── crates/domain/src/generated/entities.rs (ADR-0034 #3 — Rust entity structs from entities.yaml) ──

/// snake_case of a camelCase property name (e.g. `amountCents` → `amount_cents`).
pub(crate) fn snake_field(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_uppercase() {
            out.push('_');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// What serde's `rename_all = "camelCase"` produces for a snake_case field (uppercase the char after
/// each `_`, dropping the `_`). Used to PROVE at generation time that every struct field round-trips
/// back to its exact `entities.yaml` property name on the wire.
pub(crate) fn serde_camel(field: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in field.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Rust keywords that may appear as entity property names (`ref`, `default` do) — emitted as raw
/// identifiers (`r#ref`). serde renames from the identifier WITHOUT the `r#`, so the wire value stays
/// the spec property name.
pub(crate) const RUST_FIELD_KEYWORDS: &[&str] = &[
    "as", "async", "await", "box", "break", "const", "continue", "default", "do", "dyn", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut",
    "priv", "pub", "ref", "return", "static", "struct", "trait", "true", "try", "type", "union",
    "unsafe", "use", "where", "while", "yield",
];

/// The Rust type of one struct property node, BEFORE optionality wrapping: `$ref` → the referenced
/// type name (scalars/entities are in scope via `use super::…::*`, same-module refs resolve directly),
/// arrays → `Vec<Item>`, inline primitives → `String`/`i64`/`bool`/`f64` (`date-time` stays `String`).
/// `file` is the spec file the owning struct came from (for panic messages only).
pub(crate) fn struct_field_type(file: &str, owner: &str, prop: &str, node: &Value) -> String {
    if let Some(rf) = node.get("$ref").and_then(|x| x.as_str()) {
        return ref_name(rf)
            .unwrap_or_else(|| panic!("{}#/{}/{}: malformed $ref '{}'", file, owner, prop, rf));
    }
    match node.get("type").and_then(|t| t.as_str()) {
        Some("array") => {
            let items = node
                .get("items")
                .unwrap_or_else(|| panic!("{}#/{}/{}: array without items", file, owner, prop));
            format!("Vec<{}>", struct_field_type(file, owner, prop, items))
        }
        Some("string") => "String".to_string(),
        Some("integer") => "i64".to_string(),
        Some("boolean") => "bool".to_string(),
        Some("number") => "f64".to_string(),
        other => panic!("{}#/{}/{}: unsupported inline type {:?}", file, owner, prop, other),
    }
}

/// Emit one serde `camelCase` payload struct for a spec node with `properties`/`required` (shared by the
/// entities, events and commands emitters — same shape). A field is optional (`Option<T>`) when
/// `nullable: true` or absent from `required`; optional ARRAYS stay `Vec<T>` with `#[serde(default)]`
/// (a missing array deserializes to empty, never `Option<Vec>`).
pub(crate) fn push_struct(out: &mut String, file: &str, name: &str, node: &Value) {
    out.push('\n');
    out.push_str(&scalar_doc(node));
    out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    out.push_str("#[serde(rename_all = \"camelCase\")]\n");
    out.push_str(&format!("pub struct {} {{\n", name));
    let required: BTreeSet<&str> = node
        .get("required")
        .and_then(|r| r.as_sequence())
        .map(|s| s.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    if let Some(props) = node.get("properties").and_then(|p| p.as_mapping()) {
        for (pk, pnode) in props {
            let prop = match pk.as_str() {
                Some(s) => s,
                None => continue,
            };
            let field = snake_field(prop);
            // PROVE serde's camelCase rename restores the exact spec property name on the wire
            // (raw `r#` prefixes are stripped before renaming, so `ref`/`default` stay as-is);
            // fail loudly at generation rather than corrupt the wire.
            assert_eq!(
                serde_camel(&field),
                prop,
                "{}#/{}/{}: field '{}' does not round-trip through serde rename_all",
                file,
                name,
                prop,
                field
            );
            let ident = if RUST_FIELD_KEYWORDS.contains(&field.as_str()) {
                format!("r#{}", field)
            } else {
                field
            };
            let ty = struct_field_type(file, name, prop, pnode);
            let nullable = pnode.get("nullable").and_then(|x| x.as_bool()) == Some(true);
            let optional = nullable || !required.contains(prop);
            if ty.starts_with("Vec<") {
                if optional {
                    out.push_str("    #[serde(default)]\n");
                }
                out.push_str(&format!("    pub {}: {},\n", ident, ty));
            } else if optional {
                out.push_str(&format!("    pub {}: Option<{}>,\n", ident, ty));
            } else {
                out.push_str(&format!("    pub {}: {},\n", ident, ty));
            }
        }
    }
    out.push_str("}\n");
}

/// True for a spec node that defines a payload struct (an object with `properties`, or `type: object`) —
/// distinguishes real definitions from a file's top-level `version`/`description` meta.
pub(crate) fn is_struct_def(node: &Value) -> bool {
    node.is_mapping()
        && (node.get("properties").is_some() || node.get("type").and_then(|t| t.as_str()) == Some("object"))
}

/// Emit `crates/domain/src/generated/entities.rs` — since #373 a RE-EXPORT facade over the
/// per-scope crates' `entities` modules (the definitions live in `crates/domains/{scope}`).
pub(crate) fn emit_domain_entities(model: &Model) -> String {
    facade_reexports(model, "entities.yaml", "entities", "Entity structs")
}

/// Emit `crates/domain/src/generated/events.rs` — since #373 the event payload STRUCTS live in the
/// per-scope crates; this facade re-exports them and keeps the ONE genuinely cross-scope artifact:
/// the `DomainEvent` union. The single event log (D3, ADR-20260807-183024) speaks every scope's
/// events, so its typed union must link every scope — per-scope event unions are step (3)'s bin
/// work, not this facade's.
pub(crate) fn emit_domain_events(model: &Model) -> String {
    let mut out = facade_reexports(model, "events.yaml", "events", "Event payload structs");
    // The DomainEvent enum — a typed union of every business event, adjacently tagged so it (de)serializes
    // straight from the stored envelope shape `{ eventType, payload }`. Projectors and the event store
    // match on this instead of stringly-typed event_type + a serde_json::Value payload. Variant order is
    // the MERGED events.yaml catalog order (scope-alphabetical, then fragment order) — stable.
    out.push_str("\nuse serde::{Deserialize, Serialize};\n");
    out.push_str(
        "\n/// Every business event as a typed, adjacently-tagged union: `{ \"eventType\": <name>, \"payload\": { … } }`.\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(tag = \"eventType\", content = \"payload\")]\npub enum DomainEvent {\n",
    );
    if let Some(Value::Mapping(m)) = model.defs.get("events.yaml") {
        for (k, node) in m {
            if let Some(name) = k.as_str() {
                if is_struct_def(node) {
                    out.push_str(&format!("    {}({}),\n", name, name));
                }
            }
        }
    }
    out.push_str("}\n");
    out
}

/// The Rust type of a materialized read-model column: a SQL primitive maps to its Rust counterpart,
/// otherwise the name is a scalars.yaml newtype (in scope via `use domain::generated::scalars::*`).
/// An undetermined type (a computed column with no derivable lineage) falls back to `serde_json::Value`.
pub(crate) fn projection_rust_type(ty: &str) -> String {
    match ty {
        "" => "serde_json::Value".to_string(),
        "text" => "String".to_string(),
        "jsonb" => "serde_json::Value".to_string(),
        "integer" => "i64".to_string(),
        "bigint" => "i64".to_string(),
        "boolean" => "bool".to_string(),
        "numeric" => "f64".to_string(),
        "timestamptz" => "chrono::DateTime<chrono::Utc>".to_string(),
        // A raw `uuid` column — an id with no dedicated domain scalar because it is POLYMORPHIC
        // (ScopeMembership.scope_id is an OrderId or a RestaurantId; member_id a CustomerId,
        // RestaurantId, RestaurantAccountId or RiderId). Without this arm the bare crate name `uuid`
        // was emitted as the field type and the row struct did not compile (#144).
        "uuid" => "uuid::Uuid".to_string(),
        scalar => scalar.to_string(),
    }
}

/// Emit `crates/application/src/generated/rows.rs` — one `<Table>Row` struct per materialized read-model
/// table (projection_tables.yaml). These are the rows a projector writes and the query side returns
/// (ADR-0040). Column names are already snake_case, so serde's defaults match; jsonb / entity-shaped
/// columns are `serde_json::Value`, timestamps `chrono::DateTime<Utc>`, domain scalars their newtype.
pub(crate) fn emit_projection_rows(model: &Model) -> String {
    let mut out = String::from(
        "// GENERATED by the Captain.Food codegen from specs/database/tables/projection_tables.yaml — do not edit by hand.\n// Read-model row types: what a projector writes and the query side returns (ADR-0040).\n\nuse serde::{Deserialize, Serialize};\nuse domain::generated::scalars::*;\n",
    );
    for v in parse_views(model).iter().filter(|v| v.is_table) {
        out.push('\n');
        if let Some(note) = &v.note {
            out.push_str(&format!("/// {}\n", ws1(note)));
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub struct {}Row {{\n", v.name));
        for c in &v.columns {
            let rt = projection_rust_type(&c.ty);
            let ty = if c.nullable && !c.pk { format!("Option<{}>", rt) } else { rt };
            let ident = if RUST_FIELD_KEYWORDS.contains(&c.name.as_str()) {
                format!("r#{}", c.name)
            } else {
                c.name.clone()
            };
            out.push_str(&format!("    pub {}: {},\n", ident, ty));
        }
        out.push_str("}\n");
    }
    out
}

/// An event property's node in events.yaml (`events.yaml#/<event>/properties/<prop>`), if present.
pub(crate) fn event_prop_node<'a>(model: &'a Model, event: &str, prop: &str) -> Option<&'a Value> {
    model.defs.get("events.yaml")?.get(event)?.get("properties")?.get(prop)
}

/// Whether an event carries a property at all (used as the same-stream test: an event is same-stream for a
/// table iff it carries the table's PK property).
pub(crate) fn event_has_prop(model: &Model, event: &str, prop: &str) -> bool {
    event_prop_node(model, event, prop).is_some()
}

/// Whether an event property is optional on the wire (nullable, or absent from the event's `required`).
pub(crate) fn event_prop_optional(model: &Model, event: &str, prop: &str) -> bool {
    let ev = model.defs.get("events.yaml").and_then(|e| e.get(event));
    let required = ev
        .and_then(|e| e.get("required"))
        .and_then(|r| r.as_sequence())
        .map(|s| s.iter().any(|v| v.as_str() == Some(prop)))
        .unwrap_or(false);
    let nullable = event_prop_node(model, event, prop)
        .and_then(|p| p.get("nullable"))
        .and_then(|b| b.as_bool())
        == Some(true);
    nullable || !required
}

/// Snake_case Rust field ident for a column/property, raw-escaped if it collides with a keyword.
pub(crate) fn rust_ident(name: &str) -> String {
    if RUST_FIELD_KEYWORDS.contains(&name) {
        format!("r#{}", name)
    } else {
        name.to_string()
    }
}

/// Emit `crates/domain/src/generated/commands.rs` — since #373 a RE-EXPORT facade over the
/// per-scope crates' `commands` modules (the definitions live in `crates/domains/{scope}`).
pub(crate) fn emit_domain_commands(model: &Model) -> String {
    facade_reexports(model, "commands.yaml", "commands", "Command payload structs")
}

// ─── crates/domain/src/generated/errors.rs (anticipated-error catalog from errors.yaml) ───

/// Escape a spec string for embedding in a Rust string literal.
pub(crate) fn rust_string_lit(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n")
}

/// SCREAMING_SNAKE const name for a PascalCase errors.yaml key (`SlugAlreadyTaken` →
/// `SLUG_ALREADY_TAKEN`).
pub(crate) fn screaming_snake(name: &str) -> String {
    snake_field(name).trim_start_matches('_').to_ascii_uppercase()
}

/// Emit ONE anticipated-error `ErrorDef` const — the per-item body shared by the per-scope crate
/// emitter (`emit_domain_scope_crates`), which owns where each error now lives (#373).
pub(crate) fn push_error_const(out: &mut String, name: &str, node: &Value) {
    let konst = screaming_snake(name);
    let en = node
        .get("messages")
        .and_then(|ms| ms.get("en"))
        .and_then(|x| x.as_str())
        .unwrap_or("");
    let fr = node
        .get("messages")
        .and_then(|ms| ms.get("fr"))
        .and_then(|x| x.as_str())
        .unwrap_or("");
    out.push('\n');
    push_doc(out, "", node.get("description").and_then(|x| x.as_str()));
    // Document the typed context fields (camelCase keys of the rejection's JSON context).
    if let Some(ctx) = node.get("context").and_then(|c| c.as_mapping()) {
        if !ctx.is_empty() {
            let fields: Vec<&str> = ctx.iter().filter_map(|(ck, _)| ck.as_str()).collect();
            out.push_str(&format!("/// Context: `{}`.\n", fields.join("`, `")));
        }
    }
    out.push_str(&format!(
        "pub const {}: ErrorDef = ErrorDef {{\n    code: \"{}\",\n    message_en: \"{}\",\n    message_fr: \"{}\",\n}};\n",
        konst,
        rust_string_lit(name),
        rust_string_lit(en),
        rust_string_lit(fr)
    ));
}

/// Emit `crates/domain/src/generated/errors.rs` — since #373 the per-error `ErrorDef` consts live
/// in the per-scope crates (with `ErrorDef` + `interpolate` in the kernel, `domain-common`); this
/// facade re-exports them and keeps the genuinely GLOBAL pieces: the whole-catalog `ERRORS` slice,
/// `find` (wire-code lookup — a rejection's code arrives untyped off the wire, so the lookup must
/// span every scope), and the localized `message_en`/`message_fr` built on both. Error contract
/// P-10: the const's `code` is the errors.yaml key = the GraphQL `extensions.code`.
pub(crate) fn emit_domain_errors(model: &Model) -> String {
    let mut out = facade_reexports(
        model,
        "errors.yaml",
        "errors",
        "The per-error `ErrorDef` consts (kernel: also `ErrorDef` + `interpolate`)",
    );
    // The kernel's errors module exists whenever ANY scope declares errors (it owns `ErrorDef` +
    // `interpolate`), so re-export it even when the kernel declares no error items of its own —
    // the global catalog below is typed by it.
    let kernel_line = format!("pub use {}::errors::*;\n", domain_crate_ident(KERNEL_SCOPE));
    if !out.contains(&kernel_line)
        && model.scopes.iter().any(|s| !scope_items(model, s, "errors.yaml").is_empty())
    {
        out.push_str(&kernel_line);
    }
    let mut names: Vec<String> = Vec::new();
    if let Some(Value::Mapping(m)) = model.defs.get("errors.yaml") {
        for (k, _) in m {
            if let Some(name) = k.as_str() {
                names.push(screaming_snake(name));
            }
        }
    }
    out.push_str("\n/// Every anticipated error, in errors.yaml order.\npub const ERRORS: &[ErrorDef] = &[\n");
    for n in &names {
        out.push_str(&format!("    {},\n", n));
    }
    out.push_str("];\n");
    out.push_str(
        "\n/// Look up an anticipated error by its stable PascalCase code.\npub fn find(code: &str) -> Option<&'static ErrorDef> {\n    ERRORS.iter().find(|e| e.code == code)\n}\n\n/// The interpolated English message for `code`, if it is a catalogued error.\npub fn message_en(code: &str, context: &serde_json::Value) -> Option<String> {\n    find(code).map(|e| interpolate(e.message_en, context))\n}\n\n/// The interpolated French message for `code`, if it is a catalogued error.\npub fn message_fr(code: &str, context: &serde_json::Value) -> Option<String> {\n    find(code).map(|e| interpolate(e.message_fr, context))\n}\n",
    );
    out
}

// ─── crates/domain/src/generated/states.rs (declared-state folds, PROP-20260728-135632 §2.1) ──

/// Emit `crates/domain/src/generated/states.rs` — one module per actor declaring a `state:` block
/// in actors.yaml (#242 Runtime A): the declared, event-lineaged fold as plain data/match — the
/// SAME shape as the hand-written write-side state so parity is assertable field by field. Modes:
/// `latest` assigns the lineage property; `flag` sets on `from`, clears on `removedBy`; `set`
/// inserts/removes its element (scalar lineage property, or a composite read off the payload by
/// key name in declaration order); `count` increments. A BIRTH event (one appearing in the `from`
/// lineage of every non-nullable latest field) constructs the state fresh (replace semantics —
/// mirroring the hand folds); every other arm requires an existing state (`state?`), so a stream
/// that never births folds to `None`.
pub(crate) fn emit_domain_states(model: &Model) -> String {
    let mut out = String::from(
        "// GENERATED by the Captain.Food codegen from specs/actors.yaml `state` blocks\n// (PROP-20260728-135632 §2.1, #242 Runtime A) — do not edit by hand. Declared write-side state\n// folds as plain data/match (no SDK, no I/O — the domain stays dependency-free): the hand-written\n// aggregate keeps its own fold, and the parity test asserts the two can never disagree with the\n// declared spec lineage.\n",
    );
    let Some(Value::Mapping(actors)) = model.defs.get("actors.yaml") else { return out };
    for (k, def) in actors {
        let actor = match k.as_str() {
            Some(s) if s != "principals" => s,
            _ => continue,
        };
        let Some(Value::Mapping(state)) = def.get("state") else { continue };
        // #582 (PROP-20260815-142349 §19): an actor with a `lifecycle:` block keeps its
        // HAND-WRITTEN fold — the declared-state grammar cannot yet express the
        // lifecycle-owned `status` (`st-status-duplicated` forbids redeclaring it), nested
        // payload lineage (`checkout/orderId`) or entity-typed fields, so a generated fold
        // here would be a second, partial state type for the same actor. Its `state:` block
        // is DECLARATION-ONLY this slice: it types the actor's `answers:` replies, and
        // YAML↔fold parity is enforced by the reply-construction tests colocated in the hand
        // fold modules (compiler-checked), not by this emitter. Fold generation composes with
        // the lifecycle table in the states-generation slice 2 (#242).
        if def.get("lifecycle").is_some() {
            continue;
        }

        // Parse the fields in declaration order.
        struct Field {
            name: String,             // spec (camelCase) name
            rust: String,             // snake_case field
            mode: String,             // latest | flag | set | count
            ty: String,               // rendered Rust type
            nullable: bool,
            scalar_of: Option<String>,          // set: scalar element type
            composite_of: Vec<(String, String)>, // set: composite (payload key, element type)
            from: Vec<(String, Option<String>)>,     // (event, Some(prop) | None)
            removed_by: Vec<(String, Option<String>)>,
        }
        let scalar_name = |node: &Value| -> Option<String> {
            node.get("$ref").and_then(|r| r.as_str()).and_then(ref_name)
        };
        let lineage = |node: Option<&Value>| -> Vec<(String, Option<String>)> {
            node.and_then(|v| v.as_sequence())
                .map(|seq| {
                    seq.iter()
                        .filter_map(|e| e.get("$ref").and_then(|r| r.as_str()))
                        .filter_map(|r| lineage_parts(r).map(|(ev, p)| (ev.to_string(), p.map(str::to_string))))
                        .collect()
                })
                .unwrap_or_default()
        };
        let mut fields: Vec<Field> = Vec::new();
        let mut scalar_imports: BTreeSet<String> = BTreeSet::new();
        for (fk, fdef) in state {
            let Some(name) = fk.as_str() else { continue };
            let mode = fdef
                .get("mode")
                .and_then(|m| m.as_str())
                .unwrap_or("latest")
                .to_string();
            let nullable = fdef.get("nullable").and_then(|n| n.as_bool()).unwrap_or(false);
            let mut scalar_of = None;
            let mut composite_of = Vec::new();
            let ty = match mode.as_str() {
                "flag" => "bool".to_string(),
                "count" => "i64".to_string(),
                "set" => match fdef.get("of") {
                    Some(of) if of.get("$ref").is_some() => {
                        let n = scalar_name(of).expect("set `of` $ref must name a scalar");
                        scalar_imports.insert(n.clone());
                        scalar_of = Some(n.clone());
                        format!("Vec<{}>", n)
                    }
                    Some(Value::Mapping(keys)) => {
                        let mut parts = Vec::new();
                        for (kk, kv) in keys {
                            let key = kk.as_str().expect("composite `of` key").to_string();
                            let n = scalar_name(kv).expect("composite `of` value must be a scalar $ref");
                            scalar_imports.insert(n.clone());
                            parts.push(n.clone());
                            composite_of.push((key, n));
                        }
                        format!("Vec<({})>", parts.join(", "))
                    }
                    _ => panic!("actors.yaml {}/state/{}: set without `of`", actor, name),
                },
                _ => {
                    // latest: `type` is a scalar $ref or an inline boolean.
                    let base = match fdef.get("type") {
                        Some(t) if t.get("$ref").is_some() => {
                            let n = scalar_name(t).expect("state `type` $ref must name a scalar");
                            scalar_imports.insert(n.clone());
                            n
                        }
                        Some(t) if t.as_str() == Some("boolean") => "bool".to_string(),
                        other => panic!(
                            "actors.yaml {}/state/{}: unsupported latest type {:?} — extend emit_domain_states",
                            actor, name, other
                        ),
                    };
                    if nullable { format!("Option<{}>", base) } else { base }
                }
            };
            fields.push(Field {
                name: name.to_string(),
                rust: snake_field(name),
                mode,
                ty,
                nullable,
                scalar_of,
                composite_of,
                from: lineage(fdef.get("from")),
                removed_by: lineage(fdef.get("removedBy")),
            });
        }

        // Birth events: appear in the `from` lineage of EVERY non-nullable latest field (those are
        // the fields with no meaningful default — a state cannot exist without them).
        let strict: Vec<&Field> = fields
            .iter()
            .filter(|f| f.mode == "latest" && !f.nullable)
            .collect();
        let mut birth_events: Vec<String> = Vec::new();
        if let Some(first) = strict.first() {
            for (ev, _) in &first.from {
                if strict.iter().all(|f| f.from.iter().any(|(e, _)| e == ev)) {
                    birth_events.push(ev.clone());
                }
            }
        }
        assert!(
            strict.is_empty() || !birth_events.is_empty(),
            "actors.yaml {}/state: no single event assigns every non-nullable latest field — no birth arm can be generated",
            actor
        );

        // Group the per-event mutation statements (insertion order = spec field order).
        #[allow(clippy::type_complexity)]
        let mut arms: Vec<(String, Vec<String>)> = Vec::new();
        let stmt = |ev: &str, s: String, arms: &mut Vec<(String, Vec<String>)>| {
            match arms.iter_mut().find(|(e, _)| e == ev) {
                Some((_, v)) => v.push(s),
                None => arms.push((ev.to_string(), vec![s])),
            }
        };
        for f in &fields {
            match f.mode.as_str() {
                "latest" => {
                    for (ev, prop) in &f.from {
                        let p = prop.as_deref().unwrap_or_else(|| panic!(
                            "actors.yaml {}/state/{}: latest lineage must name a property",
                            actor, f.name
                        ));
                        stmt(ev, format!("s.{} = e.{}.clone();", f.rust, snake_field(p)), &mut arms);
                    }
                }
                "flag" => {
                    for (ev, _) in &f.from {
                        stmt(ev, format!("s.{} = true;", f.rust), &mut arms);
                    }
                    for (ev, _) in &f.removed_by {
                        stmt(ev, format!("s.{} = false;", f.rust), &mut arms);
                    }
                }
                "count" => {
                    for (ev, _) in &f.from {
                        stmt(ev, format!("s.{} += 1;", f.rust), &mut arms);
                    }
                }
                "set" => {
                    if f.scalar_of.is_some() {
                        for (ev, prop) in &f.from {
                            let p = snake_field(prop.as_deref().expect("scalar set lineage names a property"));
                            stmt(
                                ev,
                                format!(
                                    "if !s.{f}.contains(&e.{p}) {{ s.{f}.push(e.{p}.clone()); }}",
                                    f = f.rust,
                                    p = p
                                ),
                                &mut arms,
                            );
                        }
                        for (ev, prop) in &f.removed_by {
                            let p = snake_field(prop.as_deref().expect("scalar set removedBy names a property"));
                            stmt(ev, format!("s.{f}.retain(|v| *v != e.{p});", f = f.rust, p = p), &mut arms);
                        }
                    } else {
                        let tuple = f
                            .composite_of
                            .iter()
                            .map(|(k, _)| format!("e.{}.clone()", snake_field(k)))
                            .collect::<Vec<_>>()
                            .join(", ");
                        for (ev, _) in &f.from {
                            stmt(
                                ev,
                                format!(
                                    "let el = ({tuple}); if !s.{f}.contains(&el) {{ s.{f}.push(el); }}",
                                    f = f.rust
                                ),
                                &mut arms,
                            );
                        }
                        for (ev, _) in &f.removed_by {
                            stmt(
                                ev,
                                format!("let el = ({tuple}); s.{f}.retain(|v| *v != el);", f = f.rust),
                                &mut arms,
                            );
                        }
                    }
                }
                other => panic!("actors.yaml {}/state/{}: unknown mode '{}'", actor, f.name, other),
            }
        }

        // ── Emit the module ──
        let module = snake_type(actor);
        let struct_name = format!("{}State", actor);
        let imports = scalar_imports.iter().cloned().collect::<Vec<_>>().join(", ");
        out.push_str(&format!(
            "\n/// {actor} declared state (specs/actors.yaml#/{actor}/state) — the write-side fold the\n/// `requires` authorization reads.\npub mod {module} {{\n    use crate::generated::events::DomainEvent;\n    use crate::generated::scalars::{{{imports}}};\n\n"
        ));
        out.push_str(&format!("    #[derive(Debug, Clone, PartialEq)]\n    pub struct {} {{\n", struct_name));
        for f in &fields {
            if let Some(note) = state
                .get(f.name.as_str())
                .and_then(|d| d.get("note"))
                .and_then(|n| n.as_str())
            {
                out.push_str(&format!("        /// {}\n", note));
            }
            out.push_str(&format!("        pub {}: {},\n", f.rust, f.ty));
        }
        out.push_str("    }\n\n");
        out.push_str(&format!(
            "    /// Fold a stream (version order). `None` until a birth event establishes the state.\n    pub fn fold(events: &[DomainEvent]) -> Option<{s}> {{\n        events.iter().fold(None, apply)\n    }}\n\n    /// Apply one event — a pure transition, total over the whole event union.\n    pub fn apply(state: Option<{s}>, event: &DomainEvent) -> Option<{s}> {{\n        match event {{\n",
            s = struct_name
        ));
        for (ev, stmts) in &arms {
            if birth_events.contains(ev) {
                // Birth: construct fresh (replace semantics), latest fields from the payload,
                // everything else at its default. Non-latest statements for the same event
                // (a birth that also feeds a flag/set/count lineage) re-run over the fresh state.
                let mut ctor = Vec::new();
                for f in &fields {
                    if f.mode == "latest" {
                        if let Some((_, Some(p))) = f.from.iter().find(|(e, _)| e == ev) {
                            ctor.push(format!("{}: e.{}.clone()", f.rust, snake_field(p)));
                            continue;
                        }
                    }
                    ctor.push(format!("{}: Default::default()", f.rust));
                }
                // The grouped `latest` assignments are already the constructor — keep the rest.
                let extra: Vec<&String> =
                    stmts.iter().filter(|s| !(s.starts_with("s.") && s.contains(" = e."))).collect();
                out.push_str(&format!(
                    "            DomainEvent::{ev}(e) => {{\n                #[allow(unused_mut)]\n                let mut s = {s} {{ {c} }};\n",
                    s = struct_name,
                    c = ctor.join(", ")
                ));
                for st in extra {
                    out.push_str(&format!("                {}\n", st));
                }
                out.push_str("                Some(s)\n            }\n");
            } else {
                let binding = if stmts.iter().any(|s| s.contains("e.")) { "e" } else { "_" };
                out.push_str(&format!(
                    "            DomainEvent::{ev}({binding}) => {{\n                let mut s = state?;\n"
                ));
                for st in stmts {
                    out.push_str(&format!("                {}\n", st));
                }
                out.push_str("                Some(s)\n            }\n");
            }
        }
        out.push_str("            _ => state,\n        }\n    }\n}\n");
    }
    out
}

// ─── crates/domain/src/generated/answers.rs (actor answers Request/Reply, PROP-20260815-142349) ──

/// One reply/params field, resolved for emission: the Rust field, its rendered type, and the doc.
struct AnswerField {
    rust: String,
    ty: String,
    optional: bool,
    doc: Option<String>,
}

/// One declared answer operation, resolved for emission (shared between the domain types emitter
/// and the client-surface emitter so the two can never disagree).
pub(crate) struct AnswerOp {
    pub(crate) actor: String,
    pub(crate) op: String,
    /// `OrderPaymentReference` — the `<Actor><Op>` prefix of the generated Request/Reply pair.
    pub(crate) pair: String,
    /// The snake-case Rust field of the REQUEST that carries the actor's identity (the stream
    /// key — how the local adapter addresses the stream).
    pub(crate) identity_rust: String,
    /// `(reply rust field, actor-state rust field)` pairs — the projection sites.
    pub(crate) projections: Vec<(String, String)>,
}

/// Render a scalars.yaml/entities.yaml `$ref` into a Rust type name, recording the import.
fn answer_type(
    r: &str,
    scalar_imports: &mut BTreeSet<String>,
    entity_imports: &mut BTreeSet<String>,
) -> String {
    let name = ref_name(r).unwrap_or_else(|| panic!("answers: malformed type ref '{r}'"));
    match ref_target_file(r, "actors.yaml").as_deref() {
        Some("entities.yaml") => entity_imports.insert(name.clone()),
        _ => scalar_imports.insert(name.clone()),
    };
    name
}

/// The scalar `$ref` typing an actor's IDENTITY field. The identity is the stream key — it exists
/// before any fold, so it usually has NO `state:` entry of its own (see
/// `is_implicit_identity_state_ref`): its scalar is recovered from the actor's own inbox, where
/// every received message that carries a payload property named after the identity types it —
/// the same place command addressing reads it from. All carriers must AGREE (one name = one
/// dedicated scalar); a conflict or an inbox that never carries the identity returns `None` and
/// generation refuses loudly rather than guessing.
fn identity_scalar_ref(model: &Model, def: &Value, identity: &str) -> Option<String> {
    let mut found: Option<String> = None;
    let receives = def.get("receives").and_then(|r| r.as_sequence())?;
    for entry in receives {
        let Some(mref) = entry.get("message").and_then(|m| m.get("$ref")).and_then(|r| r.as_str())
        else {
            continue;
        };
        let Some((file, key)) = mref.split_once("#/") else { continue };
        let ty = model
            .defs
            .get(file)
            .and_then(|d| d.get(key))
            .and_then(|n| n.get("properties"))
            .and_then(|p| p.get(identity))
            .and_then(|f| f.get("$ref"))
            .and_then(|r| r.as_str());
        if let Some(t) = ty {
            match &found {
                None => found = Some(t.to_string()),
                Some(prev) if prev != t => return None, // conflicting carriers — refuse to guess
                _ => {}
            }
        }
    }
    found
}

/// Every declared answer operation with its resolved fields, in catalog order. Panics (loudly, at
/// generation) on shapes the `ans-*` validator already refuses — the two must agree.
fn parse_answers(model: &Model) -> Vec<(AnswerOp, Vec<AnswerField>, Vec<AnswerField>, String)> {
    let mut out = Vec::new();
    let Some(Value::Mapping(actors)) = model.defs.get("actors.yaml") else { return out };
    for (k, def) in actors {
        let Some(actor) = k.as_str().filter(|s| *s != "principals") else { continue };
        let Some(answers) = def.get("answers").and_then(|a| a.as_mapping()) else { continue };
        let identity = actor_identity_field(def, actor).unwrap_or_else(|| {
            panic!("actors.yaml {}: `answers:` needs a typed `identity` (the ask is addressed by it)", actor)
        });
        for (ok, op_def) in answers {
            let Some(op) = ok.as_str() else { continue };
            let description = op_def
                .get("description")
                .and_then(|d| d.as_str())
                .unwrap_or("")
                .trim()
                .to_string();
            let mut scalar_imports = BTreeSet::new(); // rendered per-field; imports merged later
            let mut entity_imports = BTreeSet::new();
            // The field type of one same-actor state field (reply property / identity), via the
            // shared validator resolution so generation cannot drift from `ans-reply-ref`.
            let state_field_ty = |field: &str| -> (String, bool) {
                match resolve_reply_field(def, actor, field) {
                    Some(ReplyField::Declared { flag: true, .. }) => ("bool".into(), false),
                    Some(ReplyField::Declared { type_ref: Some(r), nullable, .. }) => {
                        (ref_name(&r).expect("state type ref"), nullable)
                    }
                    Some(ReplyField::Declared { type_ref: None, .. }) => ("bool".into(), false),
                    Some(ReplyField::LifecycleStatus { status_ref }) => {
                        (ref_name(&status_ref).expect("lifecycle status ref"), false)
                    }
                    Some(ReplyField::Identity) => {
                        let r = identity_scalar_ref(model, def, field).unwrap_or_else(|| panic!(
                            "actors.yaml {}/answers/{}: the identity field '{}' has no single agreed scalar on the actor's received payloads — declare it in `state:` or fix the carriers",
                            actor, op, field
                        ));
                        (ref_name(&r).expect("identity scalar ref"), false)
                    }
                    None => panic!(
                        "actors.yaml {}/answers/{}: field '{}' must be a declared `state:` entry (or the lifecycle status / identity) so its scalar is knowable — declare it",
                        actor, op, field
                    ),
                }
            };
            // REQUEST fields: the declared params; the identity field is added when absent
            // (identity IS the argument — PROP §3's common case).
            let mut request: Vec<AnswerField> = Vec::new();
            let mut has_identity = false;
            if let Some(params) = op_def.get("params").and_then(|p| p.as_mapping()) {
                for (pk, pv) in params {
                    let pname = pk.as_str().expect("param name");
                    let r = pv.get("$ref").and_then(|x| x.as_str()).unwrap_or_else(|| {
                        panic!("actors.yaml {}/answers/{}/params/{}: params are $refs (ans-inline-type)", actor, op, pname)
                    });
                    if pname == identity {
                        has_identity = true;
                    }
                    request.push(AnswerField {
                        rust: snake_field(pname),
                        ty: answer_type(r, &mut scalar_imports, &mut entity_imports),
                        optional: false,
                        doc: None,
                    });
                }
            }
            if !has_identity {
                let (ty, _) = state_field_ty(&identity);
                request.insert(
                    0,
                    AnswerField {
                        rust: snake_field(&identity),
                        ty,
                        optional: false,
                        doc: Some(format!(
                            "The answering instance — the `{}-{{id}}` stream key IS the argument (no declared param restates it).",
                            actor
                        )),
                    },
                );
            }
            // REPLY fields: same-actor state composition.
            let mut reply: Vec<AnswerField> = Vec::new();
            let mut projections: Vec<(String, String)> = Vec::new();
            for (rk, rv) in op_def.get("reply").and_then(|r| r.as_mapping()).into_iter().flatten() {
                let rname = rk.as_str().expect("reply property name");
                let field = rv
                    .get("$ref")
                    .and_then(|x| x.as_str())
                    .and_then(parse_ref)
                    .filter(|pr| pr.path.len() == 3)
                    .map(|pr| pr.path[2].clone())
                    .unwrap_or_else(|| panic!("actors.yaml {}/answers/{}/reply/{}: reply properties are same-actor state $refs", actor, op, rname));
                let (ty, optional) = state_field_ty(&field);
                let doc = def
                    .get("state")
                    .and_then(|s| s.get(field.as_str()))
                    .and_then(|f| f.get("note"))
                    .and_then(|n| n.as_str())
                    .map(str::to_string);
                reply.push(AnswerField { rust: snake_field(rname), ty, optional, doc });
                projections.push((snake_field(rname), snake_field(&field)));
            }
            // Merge the imports into the field types (rendered names only — the emitter builds
            // one import line per file from the union below).
            let _ = (&scalar_imports, &entity_imports);
            out.push((
                AnswerOp {
                    actor: actor.to_string(),
                    op: op.to_string(),
                    pair: format!("{}{}", actor, pascal(op)),
                    identity_rust: snake_field(&identity),
                    projections,
                },
                request,
                reply,
                description,
            ));
        }
    }
    out
}

/// The declared answer operations, resolved — the client-surface emitter's view.
pub(crate) fn answer_ops(model: &Model) -> Vec<AnswerOp> {
    parse_answers(model).into_iter().map(|(op, _, _, _)| op).collect()
}

/// Emit `crates/domain/src/generated/answers.rs` — the `<Actor><Op>Request`/`<Actor><Op>Reply`
/// pair for every declared answer operation (PROP-20260815-142349 §2, #582), with UNCONDITIONAL
/// serde (the wire shape may not rot while the ask is local) and a TOLERANT reader (no
/// `deny_unknown_fields`; nullable fields are `Option` + `serde(default)`, so an absent value
/// round-trips as absent — additive-only producer / tolerant reader is the reply's whole
/// evolution contract, and a breaking reshape takes a NEW answer name).
pub(crate) fn emit_domain_answers(model: &Model) -> String {
    let mut out = String::from(
        "// GENERATED by the Captain.Food codegen from specs/actors.yaml `answers:` blocks\n// (PROP-20260815-142349 §2, #582) — do not edit by hand. The typed Request/Reply pair per\n// declared answer operation. A reply is a SNAPSHOT whose authority expires at send: never\n// stored, never folded, never api-exposed (`ans-ref-isolation`); the served stream version\n// rides the `AskOutcome` ENVELOPE (actor_client::ask), never a payload field. Serde is\n// UNCONDITIONAL and the reader TOLERANT (unknown fields are ignored, never refused):\n// additive-only producer / tolerant reader — a breaking reshape takes a NEW answer name\n// (review-carried V7). Round-trip tests live beside the hand folds\n// (crates/domain/src/{order,payment}.rs), built from real fold() fixtures so they cannot be\n// vacuous.\n",
    );
    let ops = parse_answers(model);
    if ops.is_empty() {
        return out;
    }
    // One import line over the union of every field type (bool is primitive; the rest scalars —
    // entity-typed params would import from entities the same way).
    let mut scalar_imports: BTreeSet<String> = BTreeSet::new();
    let mut entity_imports: BTreeSet<String> = BTreeSet::new();
    for (op, request, reply, _) in &ops {
        let _ = op;
        for f in request.iter().chain(reply.iter()) {
            if f.ty != "bool" {
                // Re-derive the import bucket from the model: scalars vs entities is decided by
                // where the name is declared.
                if model.defs.get("entities.yaml").map(|e| e.get(f.ty.as_str()).is_some()).unwrap_or(false) {
                    entity_imports.insert(f.ty.clone());
                } else {
                    scalar_imports.insert(f.ty.clone());
                }
            }
        }
    }
    out.push_str("\nuse serde::{Deserialize, Serialize};\n");
    if !scalar_imports.is_empty() {
        out.push_str(&format!(
            "use crate::generated::scalars::{{{}}};\n",
            scalar_imports.iter().cloned().collect::<Vec<_>>().join(", ")
        ));
    }
    if !entity_imports.is_empty() {
        out.push_str(&format!(
            "use crate::generated::entities::{{{}}};\n",
            entity_imports.iter().cloned().collect::<Vec<_>>().join(", ")
        ));
    }
    let emit_struct = |out: &mut String, name: &str, doc: &str, fields: &[AnswerField]| {
        out.push_str(&format!("\n/// {}\n", doc));
        out.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct ");
        out.push_str(name);
        out.push_str(" {\n");
        for f in fields {
            if let Some(d) = &f.doc {
                out.push_str(&format!("    /// {}\n", d));
            }
            if f.optional {
                out.push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
                out.push_str(&format!("    pub {}: Option<{}>,\n", f.rust, f.ty));
            } else {
                out.push_str(&format!("    pub {}: {},\n", f.rust, f.ty));
            }
        }
        out.push_str("}\n");
    };
    for (op, request, reply, description) in &ops {
        emit_struct(
            &mut out,
            &format!("{}Request", op.pair),
            &format!(
                "Ask `{}.{}` (actors.yaml#/{}/answers/{}): {}",
                op.actor, op.op, op.actor, op.op, description
            ),
            request,
        );
        emit_struct(
            &mut out,
            &format!("{}Reply", op.pair),
            &format!(
                "Reply of `{}.{}` — every property composes `#/{}/state/…` (declared once, served many).",
                op.actor, op.op, op.actor
            ),
            reply,
        );
    }
    out
}

// ─── crates/domain/src/generated/lifecycles.rs (aggregate lifecycle tables, ADR-20260720-004419) ──

/// Emit `crates/domain/src/generated/lifecycles.rs` — one module per aggregate declaring a
/// `lifecycle:` block in actors.yaml (ADR-20260720-004419): the status machine as plain data/match
/// (no SDK, no I/O — the domain stays dependency-free). `initial` maps a birth event to its entry
/// state; `transition` is the declared table (`Some(next)` iff legal — `None` = illegal move OR an
/// event outside the machine, a status no-op for the fold); `TERMINAL`/`is_terminal` close it.
pub(crate) fn emit_domain_lifecycles(model: &Model) -> String {
    let mut out = String::from(
        "// GENERATED by the Captain.Food codegen from specs/actors.yaml `lifecycle` blocks (ADR-20260720-004419)\n// — do not edit by hand. Aggregate lifecycle state machines as plain data/match: the fold and the\n// command handlers consult `transition` so the write side can never disagree with the declared spec.\n",
    );
    for lc in parse_lifecycles(model) {
        let status = ref_name(&lc.status_ref).unwrap_or_default();
        let module = snake_type(&lc.aggregate);
        out.push_str(&format!(
            "\n/// {} lifecycle over [`{}`] (specs/actors.yaml#/{}/lifecycle).\npub mod {} {{\n    use crate::generated::events::DomainEvent;\n    use crate::generated::scalars::{};\n\n",
            lc.aggregate, status, lc.aggregate, module, status
        ));
        let terminal: Vec<String> = lc.terminal.iter().map(|s| format!("{}::{}", status, s)).collect();
        out.push_str(&format!(
            "    /// Terminal states — no outgoing transitions.\n    pub const TERMINAL: &[{}] = &[{}];\n\n",
            status,
            terminal.join(", ")
        ));
        out.push_str(&format!(
            "    /// The state a birth event enters, or `None` when `event` does not birth this lifecycle.\n    pub fn initial(event: &DomainEvent) -> Option<{}> {{\n        match event {{\n",
            status
        ));
        for ini in &lc.initial {
            let ev = ref_name(&ini.event_ref).unwrap_or_default();
            match &ini.via {
                // Event-carried birth state (dynamic, ADR-20260721-093027): the recorded fact wins.
                Some(via) => out.push_str(&format!(
                    "            DomainEvent::{}(e) => Some(e.{}),\n",
                    ev,
                    snake_field(via)
                )),
                None => out.push_str(&format!("            DomainEvent::{}(_) => Some({}::{}),\n", ev, status, ini.to)),
            }
        }
        out.push_str("            _ => None,\n        }\n    }\n\n");
        out.push_str(&format!(
            "    /// The declared transition table: `Some(next)` iff `event` legally moves the machine from\n    /// `from`; `None` = illegal transition, or an event outside the machine (status no-op). A\n    /// dynamic-target arm matches only when the event's carried state equals the declared target.\n    pub fn transition(from: {}, event: &DomainEvent) -> Option<{}> {{\n        match (from, event) {{\n",
            status, status
        ));
        for t in &lc.transitions {
            let ev = ref_name(&t.event_ref).unwrap_or_default();
            for f in &t.from {
                match &t.via {
                    Some(via) => out.push_str(&format!(
                        "            ({}::{}, DomainEvent::{}(e)) if e.{} == {}::{} => Some({}::{}),\n",
                        status,
                        f,
                        ev,
                        snake_field(via),
                        status,
                        t.to,
                        status,
                        t.to
                    )),
                    None => out.push_str(&format!(
                        "            ({}::{}, DomainEvent::{}(_)) => Some({}::{}),\n",
                        status, f, ev, status, t.to
                    )),
                }
            }
        }
        out.push_str("            _ => None,\n        }\n    }\n\n");
        // target: the state an event drives the machine to IRRESPECTIVE of the current state — at
        // fold time the recorded fact wins (legality was enforced at append time by `transition`).
        // A dynamic (`via`) event's target is its carried payload field; a static event is only
        // emitted when it has a single target across all its transitions.
        let mut targets: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        let mut dynamic_via: BTreeMap<String, String> = BTreeMap::new();
        for t in &lc.transitions {
            if let Some(ev) = ref_name(&t.event_ref) {
                match &t.via {
                    Some(via) => {
                        dynamic_via.insert(ev, via.clone());
                    }
                    None => {
                        targets.entry(ev).or_default().insert(t.to.clone());
                    }
                }
            }
        }
        out.push_str(&format!(
            "    /// The state `event` drives the machine to, irrespective of the current state — at fold\n    /// time the recorded fact wins (legality was enforced at append time by [`transition`]). `None`\n    /// for an event outside the machine (or whose target depends on the current state). A dynamic\n    /// (event-carried) target is the event's payload field.\n    pub fn target(event: &DomainEvent) -> Option<{}> {{\n        match event {{\n",
            status
        ));
        for t in &lc.transitions {
            let ev = match ref_name(&t.event_ref) {
                Some(e) => e,
                None => continue,
            };
            if let Some(via) = dynamic_via.remove(&ev) {
                // emit each dynamic event once, in declaration order
                out.push_str(&format!("            DomainEvent::{}(e) => Some(e.{}),\n", ev, snake_field(&via)));
                continue;
            }
            if targets.get(&ev).map(|s| s.len()) != Some(1) {
                continue;
            }
            targets.remove(&ev); // emit each single-target event once, in declaration order
            out.push_str(&format!("            DomainEvent::{}(_) => Some({}::{}),\n", ev, status, t.to));
        }
        out.push_str("            _ => None,\n        }\n    }\n\n");
        out.push_str(&format!(
            "    /// Whether `state` is terminal (no outgoing transitions).\n    pub fn is_terminal(state: {}) -> bool {{\n        TERMINAL.contains(&state)\n    }}\n}}\n",
            status
        ));
    }
    out
}

/// Per-aggregate lifecycle state diagrams (mermaid `stateDiagram-v2`) from the declared `lifecycle`
/// blocks — (aggregate → diagram body), in actors.yaml order. Mirrors [`pm_sequence_map`]: callers
/// add their own framing (Markdown fence, HTML `<pre>`), so one source feeds every artifact.
pub(crate) fn lifecycle_state_map(model: &Model) -> Vec<(String, String)> {
    parse_lifecycles(model)
        .into_iter()
        .map(|lc| {
            // A dynamic (event-carried) edge is labelled `Event(field)` so the docs show which
            // payload field names the target state (ADR-20260721-093027).
            let label = |ev: &str, via: &Option<String>| match via {
                Some(v) => format!("{}({})", ev, v),
                None => ev.to_string(),
            };
            let mut lines: Vec<String> = vec!["stateDiagram-v2".into()];
            for ini in &lc.initial {
                lines.push(format!(
                    "  [*] --> {} : {}",
                    ini.to,
                    label(&ref_name(&ini.event_ref).unwrap_or_default(), &ini.via)
                ));
            }
            for t in &lc.transitions {
                let ev = label(&ref_name(&t.event_ref).unwrap_or_default(), &t.via);
                for f in &t.from {
                    lines.push(format!("  {} --> {} : {}", f, t.to, ev));
                }
            }
            for s in &lc.terminal {
                lines.push(format!("  {} --> [*]", s));
            }
            (lc.aggregate, lines.join("\n"))
        })
        .collect()
}

// ─── crates/application/src/generated/handlers.rs (issue #23 — require+guard+append handlers) ────

/// The per-aggregate SEAMS of the generated require+guard+append handlers (ADR-20260721-093027):
/// rehydration (existence + tenant scoping), stream naming and the illegal-move rejection stay
/// hand-written policy in `crates/application/src/commands.rs` (`pub(crate)`), referenced here by
/// expression — error-context construction is per-aggregate policy, not mechanics. Folded into the
/// DSL if a second consumer appears (PM-pipeline precedent, ADR-20260721-053456).
pub(crate) struct LifecycleHandlerSeam {
    pub(crate) aggregate: &'static str,
    /// The domain module whose `lifecycle` re-export holds this aggregate's generated tables.
    pub(crate) lifecycle: &'static str,
    /// Rehydration expression yielding `(state, version)` (awaited with `?`).
    pub(crate) require: &'static str,
    /// Rejection expression for a move the declared machine does not contain.
    pub(crate) reject: &'static str,
    /// Stream-name expression for the append.
    pub(crate) stream: &'static str,
    /// Event payload fields the COMMAND cannot carry, sourced from the REHYDRATED state instead:
    /// `(event property name, Rust expression over `state`)`. Consulted after the command's
    /// same-named fields and BEFORE both the required-field check and the `None` fallback, so an
    /// aggregate can supply from its own fold what no client should be trusted to assert — e.g. the
    /// DeliveryJob's `orderId`, known from its birth fact (D-QW1 option b, ADR-20260808-234907).
    pub(crate) state_fields: &'static [(&'static str, &'static str)],
}

pub(crate) const LIFECYCLE_HANDLER_SEAMS: &[LifecycleHandlerSeam] = &[
    LifecycleHandlerSeam {
        aggregate: "Order",
        lifecycle: "domain::order::lifecycle",
        require: "require_order(store, &cmd.order_id, &cmd.restaurant_id)",
        reject: "invalid_order_status(&cmd.order_id, state.status)",
        stream: "order_stream(&cmd.order_id)",
        state_fields: &[],
    },
    LifecycleHandlerSeam {
        aggregate: "Rider",
        lifecycle: "domain::rider::lifecycle",
        require: "require_rider(store, &cmd.rider_id)",
        reject: "reject(\"InvalidRiderStatusTransition\", json!({ \"riderId\": cmd.rider_id, \"currentStatus\": state.status, \"targetStatus\": cmd.status }))",
        stream: "rider_stream(&cmd.rider_id)",
        state_fields: &[],
    },
    LifecycleHandlerSeam {
        aggregate: "DeliveryJob",
        lifecycle: "domain::delivery_job::lifecycle",
        require: "require_delivery_job(store, &cmd.delivery_job_id)",
        reject: "invalid_delivery_status(&cmd.delivery_job_id, state.status, canonical_predecessor(cmd.status))",
        stream: "delivery_job_stream(&cmd.delivery_job_id)",
        // The job knows the order it delivers from its birth fact (`DeliveryRequested.orderId`,
        // required); UpdateDeliveryStatus deliberately carries no orderId — a client asserting it
        // would be surplus input the handler must distrust (PROP-20260808-233000 §4).
        state_fields: &[("orderId", "Some(state.order_id)")],
    },
];

/// The commands whose WHOLE handler is mechanical require+guard+append — the single emitted event is
/// built from the command by name and legalized by the declared lifecycle table. A command with
/// business checks beyond the machine (`DeliveryAlreadyAssigned` arbitration, rider-identity checks,
/// ensure-command idempotency, cross-aggregate invariants) stays hand-written in commands.rs.
pub(crate) const LIFECYCLE_GENERATED_HANDLERS: &[(&str, &str)] = &[
    ("Order", "AcceptOrder"),
    ("Order", "StartPreparation"),
    ("Order", "MarkOrderReady"),
    ("Order", "MarkOrderDelivered"),
    ("Order", "RejectOrder"),
    ("Order", "CancelOrderByCustomer"),
    ("Order", "CancelOrderByRestaurant"),
    ("Rider", "ChangeRiderStatus"),
    ("DeliveryJob", "UpdateDeliveryStatus"),
];

/// Emit `crates/application/src/generated/handlers.rs` — one require+guard+append command handler per
/// [`LIFECYCLE_GENERATED_HANDLERS`] row (issue #23, ADR-20260721-093027): rehydrate through the
/// aggregate's seam, build the single emitted event from the command's same-named fields (then the
/// seam's state-sourced fields, then `None` for an optional field neither supplies), consult the GENERATED lifecycle transition table,
/// append. Generation FAILS if the actors.yaml wiring stops matching (≠1 emitted event, an event
/// outside the declared machine, or a required event field the command cannot supply).
pub(crate) fn emit_application_handlers(model: &Model) -> String {
    let lifecycles: BTreeSet<String> = parse_lifecycles(model).into_iter().map(|l| l.aggregate).collect();
    let mut commands: BTreeSet<String> = BTreeSet::new();
    let mut events: BTreeSet<String> = BTreeSet::new();
    let mut fns = String::new();
    for (aggregate, command) in LIFECYCLE_GENERATED_HANDLERS {
        let seam = LIFECYCLE_HANDLER_SEAMS
            .iter()
            .find(|s| s.aggregate == *aggregate)
            .unwrap_or_else(|| panic!("handlers: no seam for aggregate '{}'", aggregate));
        if !lifecycles.contains(*aggregate) {
            panic!("handlers: aggregate '{}' declares no lifecycle", aggregate);
        }
        // The command's single emitted event, per the aggregate's receives wiring.
        let receives = model
            .defs
            .get("actors.yaml")
            .and_then(|a| a.get(*aggregate))
            .and_then(|n| n.get("receives"))
            .and_then(|r| r.as_sequence())
            .unwrap_or_else(|| panic!("handlers: actors.yaml#/{} has no receives", aggregate));
        let entry = receives
            .iter()
            .find(|e| {
                e.get("message")
                    .and_then(|m| m.get("$ref"))
                    .and_then(|r| r.as_str())
                    .map(|r| {
                        ref_target_file(r, "actors.yaml").as_deref() == Some("commands.yaml")
                            && ref_name(r).as_deref() == Some(command)
                    })
                    .unwrap_or(false)
            })
            .unwrap_or_else(|| panic!("handlers: actors.yaml#/{} does not receive '{}'", aggregate, command));
        let emits: Vec<String> = ref_strings(entry.get("emits")).iter().filter_map(|r| ref_name(r)).collect();
        let event = match emits.as_slice() {
            [one] => one.clone(),
            other => panic!("handlers: '{}' must emit exactly one event, got {:?}", command, other),
        };
        // Build the event payload from the command's same-named fields.
        let event_node = model
            .defs
            .get("events.yaml")
            .and_then(|e| e.get(event.as_str()))
            .unwrap_or_else(|| panic!("handlers: events.yaml#/{} missing", event));
        let required: BTreeSet<String> = event_node
            .get("required")
            .and_then(|r| r.as_sequence())
            .map(|s| s.iter().filter_map(|v| v.as_str().map(str::to_string)).collect())
            .unwrap_or_default();
        let cmd_props: BTreeSet<String> = model
            .defs
            .get("commands.yaml")
            .and_then(|c| c.get(*command))
            .and_then(|n| n.get("properties"))
            .and_then(|p| p.as_mapping())
            .map(|m| m.keys().filter_map(|k| k.as_str().map(str::to_string)).collect())
            .unwrap_or_default();
        let mut fields = String::new();
        if let Some(props) = event_node.get("properties").and_then(|p| p.as_mapping()) {
            for (k, _) in props {
                let prop = k.as_str().unwrap_or_default();
                let field = snake_field(prop);
                if cmd_props.contains(prop) {
                    fields.push_str(&format!("        {}: cmd.{},\n", field, field));
                } else if let Some((_, expr)) = seam.state_fields.iter().find(|(p, _)| *p == prop) {
                    fields.push_str(&format!("        {}: {},\n", field, expr));
                } else if required.contains(prop) {
                    panic!(
                        "handlers: required event field {}.{} has no same-named field on command {}",
                        event, prop, command
                    );
                } else {
                    fields.push_str(&format!("        {}: None,\n", field));
                }
            }
        }
        commands.insert((*command).to_string());
        events.insert(event.clone());
        fns.push_str(&format!(
            "\n/// Handle `commands.yaml#/{cmd}` → emit `events.yaml#/{evt}` — require + guard + append over\n/// the declared machine (`{lc}::transition`); an illegal move rejects through the\n/// aggregate's seam (specs/actors.yaml#/{agg}/lifecycle).\npub async fn {f}(\n    store: &dyn EventStore,\n    cmd: {cmd},\n    actor: &Actor,\n) -> Result<(), DomainError> {{\n    let (state, version) = {require}.await?;\n    let event = DomainEvent::{evt}({evt} {{\n{fields}    }});\n    if {lc}::transition(state.status, &event).is_none() {{\n        return Err({reject});\n    }}\n    Repository::new(store).save(&{stream}, version, &[event], actor).await.map(|_| ())\n}}\n",
            cmd = command,
            evt = event,
            agg = aggregate,
            lc = seam.lifecycle,
            f = snake_type(command),
            require = seam.require,
            reject = seam.reject,
            stream = seam.stream,
            fields = fields,
        ));
    }
    let cmd_list = commands.into_iter().collect::<Vec<_>>().join(", ");
    let evt_list = events.into_iter().collect::<Vec<_>>().join(", ");
    format!(
        "// GENERATED by the Captain.Food codegen from specs/actors.yaml (receives wiring + `lifecycle`\n// blocks), specs/commands.yaml and specs/events.yaml (issue #23, ADR-20260721-093027) — do not edit\n// by hand. The mechanical \"require + guard + append\" command handlers: rehydrate the aggregate\n// through its hand-written seam, build the single emitted event from the command's same-named\n// fields, legalize the move against the GENERATED lifecycle transition table, append.\n// `crates/application/src/commands.rs` re-exports these, so call sites and the behaviour suite (the\n// parity gate until #24's generated harness lands) are unchanged.\n\nuse serde_json::json;\n\nuse domain::generated::commands::{{{cmds}}};\nuse domain::generated::events::{{DomainEvent, {evts}}};\nuse domain::shared::errors::DomainError;\n\nuse crate::commands::{{\n    canonical_predecessor, delivery_job_stream, invalid_delivery_status, invalid_order_status,\n    order_stream, reject, require_delivery_job, require_order, require_rider, rider_stream,\n}};\nuse crate::ports::{{Actor, EventStore}};\nuse crate::repository::Repository;\n{fns}",
        cmds = cmd_list,
        evts = evt_list,
        fns = fns,
    )
}

