// GENERATED by the Captain.Food codegen from specs/actors.yaml (`receives` +
// `mailbox.partitions` + `reminders`) -- do not edit by hand (PROP-20260802-130500 phase 2,
// #306). The typed mailbox client for ONE actor, in its OWN crate: depending on this crate is the
// permission to address `DeliveryPartnerRegistration`, and nothing else.
//
// The client constructs NOTHING itself. Every row is assembled behind `actor_client::ActorDoor`,
// whose delegates own the lane, partition, principal and channel derivation -- so a typed send
// here and the string-keyed reference implementation in `actor_client` cannot drift (the
// out-of-crate drift guard in `crates/actor_client/tests/drift_guard.rs` proves it field for
// field). `MailboxEntry` and `MailboxAccess` are not nameable from this crate at all.
//
// EVERY method is spec-gated (product-owner directive, 2026-08-02 -- the declaration is the
// permission): `send` + `DeliveryPartnerRegistrationCommand` exist iff the actor receives >=1 COMMAND, `record` +
// `DeliveryPartnerRegistrationFact` iff it receives >=1 inbound FACT, `schedule`/`cancel_scheduling` iff it declares
// `reminders:`. An unjustified surface is ABSENT -- a compile error at any call site -- never
// uncallable-but-present.

use std::sync::Arc;

use actor_client::mailbox::{Envelope, Mailbox};
use actor_client::{ActorDoor, EnqueueOutcome};
use domain::shared::errors::DomainError;

/// The privacy SEAL: `Sealed` lives in a private module, so it cannot be named -- let alone
/// implemented -- outside this GENERATED crate. Every marker trait below requires it, so the
/// receive set this actor declares in actors.yaml is the receive set, period: widening it takes a
/// spec change and a regeneration, never a stray downstream `impl`. Since phase 2 each actor owns
/// its own seal, so a sibling client crate cannot even name this actor's marker supertrait.
mod sealed {
    pub trait Sealed {}
}

impl sealed::Sealed for domain::generated::commands::ApproveDeliveryPartnerAvailability {}
impl sealed::Sealed for domain::generated::commands::RegisterDeliveryPartnerAvailability {}
impl sealed::Sealed for domain::generated::commands::RevokeDeliveryPartnerAvailability {}

/// GENERATED from actors.yaml `DeliveryPartnerRegistration.receives`: marker for every COMMAND the `DeliveryPartnerRegistration` actor
/// receives. SEALED (private supertrait) so no impl can exist outside this generated crate --
/// sending a command this actor does not `receive` is a COMPILE error, not a runtime rejection.
pub trait DeliveryPartnerRegistrationCommand: sealed::Sealed + serde::Serialize + Send {
    /// The mailbox `message_type` (the commands.yaml key).
    const MESSAGE_TYPE: &'static str;
}

impl DeliveryPartnerRegistrationCommand for domain::generated::commands::ApproveDeliveryPartnerAvailability {
    const MESSAGE_TYPE: &'static str = "ApproveDeliveryPartnerAvailability";
}

impl DeliveryPartnerRegistrationCommand for domain::generated::commands::RegisterDeliveryPartnerAvailability {
    const MESSAGE_TYPE: &'static str = "RegisterDeliveryPartnerAvailability";
}

impl DeliveryPartnerRegistrationCommand for domain::generated::commands::RevokeDeliveryPartnerAvailability {
    const MESSAGE_TYPE: &'static str = "RevokeDeliveryPartnerAvailability";
}

/// GENERATED from actors.yaml: the strongly-typed client for ONE `DeliveryPartnerRegistration` mailbox lane --
/// `actor_id` is the addressed instance, the partition is the FROZEN `stable_partition` over
/// width 5 (`mailbox.partitions`). The only door to this actor.
pub struct DeliveryPartnerRegistrationClient {
    door: ActorDoor,
    actor_id: uuid::Uuid,
}

impl DeliveryPartnerRegistrationClient {
    /// A client addressing the `DeliveryPartnerRegistration` instance `actor_id`.
    pub fn new(mailbox: Arc<dyn Mailbox>, actor_id: uuid::Uuid) -> Self {
        Self { door: ActorDoor::new(mailbox), actor_id }
    }

    /// Enqueue one typed COMMAND on this lane (kind COMMAND). Delegates to the door's
    /// `send_command`, which builds the row with the shared `command_entry` constructor -- the
    /// very row `enqueue_worker_command` builds for the same inputs, field for field.
    pub async fn send<M: DeliveryPartnerRegistrationCommand>(
        &self,
        msg: M,
        env: Envelope,
    ) -> Result<EnqueueOutcome, DomainError> {
        let payload = serde_json::to_value(&msg)
            .map_err(|e| DomainError::Repository(format!("{} payload: {e}", M::MESSAGE_TYPE)))?;
        self.door.assert_addressed("DeliveryPartnerRegistrationClient", self.actor_id, M::MESSAGE_TYPE, &payload)?;
        self.door
            .send_command("DeliveryPartnerRegistration", 5, self.actor_id, M::MESSAGE_TYPE, payload, env)
            .await
    }
}
