// GENERATED by the Captain.Food codegen from the derived bin topology — do not edit by hand
// (ADR-20260807-183024 steps 3+4 and #385).

//! `actor-rider` — mailbox worker realizing the `Rider` aggregate -- drains ONLY its own lanes (the LANES const it hands the shared fleet, not a link fact).
//!
//! BUSINESS RUNTIME (#385): hosts the `Rider` mailbox lane's supervised worker fleet (the SAME `infrastructure::mailbox::standalone` runtime the adapter binaries use: leases, fencing, head-of-line, the money lanes' startup Stripe-fact backfill, graceful drain). Serves the `/health` + `/ping` probes its generated
//! Deployment (deploy/generated/manifests/bins/actor-rider.yaml) declares (`wired:true`, readiness
//! 503 until the hosted runtime is up), draining on SIGTERM.
//!
//! GATE-THEN-STABILIZE: runnable end-to-end, but the monolith `server` bin remains the DEPLOYED
//! production runtime until ADR-20260807-183024 steps (6)–(7) (#358 cutover) point traffic and
//! the mailbox at these pods.

// The manifest is the scope assertion; these imports make each declared domain-crate
// link a compile-checked fact (the linker cannot silently strip it).
use domain_common as _;
use domain_delivery as _;

/// The bin's scope-filtered typed configuration (#374 Q4): the declared keys of its linked
/// scopes + `common`, read once at startup — the same generated reader the monolith uses,
/// emitted over this bin's key subset.
mod config;

/// The c4-l2 container this binary realizes.
const BIN: &str = "actor-rider";
/// The bin's family in the deploy topology.
const FAMILY: &str = "actor";
/// The mailbox lane(s) this deployable drains -- and the WHOLE of its scoping: the image
/// links every domain crate behind `bin_runtime`, so this list is a routing fact, not a link one
/// (#475).
const LANES: &[&str] = &["Rider"];

#[tokio::main]
async fn main() {
    // Identity FIRST, before any fallible startup (ADR-20260721-175411): a boot that never binds
    // still names its version in the logs.
    println!("{BIN} ({FAMILY}) starting -- version {}, business runtime (#385)", bin_runtime::build_version());

    // Configuration gate (PROP-20260729-004500): every problem reported at once; production and
    // staging refuse to start on a broken configuration, development reports and continues.
    let (config, problems) = config::Config::resolve();

    // Telemetry SECOND -- after config (it needs LOG_LEVEL and the ingest key), before every
    // worker, so their startup lines are structured and correlated (issue #191).
    let mut telemetry_guard = bin_runtime::init_telemetry(bin_runtime::TelemetrySettings {
        api_key: config.honeycomb_api_key.clone(),
        endpoint: config.honeycomb_api_endpoint.clone(),
        dataset: config.honeycomb_dataset.clone(),
        sample_ratio: config.otel_traces_sample_ratio.clone(),
        log_level: config.log_level.clone(),
        profile: config.profile.to_string(),
    });
    if !problems.is_empty() {
        let report = config::MissingConfig { profile: config.profile, problems };
        tracing::error!(profile = %config.profile, "{report}");
        if config.must_stop_on_problems() {
            // Flush before exiting, or the error explaining the failed deploy never leaves the box.
            telemetry_guard.shutdown();
            // 78 = EX_CONFIG (sysexits.h): a configuration error, not a crash.
            std::process::exit(78);
        }
        tracing::warn!(profile = %config.profile, "starting anyway -- production and staging STOP here");
    }
    tracing::info!("{}", config.boot_report());

    // Without a database this runtime cannot host its slice: stay a viable pod that says
    // so (readiness 503) rather than crash-loop -- the config gate already stopped prod/staging.
    let db_ready = !config.database_url.is_empty();
    if db_ready {
        let pool = bin_runtime::pg_pool(&config.database_url, config.database_pool_max_connections)
            .unwrap_or_else(|e| panic!("{BIN}: pg pool init: {e}"));
        bin_runtime::spawn_actor_fleet(
            pool,
            BIN,
            LANES,
            bin_runtime::fail_closed_payments(),
            config.reminder_windows(),
            bin_runtime::MailboxSettings {
                lease_seconds: config.mailbox_lease_seconds,
                heartbeat_seconds: config.mailbox_heartbeat_seconds,
                max_delivery_attempts: config.mailbox_max_delivery_attempts,
            },
        );
    } else {
        tracing::warn!(bin = BIN, "DATABASE_URL unset -- no workers hosted, readiness stays 503");
    }
    // Readiness = the fleet's host has its database; the fleet supervises itself (respawn
    // with backoff) and reports per-lane state through the mailbox rows, not this probe.
    let health: bin_runtime::HealthFn = std::sync::Arc::new(move || {
        (
            db_ready,
            serde_json::json!({
                "lanes": LANES,
                "db": if db_ready { "configured" } else { "not_configured" },
            }),
        )
    });

    bin_runtime::serve_probes(BIN, FAMILY, &config.port.to_string(), health).await;
    telemetry_guard.shutdown();
}
